### ISSUE TITLE
I can't connect to the server.

### ISSUE THREAD

**Issue by songminwoo1** [kaist-cp/cs220#10]
![image](https://user-images.githubusercontent.com/57557231/187856012-404343ab-964e-432a-ab0e-e26c047a8e4d.png)

I did nothing else and just tried ssh connect.
I have no idea why this is happening. I took this class an year ago and now I'm retaking the class. Does that may be the reason?

**Comment by minseongg** [comment]
Could you please try again after remove `C:\\Users\\alsdn/.ssh/known_hosts` in your local environment?

**Comment by jeehoonkang** [comment]
Please see #15
