### ISSUE TITLE
Midterm) Concern about bad Wifi in the lecture room

### ISSUE THREAD

**Issue by KCY-G** [kaist-cp/cs220#102]
Welcome-Kaist Wifi in the lecture room is quite weak and unstable.
It would be difficult to take the exam using the wifi.

**Comment by theonlyrealALEX** [comment]
I recommend to use a personal hotspot from your phone

**Comment by m-spitfire** [comment]
You can also use eduoram in the lecture room. See kaist ICT website for how to set it up.

**Comment by minseongg** [comment]
Thanks for question. We will prepare additional Wifis in the lecture room.

**Comment by KCY-G** [comment]
Thank you all!
