### ISSUE TITLE
[Homework 5] Error message on gg.kaist.ac.kr

### ISSUE THREAD

**Issue by rolsj** [kaist-cp/cs220#105]
Does this mean that the code is not passing the test cases? Or is it referring to another issue?

```
===== SETUP =====

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
autoconf is already the newest version (2.71-2).
libgmp-dev is already the newest version (2:6.2.1+dfsg-3ubuntu1).
pkg-config is already the newest version (0.29.2-1ubuntu3).
opam is already the newest version (2.1.2-1).
The following packages were automatically installed and are no longer required:
  binutils-riscv64-linux-gnu cpp-11-riscv64-linux-gnu cpp-riscv64-linux-gnu
  gcc-11-cross-base-ports gcc-11-riscv64-linux-gnu-base
  gcc-12-cross-base-ports libasan6-riscv64-cross libatomic1-riscv64-cross
  libc6-dev-riscv64-cross libc6-riscv64-cross libgcc-11-dev-riscv64-cross
  libgcc-s1-riscv64-cross libgomp1-riscv64-cross
  libstdc++-11-dev-riscv64-cross libstdc++6-riscv64-cross
  linux-libc-dev-riscv64-cross
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.

===== CHECK =====
[2022-10-06 08:55:35,952: WARNING/ForkPoolWorker-32] Demoting to runner...

<><> Required setup - please read <><><><><><><><><><><><><><><><><><><><><><><>

  In normal operation, opam only alters files within ~/.opam.

  However, to best integrate with your system, some environment variables
  should be set. If you allow it to, this initialisation step will update
  your bash configuration by adding the following line to ~/.profile:

    test -r /home/runner/.opam/opam-init/init.sh && . /home/runner/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true

  Otherwise, every time you want to access your opam installation, you will
  need to run:

    eval $(opam env)

  You can always re-run this setup with 'opam init' later.

Do you want opam to modify ~/.profile? [N/y/f]
(default is 'no', use 'f' to choose a different file) 
A hook can be added to opam's init scripts to ensure that the shell remains in sync with the opam environment when they are loaded. Set that up? [y/N] n
[NOTE] It seems you have not updated your repositories for a while. Consider updating them with:
       opam update

[NOTE] Package alt-ergo is already installed (current version is 2.4.2).
[NOTE] Package why3 is already installed (current version is 1.5.0).
Prover Alt-Ergo version 2.4.2 is not recognized.
  Known versions for this prover: 2.4.0, 2.4.1.
1 prover(s) added (including 1 prover(s) with an unrecognized version)
Save config to /home/runner/.why3.conf
Cloning into 'cs220'...
19c19
<   =
---
>   = 
```

**Comment by minseongg** [comment]
There seems to be a difference between your code and the skeleton code at L19.

Could you please copy and paste the [skeleton code's L19](https://github.com/kaist-cp/cs220/blob/main/assets/why3/binary_search.mlw#L19) to your code's L19 and then try again?

**Comment by rolsj** [comment]
Is the problem solved?
'''
===== SETUP =====

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
autoconf is already the newest version (2.71-2).
libgmp-dev is already the newest version (2:6.2.1+dfsg-3ubuntu1).
pkg-config is already the newest version (0.29.2-1ubuntu3).
opam is already the newest version (2.1.2-1).
The following packages were automatically installed and are no longer required:
  binutils-riscv64-linux-gnu cpp-11-riscv64-linux-gnu cpp-riscv64-linux-gnu
  gcc-11-cross-base-ports gcc-11-riscv64-linux-gnu-base
  gcc-12-cross-base-ports libasan6-riscv64-cross libatomic1-riscv64-cross
  libc6-dev-riscv64-cross libc6-riscv64-cross libgcc-11-dev-riscv64-cross
  libgcc-s1-riscv64-cross libgomp1-riscv64-cross
  libstdc++-11-dev-riscv64-cross libstdc++6-riscv64-cross
  linux-libc-dev-riscv64-cross
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.

===== CHECK =====
[2022-10-06 12:12:57,823: WARNING/ForkPoolWorker-32] Demoting to runner...

<><> Required setup - please read <><><><><><><><><><><><><><><><><><><><><><><>

  In normal operation, opam only alters files within ~/.opam.

  However, to best integrate with your system, some environment variables
  should be set. If you allow it to, this initialisation step will update
  your bash configuration by adding the following line to ~/.profile:

    test -r /home/runner/.opam/opam-init/init.sh && . /home/runner/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true

  Otherwise, every time you want to access your opam installation, you will
  need to run:

    eval $(opam env)

  You can always re-run this setup with 'opam init' later.

Do you want opam to modify ~/.profile? [N/y/f]
(default is 'no', use 'f' to choose a different file) 
A hook can be added to opam's init scripts to ensure that the shell remains in sync with the opam environment when they are loaded. Set that up? [y/N] n
[NOTE] It seems you have not updated your repositories for a while. Consider updating them with:
       opam update

[NOTE] Package alt-ergo is already installed (current version is 2.4.2).
[NOTE] Package why3 is already installed (current version is 1.5.0).
Prover Alt-Ergo version 2.4.2 is not recognized.
  Known versions for this prover: 2.4.0, 2.4.1.
1 prover(s) added (including 1 prover(s) with an unrecognized version)
Save config to /home/runner/.why3.conf
Cloning into 'cs220'...
Checking if there is difference between the skeleton code and submission at L1-L19...
File submission.mlw:
Goal binary_search'vc.
Prover result is: Timeout (5.00s).
'''

**Comment by minseongg** [comment]
It seems like your code has failed to prove the postcondition. (Relevant issue: https://github.com/kaist-cp/cs220/issues/77)
