### ISSUE TITLE
Do expressions not include ending semicolons always?

### ISSUE THREAD

**Issue by rowletter** [kaist-cp/cs220#110]
While reviewing 'The Rust Programming Language', I found out the sentence 'Expressions do not include ending semicolons.' in the middle of 3.3 Functions. I remember that the professor said it also in the lecture. Numerous lines of code I saw and written so far didn't tackled the sentence till finding out this sentence: 'Calling a macro is an expression.'

One of the most frequently used macro is println macro. But when we use it, we put ending semicolon like this code(which is the code that the book uses to explain that expressions do not include ending semicolons):
```
fn main() {
    let y = {
        let x = 3;
        x + 1
    };
    println!("The value of y is: {y}");
}
```
I got `x + 1` is an expression, and the block also, since the block is from `{` to `}`, which does not contain ending semicolon. But not for println macro. The line clearly contains the ending semicolon. 

Though there was no explanation about this in the book, I believed the sentence, so I tried to make it sense. Where I ended up is that `{}` in str works as %d or %s in C/C++, and `{}` inside string is the thing which is called 'calling a macro'. But I soon found out that this explanation is not enough for me since we print out something which is not in `{}`, which is the role of the println macro. 

So do the sentence and the println macro stands at the same time? If they do, how?

**Comment by zzz845zz** [comment]
"Expressions do not include ending semicolons" does not mean "you should not add the semicolon at the end of expression". It means "There is no expression which has the ending semicolons at the end".

If you add the ending semicolon at the end of the expression, then that will be a statement, not an expression. Note that Rust needs an expression to return some type.

For example,  Let's assume there is an `add!` macro, which adds two values and returns the added value.

```rust
// This `add1()` works well.
fn add1(v1: usize, v2: usize) -> usize {
    add!(v1, v2) // expr
}

// But this `add2()` can't be compiled because 
// Rust needs an expression to return some type.
fn add2(v1: usize, v2: usize) -> usize {
    add!(v1, v2); // statement
}
```

**Comment by minseongg** [comment]
For more details about Statements and Expressions, please refer to these:

- Macro Invocation: https://doc.rust-lang.org/reference/macros.html
- Statements: https://doc.rust-lang.org/reference/statements.html
- Expressions: https://doc.rust-lang.org/reference/expressions.html

In Rust syntax, `MacroInvocation` is considered as expression and `MacroInvocationSemi` is considered as statement.
