### ISSUE TITLE
[Homework 5] Timeout

### ISSUE THREAD

**Issue by malore350** [kaist-cp/cs220#111]
I wrote my code a while ago but now that I wanted to submit, I get the timeout (5s).

I know that this question has been previously asked, and the answer was that it doesn't pass all postconditions, but when I run it on my device and check it with 5000 steps, it does pass all postconditions. Should my code work with less steps? How should I solve this issue?

**Comment by Hado-lee** [comment]
I have the same problem. My code works for 5000 steps prove, but it didn't work at gg.

**Comment by zzz845zz** [comment]
We extended the time limit to 20 seconds. Could you please try again? 

If the same error occurs, please send your submission file to [seungmin.jeon@kaist.ac.kr](mailto:seungmin.jeon@kaist.ac.kr).

**Comment by Hado-lee** [comment]
it works! Thanks a lot

**Comment by malore350** [comment]
Just checked: still a timeout. So, I am sending it to you. Thanks.
