### ISSUE TITLE
[Homework 5] add 0 in  the end of the function

### ISSUE THREAD

**Issue by intellkim** [kaist-cp/cs220#113]
when I add 0 in the end of the function, postcondition that forall i: int. result <= i < length a -> v <= a[i] don't meet. But if I do not use 0, the program makes error what should i do?

**Comment by m-spitfire** [comment]
0 at the end of the function is for return value of function. When the execution reaches to that zero the function will return it.

**Comment by intellkim** [comment]
But when I put 0 at the end of the function, it don't meet the third postcondition that forall i: int. result <= i < length a -> v <= a[i].

**Comment by m-spitfire** [comment]
You don't have to put 0. As I said 0 is the value you're returning at the end of the function. You may want to change it for satisfying postcondition.

**Comment by intellkim** [comment]
I don't know what to put. I take all cases in while loop so there is no out in the while loop and return the end value

**Comment by zzz845zz** [comment]
You should return the index of the item you searched to satisfy all postcondition.

**Comment by intellkim** [comment]
when I restore the value to return it later, the variant doesn't decrease so the loop doesn't end. However, if I restore it and return it the error message show up. I don't know what to write in the end of code.

**Comment by choejms** [comment]
Every time a loop runs, some positive quantity should decrease by some amount, so if the variant is not decreasing, probably there is something wrong with the condition of the loop.
