### ISSUE TITLE
[Homework 4] processing assignment in eval function of parser

### ISSUE THREAD

**Issue by shapoid** [kaist-cp/cs220#114]
I have no idea how to process `Command::variable `.
For example, if "v1 = v" is parsed, climb function need to match `Rule::var` for both "v1" and "v" in `primary`.
I want to return `Command` type for eval function, so "v1" is stored in Command.variable. I don't know ho w to store "v" in `Command.expression`. I think the rest of expression, "v" need to be called with eval, but I don't know how to do that in primary closure.
When I print the tokens returned from `SyntaxParser::parse` by `dbg!`, it gives me 

<img width="420" alt="스크린샷 2022-10-07 오후 3 46 12" src="https://user-images.githubusercontent.com/35846889/194484777-4ac157fe-fbf3-4f65-95b2-039ec117d10e.png">

first Pair, "v1" has no inner, so I need method to call second Pair "v" by doing something for first pair in primary closure of climb function call. Please correct me, if my understanding is wrong.

**Comment by minseongg** [comment]
You can fill the fields of `Command` by applying climb function for each tokens returned by `SyntaxParser::parse`.

For example, there are three tokens in your code: `v1`, `v`, and EOI.

- `v1`: This pair has rule `var`, its evaluated result should be stored in `variable` field of `Command`.
- `v`: This pair has rule `expr`, its evaluated result should be stored in `expression` field of `Command`.
- EOI: This pair has rule `EOI`, you can just ignore it.

**Comment by shapoid** [comment]
Thank you for your comment. I wonder for `v1`, what should be the `expression` field of `Command`? I think it cannot be blank.

**Comment by minseongg** [comment]
Ah, I see. It should be `Expression::Variable("v1")`.

**Comment by shapoid** [comment]
I think eval function get all tokens. I don't know why eval function only process first Pair.

**Comment by shapoid** [comment]
> 

Oh, I will try this.

**Comment by shapoid** [comment]
> You can fill the fields of `Command` by iterating for each token returned by `SyntaxParser::parse` function.
> 
> For example, there are three tokens in your code: `v1`, `v`, and EOI.
> 
> * `v1`: This pair has rule `var`. It should be stored in `variable` field of `Command`. (`Some("v1")`)
> * `v`: This pair has rule `expr`. You need to apply climb function, and its evaluated result should be stored in `expression` field of `Command`. (`Expression::Variable("v")`)
> * EOI: This pair has rule `EOI`, you can just ignore it.

Oh, I will try this.

**Comment by shapoid** [comment]
Thank you! solved it.
