### ISSUE TITLE
[Homework 5] How to solve postcondition?

### ISSUE THREAD

**Issue by vm3fk5dla2** [kaist-cp/cs220#115]
How to solve postcondition

    ensures  { forall i: int. 0 <= i < result -> a[i] < v }
    ensures  { forall i: int. result <= i < length a -> v <= a[i] }

by invariant??..

![image](https://user-images.githubusercontent.com/52191701/194505611-63dcb0bd-af62-46d5-8107-a63daf4e5c83.png)

Can I get some hint please?..

**Comment by minseongg** [comment]
I hope you can get hint from this example: https://gitlab.inria.fr/why3/why3/-/blob/master/examples/binary_search.mlw

**Comment by yj-han** [comment]
(I'm not a TA though...!) In my case, thinking about special cases like `binary_search [1, 1, 1, 1, 1] 1` and `binary_search [1, 2, 3, 4, 7, 8] 5` helped me find out what conditions should remain unchanged in a loop to ensure the postconditions.
