### ISSUE TITLE
[Homework 4] Missing documentation for an enum

### ISSUE THREAD

**Issue by koosaga** [kaist-cp/cs220#118]
It seems I am missing a documentation, but I'm now unsure where I should even add new documentation.
<img width="1533" alt="image" src="https://user-images.githubusercontent.com/12739513/194562190-4931d08f-b3d7-4d61-bc0d-074a3c0b9632.png">

**Comment by Inhyeok-Jeong** [comment]
If you removed some comments describing the code in the top of context.rs or parser.rs, it causes missing doc error. Check comment in original file.

**Comment by m-spitfire** [comment]
You have modified the original skeleton code where the `SyntaxParser` was inside a module called `inner` which had the following macros
```rust
#[allow(missing_docs)]
#[allow(missing_debug_implementations)]
```
that was suppressing the errors you were seeing. As the above comment said, check the original file.

**Comment by minseongg** [comment]
In the [original skeleton code](https://github.com/kaist-cp/cs220/blob/main/src/assignments/assignment04/parser.rs#L6-L14), you can use `SyntaxParser` in your code by using `use` declaration. (e.g. Add `use inner::*;` in `parser.rs`)

**Comment by koosaga** [comment]
Oh I see, thank you so much!
