### ISSUE TITLE
[HW4] How can I iterate return value of parse function?

### ISSUE THREAD

**Issue by koosaga** [kaist-cp/cs220#120]
I called this function:
<img width="824" alt="image" src="https://user-images.githubusercontent.com/12739513/194574733-c5276b3a-3697-49ad-a444-fa8f857f5da9.png">

It seems this function contains more than one tokens, and the precClimber is only capable of parsing one of them.
https://github.com/kaist-cp/cs220/issues/114

Therefore, I have to iterate this structure, but I couldn't find such method from the official document.
How can I iterate such structure?

**Comment by minseongg** [comment]
Since [`Pairs` implements `Iterator` trait](https://docs.rs/pest/latest/pest/iterators/struct.Pairs.html#impl-Iterator-for-Pairs%3C%27i%2C%20R%3E), You can iterate it by using `for` loop. ([Reference](https://doc.rust-lang.org/rust-by-example/flow_control/for.html#for-and-range))

e.g)

```rust
let parse_result = SyntaxParser::parse(Rule::Command, line)?;

for pair in parse_result {
    ...
}
```

**Comment by koosaga** [comment]
I swear I tried it, but I tried it again and it somehow works. Thank you!
