### ISSUE TITLE
Question for average score of HW 1 ~ HW5

### ISSUE THREAD

**Issue by JoonsungKwon** [kaist-cp/cs220#127]
May I know about the average score for each assignment?

**Comment by minseongg** [comment]
The average score is as follows:

- Homework 1: https://github.com/kaist-cp/cs220/issues/6#issuecomment-1278152342
- Homework 2: https://github.com/kaist-cp/cs220/issues/7#issuecomment-1278155225
- Homework 3: https://github.com/kaist-cp/cs220/issues/36#issuecomment-1278155499
- Homework 4: https://github.com/kaist-cp/cs220/issues/41#issuecomment-1278156008
- Homework 5: https://github.com/kaist-cp/cs220/issues/48#issuecomment-1278156525
