### ISSUE TITLE
Regarding Midterm Range

### ISSUE THREAD

**Issue by hoosong0235** [kaist-cp/cs220#129]
1. Do we have to study syntax and semantics of why3 for midterm exam?
2. Are ex1_eucl_div.mlw, ex2_fact.mlw, and ex4_two_way.mlw in the range of midterm exam?

Thanks.

**Comment by jeehoonkang** [comment]
- why3 syntax/semantics: you don't need to write a perfect why3/whyml programs in the exam. but you should understand the underpinning concepts.
- `*.mlw` files are covered in the midterm.
