### ISSUE TITLE
Everything was ok with cargo test, but not correct when I submit the code.

### ISSUE THREAD

**Issue by dannyiscard** [kaist-cp/cs220#13]
I checked the code passing every testcase by 'cargo test --lib assignment01_grade'.

But The website says NO when I submit the code on gg.kaist.ac.kr, and I still have no idea why.

Here is the log with exposed personal code removed.

===== SETUP =====

===== CHECK =====
[2022-09-01 15:05:09,652: WARNING/ForkPoolWorker-32] Demoting to runner...
info: downloading installer
info: profile set to 'default'
info: default host triple is x86_64-unknown-linux-gnu
warning: Updating existing toolchain, profile choice will be ignored
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.63.0 (4b91a6ea7 2022-08-08)

Rust is installed now. Great!

To get started you may need to restart your current shell.
This would reload your PATH environment variable to include
Cargo's bin directory ($HOME/.cargo/bin).

To configure your current shell, run:
source "$HOME/.cargo/env"
Cloning into 'cs220'...
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.63.0 (4b91a6ea7 2022-08-08)

info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'

  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.65.0-nightly (9243168fa 2022-08-31)

info: checking for self-updates
Diff in /app/files/checks/ea08f89a-52b1-46fd-81f0-4b9d356399fd/cs220/src/assignments/assignment01.rs at line 17:

**Comment by minseongg** [comment]
Does your code pass self-grader? (`./scripts/grade-01.sh`)

In self-grader, formatter and linter are performed before executing tests. ([scripts/grade-01.sh#L20-L22](https://github.com/kaist-cp/cs220/blob/main/scripts/grade-01.sh#L20-L22))

If your code does not pass the self-grader, please apply the suggestions of `cargo fmt --check` and `cargo clippy`, then rerun self-grader.

**Comment by idealyhn** [comment]
If I test my code with the `zsh grade-02.sh` command, it gives me some errors.

<details>
<summary>Errors</summary>
```
bash grade-02.sh 
info: syncing channel updates for 'stable-x86_64-apple-darwin'

  stable-x86_64-apple-darwin unchanged - rustc 1.63.0 (4b91a6ea7 2022-08-08)

info: syncing channel updates for 'nightly-x86_64-apple-darwin'

  nightly-x86_64-apple-darwin unchanged - rustc 1.65.0-nightly (2e35f954a 2022-09-01)

info: checking for self-updates
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
Running with cargo...
./grade-utils.sh: line 61: timeout: command not found
Test failed:    cargo test  --lib assignment02_grade
```
</details>

But my code passed gg.kaist's test... strange...
