### ISSUE TITLE
Proving mathematical theorems/verifying algorithms with programs

### ISSUE THREAD

**Issue by choejms** [kaist-cp/cs220#131]
Hi, after learning about Why3, I got interested in proving mathematical theorems/verifying algorithms with programs.
Are there any recommended textbooks/online materials/lecture videos for delving deeper into this field?

Also, there seems to be a few programming languages for proving theorems: ex) Why3, Agda, Lean, Coq. 
Is there any recommendation for the language as well. 

Thank you

**Comment by jeehoonkang** [comment]
I'm familiar more with Coq than with the others. I suggest you have a look at <https://softwarefoundations.cis.upenn.edu/>, especially volumes 1 and 2.

**Comment by choejms** [comment]
Thank you. The link was something I was looking for.
