### ISSUE TITLE
Question for Midterm range.

### ISSUE THREAD

**Issue by vm3fk5dla2** [kaist-cp/cs220#132]
Dear professor and TAs.

I have a question about the range of Midterm.

Chapter 4: Ownership  is not covered in midterm, but & and (&mut) is many used in other Chapters.
Then should we know about concept of  & and (&mut) in detail? or perceive as just "used in that case..."?

Thank you.

**Comment by jeehoonkang** [comment]
we've discussed that they're references, and you should understand that for the midterm exam.

**Comment by vm3fk5dla2** [comment]
> we've discussed that they're references, and you should understand that for the midterm exam.

Thank you professor.

I hope you have great weekend.
