### ISSUE TITLE
Postcondition of two_way.mlw

### ISSUE THREAD

**Issue by choejms** [kaist-cp/cs220#134]
Hi, in two_way.mlw, for postcondition we have 
`ensures { true }`.

But shouldn't this be changed to 
`ensures { sorted (a) }`? Because after the function is complete, `a` should be sorted.
Right now, even if I remove some invariants in the loop, the algorithm is verified because the postcondition is always true.

Below is the code for two_way_sort.

```
 predicate sorted (a: array bool) =
    forall i1 i2: int. 0 <= i1 <= i2 < a.length -> a[i1] << a[i2]

  let two_way_sort (a: array bool) : unit
    ensures { true }
  =
    label Init in
    let ref i = 0 in
    let ref j = length a - 1 in
    while i < j do
      invariant { forall i1: int. 0 <= i1 < i -> a[i1] = False }
      invariant { forall i2: int. j < i2 < length a -> a[i2] = True }
      invariant { 0 <= i /\ j < length a }
      variant { j - i }
      if not a[i] then
        incr i
      else if a[j] then
        decr j
      else begin
        swap a i j;
        incr i;
        decr j
      end
    done

end
```

**Comment by Lee-Janggun** [comment]
Yes, doing 3 would mean (1) changing the postcondition to `sorted a` and (2) still proving it using the why3 framework.

**Comment by choejms** [comment]
Thank you for the explanation
