### ISSUE TITLE
[Chapter 3] Can functions be expressions?

### ISSUE THREAD

**Issue by nargizas** [kaist-cp/cs220#135]
In the Rust book, it says that function definitions are also statements. Expressions evaluate to a resulting value. If the function returns a value, is it considered to be an expression? Or is the function call an expression?

**Comment by m-spitfire** [comment]
The declaration of a function is a statement. The call of the function can be an expression.

**Comment by minseongg** [comment]
For more details, please refer to this:

- Function declaration is a statement: [Item declarations statement](https://doc.rust-lang.org/reference/statements.html#item-declarations), [Functions](https://doc.rust-lang.org/reference/items/functions.html)
- Function call is an expression: [Call expressions](https://doc.rust-lang.org/reference/expressions/call-expr.html)

**Comment by nargizas** [comment]
Got it, thanks!
