### ISSUE TITLE
Should we consider linter or macro such as #[deny(clippy::let_and_return)] or #[must_use] etc. while writing codes on the exam?

### ISSUE THREAD

**Issue by 7dy109** [kaist-cp/cs220#136]
I guess you have announced it before, but I'm not sure about this point.
When I do homework, I can see "No" in "success?" in gg, or I couldn't compile my homework file if I do not satisfy the macro or linter.
Should we consider them while writing codes for the exam?

ex)
note: `#[deny(clippy::let_and_return)]` implied by `#[deny(warnings)]`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#let_and_return
help: return the expression directly

Please format your code with `cargo fmt` first.

= note: `#[deny(clippy::explicit_counter_loop)]` implied by `#[deny(warnings)]`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#explicit_counter_loop

error: could not compile `cs220` due to 2 previous errors

The above 3 are from the assignment log in gg.

#[must_use] - this is referenced in https://github.com/kaist-cp/cs220/issues/59

**Comment by minseongg** [comment]
You do not need to consider formatter and linter in the exam.

**Comment by 7dy109** [comment]
Thank you for your quick and clear answer!
