### ISSUE TITLE
Can I ask you the meaning of (except internal implementation source code)?

### ISSUE THREAD

**Issue by 7dy109** [kaist-cp/cs220#137]
in https://github.com/kaist-cp/cs220/issues/19, there is the comment "[Rust Playground](https://play.rust-lang.org/) and [Rust Standard Library Documentation](https://doc.rust-lang.org/std/) (except internal implementation source code)"
what is the meaning of (except internal implementation source code)?
which area I cannot see in the standard library document?
I really appreciate for efforts that TAs contribute.
Thank you for answering lots of my questions.

**Comment by choejms** [comment]
I think it means you are not supposed to click Source on the top right corner to check the internal implementation.

<img width="1293" alt="스크린샷 2022-10-17 오후 9 28 58" src="https://user-images.githubusercontent.com/90259205/196177284-d5d23b53-2c84-4ce3-8b42-edee06277454.png">

**Comment by 7dy109** [comment]
Thank you all!! I really appreciate it. I will close this issue after the exam.
