### ISSUE TITLE
Time complexity of type checking algorithm

### ISSUE THREAD

**Issue by choejms** [kaist-cp/cs220#139]
According to slide pg 35, type checking algorithm has sub-O(n^2) complexity.
What does `n` mean?

<img width="865" alt="스크린샷 2022-10-18 오전 2 09 04" src="https://user-images.githubusercontent.com/90259205/196240154-a49e1a49-e7e7-473c-8eb3-1574064b383f.png">

**Comment by jeehoonkang** [comment]
the code size
