### ISSUE TITLE
[HW6] Is my submission nullified?

### ISSUE THREAD

**Issue by cwj2021** [kaist-cp/cs220#140]
I just noticed that I had to submit the solution after 10/7. But I realized that I submitted on 10/7 18:59. Is my submission is nullified?

**Comment by minseongg** [comment]
We did not nullify previous submissions because there was no extra test cases. If you can see "Yes" at "SUBMITTED?" column, then you'll get full score.

I'm sorry that I didn't make the announcement..!

**Comment by cwj2021** [comment]
Thank you so much!
