### ISSUE TITLE
[HW8] Mistake in function signature of `repeat`

### ISSUE THREAD

**Issue by m-spitfire** [kaist-cp/cs220#145]
Hello!

When I try to use the function `f` inside a closure in the function `repeat` compiler says that 
```
error[E0596]: cannot borrow `f` as mutable, as it is not declared as mutable
  --> src/assignments/assignment08.rs:18:38
   |
11 | pub fn repeat<T, F: FnMut(T) -> T>(n: usize, f: F) -> impl FnMut(T) -> T {
   |                                              - help: consider changing this to be mutable: `mut f`
...
18 |     <redacted> f(<redacted>)
   |                          ^ cannot borrow as mutable
```
This is because as the `f` implements `FnMut` when we need to call it it has to be mutable since the [`call_mut`](https://doc.rust-lang.org/std/ops/trait.FnMut.html#tymethod.call_mut) function in `FnMut` takes the `self` argument as a mutable reference.

So I think the function signature should have been different.

I am not sure if this was intended or not, but usually, when you solve an assignment you wouldn't change the function signature.

Should I file a pull request, or was this intended?

**Comment by minseongg** [comment]
Thanks, we updated it. (https://github.com/kaist-cp/cs220/commit/0ab03a0367f2254a9ad967bb01be7dc90d869b72)

+) One way to resolve it without changing function signature is that declare it as mutable in the function body.

For example:

```rust
pub fn repeat<T, F: FnMut(T) -> T>(n: usize, f: F) -> impl FnMut(T) -> T {
    let mut f = f;
    ...
}
```

**Comment by m-spitfire** [comment]
Thank you!
