### ISSUE TITLE
[Assignment07] cargo test assignment07 doesn't work appropriately

### ISSUE THREAD

**Issue by Inhyeok-Jeong** [kaist-cp/cs220#148]
Hello,
I'm doing assignment07. I want to test my code by using 'cargo test' as usual, but it looks it doesn't work appropriately.
When I enter 'cargo test assignment07' in my ssh terminal, it doesn't terminate. I think my code has no possibility of infinite loop. Anyway to debug my code, I added few print lines in my next() function body and grading.rs. However, cargo test print nothing in this case. I tried to search this kind of error or problem in web, I couldn't solve this issue(I tried to use timeout() in grading.rs, it doesn't work). What can I do to solve this issue?

![assignment07 test](https://user-images.githubusercontent.com/44631757/198831637-cd7ed90a-4c5d-4f63-8a33-01a15ce5d8f9.PNG)

**Comment by minseongg** [comment]
Could you please try to use `--nocapture` option? (https://doc.rust-lang.org/cargo/commands/cargo-test.html#display-options)

Usage: `cargo test assignment07 -- --nocapture`

**Comment by Inhyeok-Jeong** [comment]
It worked what I wanted for testing! Thank you :)
