### ISSUE TITLE
Connection to SSH Server Timed out

### ISSUE THREAD

**Issue by theonlyrealALEX** [kaist-cp/cs220#15]
I can't connect to your SSH server on VSCode, I am getting the following Error Message:
`Failed to connect to the remote extension host server (Error: The connection timed out)`
I tried: Restarting, Changing Time until Timeout to 30sec (from 15sec)

FYI:
`C:\Users\alexa>ping cp-service.kaist.ac.kr

Pinging cp-service.kaist.ac.kr [143.248.135.193] with 32 bytes of data:
Reply from 143.248.135.193: bytes=32 time<1ms TTL=56
Reply from 143.248.135.193: bytes=32 time<1ms TTL=56
Reply from 143.248.135.193: bytes=32 time<1ms TTL=56
Reply from 143.248.135.193: bytes=32 time<1ms TTL=56

Ping statistics for 143.248.135.193:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms`

**Comment by choejms** [comment]
For some reason, I can't connect to the server either. 
It says "ssh: connect to host cp-service.kaist.ac.kr port 13000: Network is unreachable."

**Comment by Hado-lee** [comment]
I also have the same problem.

**Comment by jpt0927** [comment]
I cannot connect to the server either.
My error message is "ssh: connect to host cp-service.kaist.ac.kr port 13000: Connection timed out".

**Comment by jeehoonkang** [comment]
Hi all,

Sorry for the inconvenience. To resolve the server problem, I just switched the CS220 server to new hardware.
- If you connect to a new SSH connection, it will warn you that it's an unknown host. Please edit your `~/.ssh/known_hosts` to resolve it.
- Your password is reset to `123454321`.

**Comment by theonlyrealALEX** [comment]
> Hi all,
> 
> Sorry for the inconvenience. To resolve the server problem, I just switched the CS220 server to new hardware.
> 
> * If you connect to a new SSH connection, it will warn you that it's an unknown host. Please edit your `~/.ssh/known_hosts` to resolve it.
> * Your password is reset to `123454321`.

Can you please announce maintenance time so that we can plan our schedules accordingly the next time.

**Comment by jeehoonkang** [comment]
Sorry. The maintenance was not scheduled, but the hardware was malfunctioning...
