### ISSUE TITLE
[Homework 7] Question about find trait

### ISSUE THREAD

**Issue by intellkim** [kaist-cp/cs220#152]
I don't know what to do in find trait. Can I just fill the todo in next fn?

**Comment by Inhyeok-Jeong** [comment]
Yes. in my case, it was enough to pass gg to implement next function.

**Comment by intellkim** [comment]
Oh, thank you

**Comment by intellkim** [comment]
Then I find numbers that fit the condition in next function?

**Comment by minseongg** [comment]
I recommend you to follow this:

- `std::iter::Iterator`: https://doc.rust-lang.org/std/iter/trait.Iterator.html
- How to implementing `Iterator`: https://doc.rust-lang.org/std/iter/index.html#implementing-iterator
- `collect` method: https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.collect
