### ISSUE TITLE
[Homework 7] How to test this code?

### ISSUE THREAD

**Issue by intellkim** [kaist-cp/cs220#153]
When I enter `cargo test assignment07 -- --nocapture` in terminal, building code does not terminate so I can't know the result. What is the problem in this situation?

**Comment by Inhyeok-Jeong** [comment]
--nocapture option doesn't guarantee the termination of your code but it allow your code to print in next function. I suggest you to add print lines and test again. ctrl + c will terminate your test and you can check the flow of your code by reading printed values.

**Comment by minseongg** [comment]
One possible reason can be your code generates infinite loop. I recommend you to check that your `next` function returns `None` properly.

**Comment by intellkim** [comment]
When I return None when the query is not same with part of base, I can only search 0 and 1. I want to continue iter until the end of base but it's not because I return None in 1. How can I continue iter?

**Comment by minseongg** [comment]
You should not return `None` in 1.

For example, the return value of `next` function for this [test case](https://github.com/kaist-cp/cs220/blob/main/src/assignments/assignment07_grade.rs#L7-L10) should be `Some(0)`, `Some(4)`, `None`.
