### ISSUE TITLE
[Assignment 8] cargo clippy raises an error even the semantics are different

### ISSUE THREAD

**Issue by ironore15** [kaist-cp/cs220#154]
I am trying to generate an anonymous function like
```rust
    let g = |(i, vi)| {
        repeat(i, |x| f(x))(vi)
    };
    ...
```

`g` should implement `FnMut(T) -> T`, not only `FnOnce(T) -> T` due to the further codes,
`|x| f(x)` is necessary not to move `f` out.

Since cargo clippy catches `|x| f(x)` as an error, I cannot submit my code.

```rust 
    let g = |(i, vi)| {
        repeat(i, f)(vi)
    };
```
This compiles with an error
```
error[E0525]: expected a closure that implements the `FnMut` trait, but this closure only implements `FnOnce`
  --> src/assignments/assignment08.rs:24:13
   |
24 |     let g = move |(i, vi)| {
   |             ^^^^^^^^^^^^^^ this closure implements `FnOnce`, not `FnMut`
25 |         repeat(i, f)(vi)
   |                   - closure is `FnOnce` because it moves the variable `f` out of its environment
26 |     };
```

Is this a bug of cargo clippy? I think that the linter should not raise error with different semantics.

**Comment by m-spitfire** [comment]
Hello. When I run your code through clippy in error message, it says
```
  |
8 |         repeat(i, |x| f(x))(vi)
  |                   ^^^^^^^^ help: replace the closure with the function itself: `&mut f`
  |
```
I think if you try to borrow the `f` instead of moving it, the code should work. Otherwise, you can also annotate the function with `#[allow(clippy::redundant_closure)]` in order to make clippy ignore your implementation.

**Comment by ironore15** [comment]
Thanks. It perfectly solved my problem.
I thought that this should change the function signature of repeat from `repeat<T, F: FnMut(T) -> T>(n: usize, mut f: F)` to `repeat<T, F: FnMut(T) -> T>(n: usize, f: &mut F)`, but from [this doc](https://doc.rust-lang.org/stable/std/ops/trait.FnMut.html#impl-FnMut%3CA%3E-for-%26mut%20F), `&mut F` is also `FnMut(T) -> T`.

**Comment by m-spitfire** [comment]
Maybe you can try to resolve it without changing the signature? See https://github.com/kaist-cp/cs220/issues/145#issuecomment-1284897141. Although as long as it passes the test cases, I assume the signature shouldn't matter.

**Comment by ironore15** [comment]
No. What I said is that `&mut F` is also implement `FnMut(T) -> T`, so I don't need to change the function signature.
