### ISSUE TITLE
Server will go down for the planned power outage (Nov 6, 9:00-18:00)

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs220#155]
There is a planned power outage for the entire KAIST campus (Nov 6, 9:00-18:00). The server will go down as well.

**Comment by jeehoonkang** [comment]
The server is up again, but the server has been reinstalled. So...
- The SSH fingerprint has changed. You should remove a line in `~/.ssh/known_hosts`.
- Your password (if exists) was reset. Please use SSH key.

**Comment by tlsdud020918** [comment]
Professor, could you please notice us what is the default password after reset the server?
I try the password 123454321, but it wasn't work.

**Comment by Inhyeok-Jeong** [comment]
How to remove a line in `~/.ssh/known_hosts`
1. Click Open Folder in VSCODE
![image](https://user-images.githubusercontent.com/44631757/200167554-e2bec094-ffe9-4eff-a55b-5564028a9eea.png)
2. enter your directory that your ssh config files exist ex) `~/.ssh`
(you can find directory by `open SSH configure file` in VSCODE)
3. remove a line which is related to cs220 `[cp-service.kaist.ac.kr]`  in ~/.ssh/known_hosts (There might be few lines depends on your ssh list like cs220, cs230, etc)
4. Try to connect SSH cs220.
5. In my case, click `continue` when VSCODE told me that a existing fingerprint was found led me to SSH that we used for previous assignments
Notice: In my case, I used SSH key file So I didn't have to enter password.
