### ISSUE TITLE
About server password

### ISSUE THREAD

**Issue by tlsdud020918** [kaist-cp/cs220#156]
Professor, could you please notice us what is the default password after reset the server?
I try the password 123454321, but it wasn't work.
Also, I tried SSH key method, but still It seems I need default password to send the public key to server because I didn't set the ssh key connection for the server before.
Can you help me?

**Comment by songminwoo1** [comment]
This also happened to me.

**Comment by jeehoonkang** [comment]
Please send jeehoon.kang@kaist.ac.kr an email, **with your student id**, if you're experiencing this problem.

But please be noted that you were asked to register an SSH key :) maybe the server will go down again and I probably cannot reset your password at that time.

**Comment by jeehoonkang** [comment]
Please send me an email if you still cannot access the server.
