### ISSUE TITLE
Assignment 08 GG server error (uninstalled toolchain)

### ISSUE THREAD

**Issue by songminwoo1** [kaist-cp/cs220#157]
This is the current log.

-------------------------------------------------

[assignment08.rs](https://gg.kaist.ac.kr/submission/15948/download/) (submitted at 2022-11-06 22:34:12)
Return code
1
Log
===== SETUP =====

===== CHECK =====
[2022-11-06 13:34:12,129: WARNING/ForkPoolWorker-32] Demoting to runner...
info: downloading installer
info: profile set to 'default'
info: default host triple is x86_64-unknown-linux-gnu
warning: Updating existing toolchain, profile choice will be ignored
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.65.0 (897e37553 2022-11-02)

Rust is installed now. Great!

To get started you may need to restart your current shell.
This would reload your PATH environment variable to include
Cargo's bin directory ($HOME/.cargo/bin).

To configure your current shell, run:
source "$HOME/.cargo/env"
error: toolchain 'nightly-x86_64-unknown-linux-gnu' is not installed

-------------------------------------------------

my code passes ./grade-08.sh in my local machine, and I think the contents of the file doesn't matters. There seems to be something not installed on the grading server.

What can I do for this?

**Comment by jeehoonkang** [comment]
Would you please try again?

**Comment by songminwoo1** [comment]
I got the same error again.

**Comment by minseongg** [comment]
Could you please try again?

**Comment by jeehoonkang** [comment]
Please reopen this issue if it continues.
