### ISSUE TITLE
[Homework 2] Adding extra test cases

### ISSUE THREAD

**Issue by ironore15** [kaist-cp/cs220#16]
Q. Is it okay to open a pull request for adding extra test cases?

I found that there is a slight lack of test cases for some programming tasks.
I want to share extra test cases to others, so no people suffer by hidden test cases. Is this allowed?

**Comment by zzz845zz** [comment]
Yes, please feel free to make a PR!

**Comment by komfkore** [comment]
@zzz845zz 
1) Will student-generated test cases be official ones that we're using for grading?
2) Are there any hidden test cases?

**Comment by zzz845zz** [comment]
1. Yes. All pull requests will be reviewed and merged if it seems reasonable to use for grading. Please let us know if you think the added test case is inappropriate.
2. We think (1) there are no more hidden cases and (2) it's already good enough for grading. But students' contributions are always welcome.

**Comment by idealyhn** [comment]
Is it okay to make a fork unless we don't implement `todo!()` part?

**Comment by jeehoonkang** [comment]
@idealyhn yes please :)

**Comment by choejms** [comment]
I have already submitted HW1 and HW2 and passed the tests. If there are more tests to be added on gg.kaist.ac.kr, do I have to resubmit my code to see if my code works on a newly added tests?

**Comment by m-spitfire** [comment]
yes @choejms. See https://github.com/kaist-cp/cs220/issues/7#issuecomment-1235166742.
