### ISSUE TITLE
Assignment 8: reached the recursion limit while instantiating ...

### ISSUE THREAD

**Issue by junsooo** [kaist-cp/cs220#160]
Hello, Now I'm doing HW8.
I'm implementing repeat function for HW8, 
for example the part of my code body is like this:
```
    move |v| {
        if n == 0 {
            return v
        } else {
            return repeat(n - 1, |x| f(x))(v)
        }
    }
```
Actually returning this makes ```reached the recursion limit while instantiating `assignment08::repeat::<usize, [c...8.rs:18:34: 18:37]>::{closure#0}``` error.
I really don't understand it cause there is a base case for n == 0. I searched google and tried to understand the reason but couldn't find some useful information.
How can i fix that error? Thank you very much.

**Comment by Re-st** [comment]
Hint : https://github.com/rust-lang/rust/issues/43520
I had same issue, couldn't fix that. 
I tried to put repeat() outside the closures, by defining y = repeat(n - 1 , ...).. but same issue happened.
You should evade this 'recursion limit' somehow.

**Comment by junsooo** [comment]
Thank you very much, @Re-st .
@minseongg , I'm curious that this is intended workaround for HW8. I tried several other options like `&mut f`, but it didn't work. If this is intended, could you give some hint for workaround?(Because i think it is related with rust bug issue)
If i'm wrong, please correct me.

**Comment by minseongg** [comment]
@junsooo It seems like calling the function itself in closure causes the error (due to Rust's type system).

I recommend you to implement the closure without calling `repeat` recursively.

**Comment by junsooo** [comment]
Thank you. Just using iterative method in function solved the problem.
