### ISSUE TITLE
SSH Permission Denied #158

### ISSUE THREAD

**Issue by cs20200689** [kaist-cp/cs220#162]
Professor, I have same problem with SSH Permission Denied.
So I sent an email to the email address that was guided.
But the same problem still arises. Could you check the mail once?

**Comment by koosaga** [comment]
I also have the same issue and I could not receive any clarification from emails.
I wish this issue could be resolved before it's not too late to start the assignment.

**Comment by intellkim** [comment]
I also have same issue. In my case, there is no message that write password. I just denied and can't access the server.

**Comment by koosaga** [comment]
@intellkim You can open the file `~/.ssh/known_hosts` (per Mac) and remove any line that contains `cp-service.kaist.ac.kr`.

**Comment by intellkim** [comment]
@koosaga I did it and I can enter password but still permission denied.

**Comment by leeyh0623** [comment]
I also have same issue. In my case, I can't enter password. What's the solution?

**Comment by minseongg** [comment]
Professor said that he checked all emails.

If the same error occurs, then please send an email to the professor again.
