### ISSUE TITLE
About gg grade

### ISSUE THREAD

**Issue by leeyh0623** [kaist-cp/cs220#163]
I submitted it after confirming that all test cases were passed, but the gg shows no. What should I do?

**Comment by jeehoonkang** [comment]
did you test your code with the provided grade script?

**Comment by leeyh0623** [comment]
Yes, all test case was passed

**Comment by jeehoonkang** [comment]
what does gg say?

**Comment by leeyh0623** [comment]
Just show "No" in success part

**Comment by jeehoonkang** [comment]
what's the error message? you can click your submission entry to see the log.

**Comment by Youhyeon1013** [comment]
Passing the test cases is only the first step. Your code should keep additional rules for you to get the score. You can see the details in the log, on the left of "SUCCESS?", after gg judges your submission.
The script in cs220/scripts/grade-XX.sh works same as gg submission works, so you can check your code without submitting in gg by ./grade-XX.sh in cs220/scripts folder.

**Comment by leeyh0623** [comment]
Using ./grade-XX.sh in cs220/scripts folder, then all test case passed.

**Comment by minseongg** [comment]
Could you please upload your log in gg?

**Comment by leeyh0623** [comment]
![image](https://user-images.githubusercontent.com/85305379/201269576-507acd85-09ca-4d29-89e2-5445bc421a07.png)

**Comment by jeehoonkang** [comment]
Please don't upload the logs in the image. Please ask another question.

**Comment by minseongg** [comment]
As the log said, please format your code with `cargo fmt` first.

**Comment by leeyh0623** [comment]
I can't enter server. So I use online compiler. It make problem?

**Comment by minseongg** [comment]
If you're using Rust Playground, then please run formatter and linter by using "TOOLS" -> "Rustfmt" and "Clippy".

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/37203263/201273591-e1979f07-8a6b-4ec3-9b3f-53e22432f1af.png">

**Comment by leeyh0623** [comment]
Thank you, I will try this
