### ISSUE TITLE
[Homework 9] Iterators (1/2) (due: 2022-11-25 23:59:59)

### ISSUE THREAD

**Issue by zzz845zz** [kaist-cp/cs220#164]
Understanding iterators and expressing programs concisely as a series of ideas.

- Read the description [here](https://github.com/kaist-cp/cs220/blob/main/src/assignments/assignment09.rs). You're going to fill out the `todo!()`s.

- We recommend you use provided methods from `itertools` crate. For more details, please refer to [this documentation](https://docs.rs/itertools/latest/itertools/trait.Itertools.html#).

- You can grade your solution yourself by running `./scripts/grade-09.sh`.

- Submit your code [here](https://gg.kaist.ac.kr/assignment/77/).

- We will accept pull requests until 11/18 for adding extra test cases. Feel free to make a PR if you think we need more test cases.

- If you get a linking error when compiling, try `cargo clean`.

- **IMPORTANT**: If there are extra test cases, we will nullify all previous submissions on 11/18. Please keep this in mind and **submit your solution again after 11/18**.

- **IMPORTANT**: only the last submission counts. Please make sure the last submission succeeds.

- **IMPORTANT**: don't fork this repository. It'll be public!

**Comment by minseongg** [comment]
The accepted rate for the homework 9 is as follows. (Except for the students who dropped the course)

- Total: 133
- Success: 120
- Success rate: 91.60%
