### ISSUE TITLE
[HW9] Order of return value of find_count_n

### ISSUE THREAD

**Issue by leejy12** [kaist-cp/cs220#168]
In HW9, the function `find_count_n` returns a `Vec<usize>`. Should the elements in this vector be in ascending order?
The test cases suggest so, but I would appreciate some clarification in the docs.

**Comment by leejy12** [comment]
I think I got it.

**Comment by minseongg** [comment]
The return vector should be sorted in ascending order.

Thanks! We updated the description. (https://github.com/kaist-cp/cs220/commit/3351e8d330bbff9b5768d4adbc19bd1a48e45e4e)
