### ISSUE TITLE
Homework 9: Can i change the function signature?

### ISSUE THREAD

**Issue by junsooo** [kaist-cp/cs220#171]
For example, fn position_median <T: ord> to <T: ord + Copy ...> something like that.

My thought to solve this problem was some kind of implementing counting sort, but there's no "copy" or "hash" for T, so i don't know how to solve this problem without changing the function signature.

**Comment by minseongg** [comment]
No, you can solve the problem without using counting sort.

I recommend you to find appropriate method from [itertools](https://docs.rs/itertools/latest/itertools/trait.Itertools.html#) crate.

**Comment by junsooo** [comment]
Thank you. Could be solved without copy trait of T.
