### ISSUE TITLE
Execution error.

### ISSUE THREAD

**Issue by vm3fk5dla2** [kaist-cp/cs220#172]
Dear Professor and TAs.

I have errors during the execution of ./scripts/grade-09.sh.

When I execute ./scripts/grade-09.sh, the compiler said, "could not compile `cs220` due to 5 previous errors."

However, these errors are in assignment03.rs. I already submitted my assignment03 without any error long ago, but why compiler said that there are errors?

Thank you.

**Comment by m-spitfire** [comment]
It would be helpful if you could share the errors.

**Comment by minseongg** [comment]
Are you using the code of `assignment03.rs` in `assignment09.rs`?

If not, I think one way to solve it is to replace the code in `assignment03.rs` to the original [skeleton code](https://github.com/kaist-cp/cs220/blob/main/src/assignments/assignment03.rs) and then run it again.

**Comment by vm3fk5dla2** [comment]
I replaced to the original skeleton code, but similar errors are occurred in assignment04 now...
![image](https://user-images.githubusercontent.com/52191701/202891523-698852c4-cc00-41d5-b521-120f2e1c7791.png)

**Comment by vm3fk5dla2** [comment]
I replaced the code in assignment03.rs to the original skeleton code, but similar errors occurred in assignment04. now.
![image](https://user-images.githubusercontent.com/52191701/202891553-bae75c1a-6d3c-408d-ab9c-46c18924f4c0.png)

**Comment by minseongg** [comment]
It seems like the linter causing new errors as the version of rust is updated.

Could you please apply the suggestions of `cargo clippy` and then try again?

**Comment by vm3fk5dla2** [comment]
It doesn't work.. the same errors still occur.

**Comment by zzz845zz** [comment]
Please share your new error messages after applying the suggestions of ‘cargo clippy’.

**Comment by vm3fk5dla2** [comment]
I replaced the code in assignment03.rs to the original skeleton code.

Before run "cargo clippy":
![Before_clippy](https://user-images.githubusercontent.com/52191701/203246205-bc349aad-a909-4648-9349-692610781fec.PNG)

After run "cargo clippy":
![After_clippt](https://user-images.githubusercontent.com/52191701/203246263-fa2f1728-b51f-4f87-a9c3-b3b2e1f1d3c5.PNG)

**Comment by minseongg** [comment]
You should apply the suggestion of the `cargo clippy`.

For example, there are three suggestions in your code and you should change your code like this:

- `command.variable != None` -> `command.variable.is_some()`
- `command.variable == None` -> `command.variable.is_none()`
- `cmd: &mut Command` -> `_cmd: &mut Command`

**Comment by vm3fk5dla2** [comment]
Thank you. I solved this problem!
