### ISSUE TITLE
[Homework 10] Resubmission for HW10

### ISSUE THREAD

**Issue by choejms** [kaist-cp/cs220#174]
Hi,
I just wanted to make sure if resubmission is necessary for HW10.
It looks like a new test case was added in #169, but all my submissions are not nullified yet in gg.

Is it necessary to resubmit the code even if there is no nullification on my submission?

Thank you

**Comment by minseongg** [comment]
We just nullified the previous submissions now, please resubmit the code. Sorry for the inconvenience.

**Comment by choejms** [comment]
Thank you
