### ISSUE TITLE
Question about entry() method / Entry enum 

### ISSUE THREAD

**Issue by quanxi1** [kaist-cp/cs220#176]
https://doc.rust-lang.org/std/collections/hash_map/enum.Entry.html

Rust HashMap has a method entry(), which is implemeted as below : 

```
pub fn entry (&mut self, key: K) -> Entry<'_, K, V>

```

and the Entry is an enum : 
```
pub enum Entry<'a, K: 'a, V: 'a> {
       Occupied(OccupiedEntry<'a, K, V>),
       Vacant(VacantEntry<'a, K, V>),
}

```

What I'm wondering is that how we can call the methods like `or_insert` or` and_modify` while the Entry enum itself doesn't have any information about the HashMap that called `entry` method at the beginning.  

Referring to library code,

```
let mut map: HashMap<&str, u32> = HashMap::new();

map.entry("poneyland")
   .and_modify(|e| { *e += 1 })
   .or_insert(42);
assert_eq!(map["poneyland"], 42);

```
Return value of` map.entry("poneyland") `is just an enumerator that let us know whether the key "poneyland" is occupied or not and what the key & value pair is, but how does the next call of and_modify virtually modify the hashmap?

**Comment by choejms** [comment]
`Occupied` and `Vacant` entry each has a field `OccupiedEntry` and `VacantEntry`
And `OccupiedEntry` is a struct with `base::RustcOccupiedEntry` as a field, where "base" actually refers to `hashbrown::hash_map`
```
pub struct OccupiedEntry<'a, K: 'a, V: 'a> {
    base: base::RustcOccupiedEntry<'a, K, V>,
}
```

And the OccupiedEntry inside hashbrown::hashmap has the following source code.
```
pub struct OccupiedEntry<'a, K: 'a, V: 'a, S: 'a> {
    key: Option<K>,
    elem: Bucket<(K, V)>,
    table: &'a mut HashMap<K, V, S>,
}
```
So in fact, `Entry` contains a mutable reference to the hashmap, key, and the bucket as fields, which allows it to modify the hashmap.
