### ISSUE TITLE
cannot go into server

### ISSUE THREAD

**Issue by doolymember** [kaist-cp/cs220#177]
I don't understand how can I solve this server problem yet...

my server still give the message 
"Could not establish connection to "cp-service.kaist.ac.kr": Remote host key has changed, port forwarding is disabled."

Can you explain what should I have to do?

**Comment by doolymember** [comment]
I erase 
"Host cp-service.kaist.ac.kr
  HostName cp-service.kaist.ac.kr
  Port 13000
  User s20160204"
from ./ssh/config file

and I try again ssh s~~@cp-server.kaist.ac.kr -p13000

but it doesn't work, give same error message

**Comment by minseongg** [comment]
Could you please try again after remove `~/.ssh/known_hosts` file?

**Comment by doolymember** [comment]
I solve it!!!

Thank you so much!
