### ISSUE TITLE
[Homework 9] Can position_median be implemented without cloning?

### ISSUE THREAD

**Issue by znunc** [kaist-cp/cs220#181]
I am working with implementing position_median in assignment 9.

I found out that sorting the iterator consumes original iterator so that I tried to make a clone of the vector and make two version of it; original and sorted.

However, as the function signature does not give T Copy or Clone trait, I cannot make a clone of it.

Should I implement this just with reference?

**Comment by zzz845zz** [comment]
You can create two iterators that one is sorted and the other is not.

```rust
let iter_sorted = inner.iter().sorted();
let iter_not_sorted = inner.iter();
```

**Comment by znunc** [comment]
Isn't there be ownership problem?

inner is moved to two different variables in code above

**Comment by m-spitfire** [comment]
`.iter()` borrows self(takes `&self` as argument), doesn't consume.

**Comment by znunc** [comment]
Thanks! I solved it with the method suggested.

I kept using `into_iter()` instead of `iter()'`

I think my understanding about the meaning of `into` keyword is quite vague.

Could anyone explain this?

**Comment by quanxi1** [comment]
I guess you can refer to this : 
https://doc.rust-lang.org/stable/std/iter/#the-three-forms-of-iteration

.into_iter() makes an iterator over each element while .iter() makes an iterator over the reference to each element. 
Thus creating an iterator using .into_iter() takes the ownership of the original collection while .iter() doesn't.

**Comment by Lee-Janggun** [comment]
In rust, methods prefixed with into generally means changing the type of the input to that of the resulting type. Thus, their API are typically of the form `into_f(self) -> T`, requiring a `self`, not just a `&self`. `into_iter()` also follows this pattern, requiring a `self`.

**Comment by quanxi1** [comment]
Oh, .into() also seems to accord with the rule in that sense. I was wrong.
