### ISSUE TITLE
[Homework 9] Test cases aren't checking for unsorted input

### ISSUE THREAD

**Issue by m-spitfire** [kaist-cp/cs220#182]
I just noticed that the existing test cases are not checking for if you sort the vector first and find median after. The only test case that have an unsorted list is 
```rust
assert_eq!(position_median(vec![3, 1, 3, 3]), Some(0));
```
Which doesn't properly check it. If you don't sort the list and just straight find its median it's 3. But if the test case was like
```rust
assert_eq!(position_median(vec![3, 1, 5, 3]), Some(0));
```
If one didn't sort the vector, their result would be wrong. Now that it's past the 18th, I'm not sure if it's appropriate to change the test case for assignment.

**Comment by m-spitfire** [comment]
Yes function wants the result index to be it of original, unsorted vector. The actual median of `[3,1,3,3]` is `3` and its index is 0 in unsorted version. But if you just also do the algorithm given in the description of the funciton: `[3,1,3,3] [4/2]` which also gives you `3` whose index is 0 in the unsorted version.

But if you wanted to do the same thing with `[3,1,5,3]` which will give you its median as `5` as its index is 2 (4/2), whose index is `2`, but the actual median's index is `0`.

**Comment by zzz845zz** [comment]
Thank you for your report.
 
However, since the deadline for additional cases has already passed, we will reflect on them in the next semester.

**Comment by Youhyeon1013** [comment]
Oh, now I see. The index of median for every test case is just half of the given vector. That's a problem.

**Comment by minseongg** [comment]
https://github.com/kaist-cp/cs220/commit/91b7639f726abbe83845cb0080a444153badd177
