### ISSUE TITLE
Homework 11: Reason for Option<Node<T>> vs Option<Box<Node<T>>>

### ISSUE THREAD

**Issue by junsooo** [kaist-cp/cs220#185]
On linked_list.rs,
I'm trying to understand why SinglyLinkedList's head is Option<Node<T>>, and Node's next is Option<Box<Node<T>>>.

Is this correct?
1. When we make new node for head on SinglyLinkedList(SLL), SinglyLinkedList has the node value, so it doesn't "dropped" so It doesn't have to be Boxed.
2. For 2nd..3rd..final node for SLL, we don't have the method to access from SLL so this nodes should be Boxed not to be dropped
3. So, on push_front function, first we make Node<T> for new node, and we get previous head node, now its the time to boxing the previous head node. Is this correct? Or we just make Box(Node<T>) from 
the first to making new node?
Boxing the previous head node makes error for `cannot move out of ... behind a mutable reference` so i'm confusing now. Thank you.

**Comment by minseongg** [comment]
> 1. When we make new node for head on SinglyLinkedList(SLL), SinglyLinkedList has the node value, so it doesn't "dropped" so It doesn't have to be Boxed.

Yes.

> 2. For 2nd..3rd..final node for SLL, we don't have the method to access from SLL so this nodes should be Boxed not to be dropped

The `next` field of `Node` has the `Option<Box<Node<T>>>` type to enable the recursive type. For more details, please refer to this: https://doc.rust-lang.org/book/ch15-01-box.html#enabling-recursive-types-with-boxes

> 3. So, on push_front function, first we make Node<T> for new node, and we get previous head node, now its the time to boxing the previous head node. Is this correct? Or we just make Box(Node<T>) from 
> the first to making new node?
> Boxing the previous head node makes error for `cannot move out of ... behind a mutable reference` so i'm confusing now. Thank you.

The former is correct. To resolve the error, I recommend you to see `Option::take()` method. (https://doc.rust-lang.org/std/option/enum.Option.html#method.take)

**Comment by junsooo** [comment]
Thank you. take() worked like a charm.
