### ISSUE TITLE
[Homework 9] calculate_mean function doesn't work due to #![deny(unused_results)]

### ISSUE THREAD

**Issue by malore350** [kaist-cp/cs220#187]
I wrote my function and since the resulting type is supposed to be String, f64, I convert my number to f64. However, my IDE says following: unused result of type `Option<f64>, and doesn't work. If I just comment out the #unused_results in libs, it works.

My question is, what should I do about it? I did various things but it just doesn't let me leave it as f64 type. If I submit it as it is, will it be accepted in gg?

**Comment by minseongg** [comment]
Please follow this: https://github.com/kaist-cp/cs220/issues/59

**Comment by malore350** [comment]
> Please follow this: #59

Thanks for this!
