### ISSUE TITLE
[Homework 11] How to unwrap Box<Node<T>>

### ISSUE THREAD

**Issue by m-spitfire** [kaist-cp/cs220#188]
Hello. I know this question was asked once (#57), but in that case the box was passing as argument to the function, so rust was doing some things to make it work automatically. Now because the `SinglyLinkedList`'s `head` is not a boxed value, but all the next nodes are boxed values, I'm having diffuculty with the `pop_back` function. I am trying to get a mutable reference to head in  a variable, and later on assign this reference to the next nodes. As you may guess I'm getting error
```
   = note: expected mutable reference `&mut Option<assignment11::linked_list::Node<T>>`
              found mutable reference `&mut Option<Box<assignment11::linked_list::Node<T>>>`
```
I thought maybe using `*` and `.as_ref()` on the inner boxed value after unwrapping `Option` may help, but there are more errors such as `cannot move out of shared reference` and `temporary value dropped while borrowed`.

Here's a MWE on Playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=98595f8183897319da206b34ef7109ed

**Comment by tomtomjhj** [comment]
https://doc.rust-lang.org/std/option/enum.Option.html#method.map

**Comment by m-spitfire** [comment]
Hello, sorry for the late reply, but `map` doesn't really help, because there's still error `cannot move out of.. behind a shared reference.`: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=613f73a681943bc345ea9569eef64b7b

**Comment by tomtomjhj** [comment]
You will first need to take the ownership of the node (not its reference). If you have `&mut Option<T>`, then you can use a certain method of `Option` to take the content's ownership.

**Comment by m-spitfire** [comment]
I can't take he ownership of the node, because everything is behind a mutable reference in the method `pop_back` (`&mut self`)

Only if the `SinglyLinkedList`'s head's node was wrapped around `Box` all the type errors would go away.

From a high-level perspective, it doesn't make sense that it's not wrapped around `Box`. Technically in a linked list, all the nodes are equivalent, but in this implementation the head node differs from all the other nodes.

**Comment by choejms** [comment]
I think #185 can help

**Comment by m-spitfire** [comment]
> You will first need to take the ownership of the node (not its reference). If you have `&mut Option<T>`, then you can use a certain method of `Option` to take the content's ownership.

I am not sure how can I get `&mut Option<T>` to the last node, I am able to get `&mut Box<Node<T>>` to the last node, but I do not think it's possible to get owned value out of that mutable reference. I am only able to get a mutable reference to the last node, because I can't move the `self.head`.  The only way I can get the ownership of the head is by using `take()`, but I don't want to take the head, and in order to reassign to head the value I took, I would need `Copy` on type `T`.

**Comment by minseongg** [comment]
If you are iterating the list with mutable reference (e.g. `&mut Node<T>`), then you can get `&mut Option<Node<T>>` to the last node at the previous node of the last node.

**Comment by m-spitfire** [comment]
Thank you for the help! I appreciate it!
