### ISSUE TITLE
Midterm exam on October 18th (Tue), 1:00pm-3:00pm in the lecture room (E3-1 1501)

### ISSUE THREAD

**Issue by minseongg** [kaist-cp/cs220#19]
Please read carefully for the exam.

- **Date and Place**

  We will conduct the **midterm exam on October 18th (Tue), 13:00-15:00 in the lecture room (E3-1, 1501)**.  (**No extension** will be given.)
Please read carefully for the exam.

- **Range**

  + Everything you've learned so far
  + Slides page 1-39
  + All the discussions we had during the lecture  

- **Presence**
  + You must be **physically present** in the lecture room.
  + You must not take a break for restrooms or other reasons.
  + You may leave 30 minutes after the beginning.

- **Supplies**
  + You should **bring your own laptop** to take the exam.
    If you don't any, please borrow one from the CS admin office by sending an email to Mr. Daejong Kim with me cc'ed.
  + You should have **a valid Google account** because the problem/answer sheet will be given as a Google Form.
  + You should bring your student ID card. If you don't have any, bring a government-issued ID card.
  + You may use pencil and paper, but you must not use calculators, tablets, and text editors.

- **Organization**

  The exam will be **split into two phases**: the T/F phase (30 minutes) and the short/long answer phase (1 hour).
  You'll turn in one Google Form answer sheet for each phase (two in total).

- **Screen Policy**

  On the laptop screen, you can only look at the following websites:

  + https://gg.kaist.ac.kr

    * Go to https://gg.kaist.ac.kr/course/12 and click the exam event.

    * Here, you can see the "event token" (see below).

    * Here, you can also ask questions.
      If your question is not answered for 10 minutes, please let us know.
      Your questions can be written either in English or Korean. Answers will be in English.

  + The problem/answer sheet as a Google Form

    * It will be announced in gg.

    * To answer the Google Form, you need to (1) log in with a Google account, and (2) fill out your KAIST email address, name, student ID, and the event token.

    * The problems will be in English. You may answer either in English or Korean.

    * Frequently save your answer.
      Google Form does not automatically save your answers unless you "submit" them.
      You are allowed to resubmit the answers as many times as you want, so it is strongly recommended for you to submit your answers frequently.
      It is your responsibility to maintain your answers reliably and we will not make any exceptions due to technical problems such as network disconnections, web browser crashes, web browser hanging, etc.

    * Here's a [practice answer sheet](https://docs.google.com/forms/d/1gdHk2z2vMt5bOWEH7kLzALDLhCBvuG5q9ZjxkCm0jQo/viewform). Please make sure you successfully submitted your solution to the practice sheet **before taking the exam.**

  + [Rust Playground](https://play.rust-lang.org/) and [Rust Standard Library Documentation](https://doc.rust-lang.org/std/) (except internal implementation source code)
    
    * You may use Rust playground and std doc **only in the short/long answer phase.**

    * You are not supposed to click Source on the top right corner to check the internal implementation. Please follow https://github.com/kaist-cp/cs220/issues/137#issuecomment-1280782150

- **Remote Participation Policy**

  + If you really cannot be physically present in the lecture room, send an email to jeehoon.kang@kaist.ac.kr to **ask for explicit permission for remote participation**.
    Without such explicit permission, you will be regarded as absent from the exam.

  + You should **join two Zoom rooms with two Zoom accounts**: ["Announcement" room](https://kaist.zoom.us/my/jeehoon.kang) and the "CCTV" room (privately emailed).
    If you have only one account, please sign up once again.

  + Join the Announcement room with a device (probably desktop/laptop) in which you'll solve the exam problems.
    Turn off the camera and microphone.

  + Join the CCTV room with another device (probably a laptop/mobile) that observes you during the exam.
    **For the entirety of the meeting, you need to (1) turn on the camera and microphone; (2) show your hand, paper, keyboard, and monitor; and (3) turn off the speaker.**
    (For privacy concerns: please be noted that you agreed to do this at the beginning of the semester.)
    I've attached the model scene from the experienced TA below.

  + **You should be properly present in both the Announcement and CCTV rooms 10 minutes before the beginning to the end of the exam.**
    If you disappear from the camera after the exam starts, we will assume that you gave up on the exam and your score will be automatically zero.
    Network disconnections and/or power outages will not be excuses. Make sure you find a place where you can get a reliable internet connection and power supply.

  + Your Zoom name should be in the form of "200711632 강지훈". Otherwise, you may be disqualified.

  + At the beginning of the exam, you will be asked to show your student card.
    Please show it in front of the CCTV camera.

  + Frequently read Announcement Zoom room messages. We'll DM you when your CCTV doesn't work properly.

![20220608_111857](https://user-images.githubusercontent.com/1201316/172517337-57e9fada-a37d-4732-9559-05e746785c7d.jpg)

**Comment by minseongg** [comment]
**IMPORTANT**: You can look at rust's standard library doc, but you cannot look at the internal implementation of it.

For example:

- You can see the function signature and its documentation of `append` method of `Vec` (https://doc.rust-lang.org/std/vec/struct.Vec.html#method.append)
- You cannot see the internal implementation of `append` method of `Vec` (https://doc.rust-lang.org/src/alloc/vec/mod.rs.html#1822)

**Comment by jeehoonkang** [comment]
**IMPORTANT**: we'll take the exam from 1:00 pm to 3:00 pm.

**Comment by jeehoonkang** [comment]
We'll try to mark the midterm exam and announce the scores by this week, but it may take another week. The announcement will be made as a comment to this issue.

**Comment by jeehoonkang** [comment]
- total: 100
- average: 76.70
- standard deviation: 10.76
- max: 97
- min: 47
- histogram: https://docs.google.com/spreadsheets/d/e/2PACX-1vRqBvkaTeWtTQkggcuD0_l_qVgZCE40O0RjRTRX2rt552HW6lHeUShzUlTXlAjjrDikyxiQzhdnyxle/pubchart?oid=703978118&format=interactive

**Comment by minseongg** [comment]
- You can check the points for each section here: https://gg.kaist.ac.kr/course/12/
  - T/F
  - Rust struct/enum: Direction, MyOption, MyResult
  - Rust generic/trait: LoggedQueue, Repeat transform
  - Rust etc: Sum array, Median, Syntax (`HasArea` trait)
  - Why3: Prime, AnyInArray
- If you want to make a claim, please send an email to minseong.jang@kaist.ac.kr, seungmin.jeon@kaist.ac.kr by **next Sunday, 2022-10-29, 23:59:59**.
- Please follow the below format so that I can quickly send you the answers.
  - Title: "[CS220 Midterm] Claim for \<your student ID\> \<your name\>"
  - Content: For each claim, label each as the following.
    
    ```
      * \<Category name\>: \<Points you got\>
      * \<Short description about what you want to claim\>
    ```

  - Category name: T/F, Rust enum, ...
- If there are any changes in the general grading scheme, I will provide an update in this issue here, so please check it before you send me an email.

**Comment by minseongg** [comment]
- You can check the points for each section here: https://gg.kaist.ac.kr/course/12/
  - T/F
  - Rust struct/enum
  - Rust generic/trait
  - Rust etc
  - Why3
- If you want to make a claim, please send an email to minseong.jang@kaist.ac.kr, seungmin.jeon@kaist.ac.kr by **next Sunday, 2022-10-29, 23:59:59**.
- Please follow the below format so that I can quickly send you the answers.
  - Title: "[CS220 Midterm] Claim for \<your student ID\> \<your name\>"
  - Content: For each claim, label each as the following.
    ```
      * \<Category name\>: \<Points you got\>
      * \<Short description about what you want to claim\>
    ```
  - Category name: T/F, Rust struct/enum, ...
- If there are any changes in the general grading scheme, I will provide an update in this issue here, so please check it before you send me an email.

**Comment by zzz845zz** [comment]
Notice: We have finished re-checking that the scores are correctly updated in the grading sheet. The updated scores won't be in gg, but it will be applied to the final score.

**Comment by minseongg** [comment]
Notice: There was one TF question in which all the answers were considered correct. For the score updates in Long question, we noticed you individually by e-mail.

Statistics after claim is as follows:

- total: 100
- average: 77.08
- standard deviation: 10.76
- max: 97
- min: 47
- histogram: https://docs.google.com/spreadsheets/d/e/2PACX-1vRqBvkaTeWtTQkggcuD0_l_qVgZCE40O0RjRTRX2rt552HW6lHeUShzUlTXlAjjrDikyxiQzhdnyxle/pubchart?oid=703978118&format=interactive
