### ISSUE TITLE
Question about scope of reference

### ISSUE THREAD

**Issue by YoonseokJeong** [kaist-cp/cs220#190]
```
let mut some_variable: &mut SomeType = &mut SomeType::new();
loop {
            match &mut some_variable {
                A => {
                }
                B => {
                }
            }
}
println!("{:?}", some_variable) // error: cannot borrow `some_variable` as immutable because it is also borrowed as mutable
some_variable = new_value; // error: cannot assign to `some_variable` because it is borrowed
```

Hello, I'm struggling with some borrowing issues.

In my opinion, for borrows occur in the pattern matching, the scope of borrowing ends with each end of the iteration.
So after the loop terminates, there is not any borrowing left.

But why do I get the errors above, each time I try to make immutable borrow or assigning new value to the variable?
Why is mutable borrowing left after the loop terminates?

**Comment by minseongg** [comment]
Could you please give a reproducible example? (i.e. permalink to the Rust playground)

I think one possible reason can be `some_variable` is mutably borrowed in the match expression.

For example, let's see this code ([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=e5767cd732c6f7e017ea52f55c85d26c)):

```rust
fn main() {
    let mut some_variable = &mut SomeType::new();
    let mut new_value = &mut SomeType::new();

    match some_variable {
        SomeType::A => {
            new_value = some_variable; // `some_variable` is mutably borrowed by `new_value` here
        }
        SomeType::B => {}
    }

    println!("{:?}", some_variable); // compile error
    some_variable = new_value; // `new_value` is used here
}
```

In the above code, `some_variable` is mutably borrowed by the `new_value` in the match expression and the `new_value` is used in the last line of the code, so the borrowed range of `some_variable` is not finished after the match expression.

**Comment by tomtomjhj** [comment]
You might be running into the problem described here (http://smallcultfollowing.com/babysteps/blog/2018/06/15/mir-based-borrow-check-nll-status-update/#polonius), which isn't still fixed.
