### ISSUE TITLE
About assignment 10 nullification

### ISSUE THREAD

**Issue by gs18050** [kaist-cp/cs220#193]
IMPORTANT: If there are extra test cases, we will nullify all previous submissions on 11/18. Please keep this in mind and submit your solution again after 11/18.

I thought that it was ok if we submitted assignment 10 after 11/18 so I resubmitted my assignment at 11/19. But today I found out that the submissions were nullified at 11/20. Can I submit my assigment?

**Comment by minseongg** [comment]
Yes. Could you please send email to minseong.jang@kaist.ac.kr with your (1) Student ID, (2) Submission ID and (3) Submitted File?

**Comment by minseongg** [comment]
For anyone who has the same problem, please follow the above comment.
