### ISSUE TITLE
[Homework 11] My code works, I don't know why.

### ISSUE THREAD

**Issue by znunc** [kaist-cp/cs220#195]
I am working on tv_room.rs

My understanding of the code is like below.

1. There's `TVRoom` which takes `Manager` and `Guest`

2. `Manager` and `Guest` has `Rc` pointing to `Watcher` and this `Watcher` is pointing to `RefCell` of the `TVRoom` state.

3. Because of `Rc` , the state of `TVRoom` is shared among each `Manager` and `Guest`

My implementation of `drop` for `Watcher` doesn't test the number of `Rc`. (I tried this and failed as `Watcher` itself has no relation to `Rc`) . As the result, my `drop` should always make the `TVRoomState` to `Closed`.

However, something weird happened and it automatically check the `Rc` count and change the `state` only if `Rc` count is 1.

The question is: Is `Rc` wrapping `RefCell` prevents the contents inside `RefCell` to be modified unless `Rc` count is 1?

**Comment by minseongg** [comment]
When the `Rc` dropped, it will decrement the reference count and drop the inner value only if the reference count reaches zero. ([Reference](https://doc.rust-lang.org/std/rc/struct.Rc.html#impl-Drop-for-Rc%3CT%3E), You can just ignore the difference between strong reference and weak reference in this assignment.)

Therefore, the `Watcher` is dropped only when the reference count reaches zero.

**Comment by znunc** [comment]
Do you mean that `state` will be able to mutated "after all the `Watcher` is dropped"?

**Comment by m-spitfire** [comment]
Yes. `Watcher` only takes a reference to the `RefCell<TVRoomState>`, so when `Watcher` is dropped, only the reference will get dropped afterwards too, the original `RefCell` will still be there.

**Comment by minseongg** [comment]
No, you can change the contents inside `RefCell` even if the reference count is larger than 1.

Example ([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=7a2d9e7a1b2356eef9743f366f64f010)):

```rust
use std::cell::RefCell;
use std::rc::Rc;

fn main() {
    let x = Rc::new(RefCell::new(1));
    let y = x.clone();
    let z = x.clone();
    println!("{}", x.borrow()); // Prints 1

    *y.borrow_mut() = 2;
    println!("{}", x.borrow()); // Prints 2

    *z.borrow_mut() = 3;
    println!("{}", x.borrow()); // Prints 3
}
```

What I mean is that the `drop` function of `Watcher` is called when all the `Rc` pointing to it is dropped, so you can assume that the `Rc` count is zero in the `drop` function of `Watcher`.

Example ([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a28203a20f788cd45856a77d16ca812b)):

```rust
use std::rc::Rc;

struct Foo;

impl Drop for Foo {
    fn drop(&mut self) {
        println!("Dropped");
    }
}

fn main() {
    let x = Rc::new(Foo);
    let y = x.clone();
    let z = x.clone();

    drop(x); // The reference count becomes 2, and `Foo` will not be dropped.
    drop(y); // The reference count becomes 1, and `Foo` will not be dropped.
    drop(z); // The reference count becomes 0, and `Foo` will be dropped.
}
```

**Comment by znunc** [comment]
Your explanation is so clear. Thank you!
