### ISSUE TITLE
[Homework 11] Error: Cannot move out of a shared reference

### ISSUE THREAD

**Issue by syjn99** [kaist-cp/cs220#197]
I'm having trouble with implementing the singly linked list, especially at the function `pop_back`.

What I'm trying to do is following:
1. get the last node (by using custom function that I wrote)
2. replace the last node with `None` by using `take()` method (thanks to #185 )
3. return the 'taken node's value' and wrap with `Some`.

It seems like when I try to move the value inside the &Node<T>, the compiler makes an error.
Error occurs in the third process like:

> error[E0507]: cannot move out of a shared reference, move occurs because value has type `T`, which does not implement the `Copy` trait

Is there any method to 'de-reference' reference, and just take it on my own?

I wrote a simple code that can demonstrate my point below.

[Rust Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b8e39e08b526da20e99595f21f6a76c2)

**Comment by zzz845zz** [comment]
To move out the value of the node, you should get the ownership of the node (i.e. `Node<T>`) from `take()`.

**Comment by minseongg** [comment]
Hint: To get the ownership of the node with `take()`, you should iterate the list with mutable reference to the node. (e.g. `&mut Option<Node<T>>`, `&mut Node<T>`, ...)

**Comment by syjn99** [comment]
Thank you for your comments. Does `take()` means `mem::take()`?  As I tried to use `mem::take(&mut node)`, the another error follows.

> error[E0277]: the trait bound `assignment11::linked_list::Node<T>: Default` is not satisfied

**Comment by minseongg** [comment]
No, `Option::take()`.

**Comment by syjn99** [comment]
My question is: How can I get the ownership of `&mut Node<T>`?

**Comment by zzz845zz** [comment]
You can't get the ownership of `T` from `&mut T`.

I think the one way is changing your helper function to return `&mut Option<T>`, rather than `Option<&mut T>` so that you can take ownership of `T` using `Option::take()`.

```rust
let a: &mut Option<T> = my_helper_func();
let b: T = a.take();
```

**Comment by minseongg** [comment]
I recommend you to refer to this: https://github.com/kaist-cp/cs220/issues/188#issuecomment-1334586136

**Comment by syjn99** [comment]
// prev: &mut Node<T>
        let mut curr: &mut Node<T> = prev.next.as_mut().unwrap().as_mut();

        // Iterating

        Some(prev.next.take().unwrap().value) // Error occurs here

I'm still in trouble... As I need the second to last node(which will be the `prev`), I used two iterating value `prev` and `curr`. There are two problems here.

1. When I update `prev` value to `curr`, there is an error: `cannot borrow `curr.next` as mutable more than once at a time` when I try to update `curr` value.
2. After finishing the loop, returning the value by using `take()` also makes an error, since I already used `prev.next.as_mut()` when I initialize `curr`.

Are there any tips or hints for iterating with two pointers?

**Comment by minseongg** [comment]
Actually, you do not need to iterating with two pointers to get the second to last node.

When you iterate the list with `curr`, you can check the `curr` is the second to last node by checking (1) the next node of `curr` exists, and (2) the next node of the next node of `curr` does not exist.

**Comment by syjn99** [comment]
Wow... I really appreciate it... Thank you so much
