### ISSUE TITLE
About server issue

### ISSUE THREAD

**Issue by tlsdud020918** [kaist-cp/cs220#198]
I tried to connect server today, firstly it takes too long time to open the folders.
Also, It is getting worse now. Even I registered ssh key before, the server seems like it has been totally initialized. It makes me enter the password, and even if I enter the correct password, permission denied appears.
How can I solve this server error? Can you initialize my password again?

**Comment by komfkore** [comment]
Seems like I'm experiencing the same problem, too.

**Comment by jeehoonkang** [comment]
Please consult #199.
