### ISSUE TITLE
Server reset

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs220#199]
There has been an anomaly in the infra. I just re-created the sandbox for this course. You may need to adjust your SSH configuration. Please consult <https://github.com/kaist-cp/cs220/issues/155>.

**Comment by jeehoonkang** [comment]
The new password is here: <https://gg.kaist.ac.kr/event/21/>

The token is your new password.

Please note that you should have registered an SSH key, though...

**Comment by kohs100** [comment]
I can't login with the given token in gg. was password reset again?
