### ISSUE TITLE
[Homework 11] cargo clippy throws an error but suggestion is not working

### ISSUE THREAD

**Issue by Losnij** [kaist-cp/cs220#201]
![clippy error](https://user-images.githubusercontent.com/112604220/204781563-1fb1fa36-abe2-42dd-a238-920e1731c779.JPG)
![clippy error2](https://user-images.githubusercontent.com/112604220/204781575-43894fc2-1f2c-4271-8df6-4ddc3671df87.JPG)

Code works fine with 'cargo test --lib assignment11_grade', but cargo clippy throws an error like first image.
When I change my code to its recommendation, now compile error appears like second image.
Can I get some help with this problem?

**Comment by minseongg** [comment]
Could you please try `head.map(Box::new)` instead of `head.map(|_| Box::new(head.unwrap()))`?

**Comment by Losnij** [comment]
It works! Thank you so much!
