### ISSUE TITLE
Can't still conncet to server 

### ISSUE THREAD

**Issue by quanxi1** [kaist-cp/cs220#202]
Hi, I'm trying to connect to server after reset but it keeps asking me password and saying **Permission denied (publickey,password)**.
I thought I did something to register ssh key to server after the last server reset a few weeks ago but maybe it didn't work. (Honestly I don't know what it exactly means to 'register key to server' until now.) Could somebody please help me?

**Comment by yumincho** [comment]
I have the same issue.. It says `Permission denied (publickey,password)`, but I couldn't figure out what the problem is. I always used my password to connect to server. And last time the server issue occurred, it worked well after professor changed my password. I want to know if it's possible to change it once again.

**Comment by intellkim** [comment]
I also have the same issue.

**Comment by leeyh0623** [comment]
I also have same problem

**Comment by seoyeonB** [comment]
I also have same issue. Same problem has occured last time too.. I hope to know if I can reset my password again.

**Comment by doolymember** [comment]
I also have same problem..
Sorry I don't know how to set up ssh key instead the password yet
So I just use the password until nowㅠㅠ

**Comment by jeehoonkang** [comment]
https://github.com/kaist-cp/cs220/issues/199#issuecomment-1332454890

**Comment by seoyeonB** [comment]
교수님 안녕하세요! 프로그래밍의 이해 수업 듣고 있는 20200292 배서연입니다.
다름이 아니라 ssh 접속에 문제가 생겨서 known host 파일을 초기화하고 다시 접속했더니 비밀번호가 계속 틀렸다고 나와서 문의 드립니다. 비밀번호를 초기화 해주실 수 있나요?

날씨가 갑자기 추워졌는데 감기 조심하세요! 감사합니다~

-----Original Message-----From: Jeehoon Kang ***@***.***&gt;To: kaist-cp/cs220 ***@***.***&gt;Cc: 배서연 ***@***.***&gt;, Comment ***@***.***&gt;Sent: 2022-12-01T01:49:28+09:00Subject: Re: [kaist-cp/cs220] Can't still conncet to server (Issue #202)

#199 (comment) https://github.com/kaist-cp/cs220/issues/199#issuecomment-1332454890
