### ISSUE TITLE
Same issue with #200

### ISSUE THREAD

**Issue by blziiiin** [kaist-cp/cs220#203]
I have same issue with #200 can you help me?

**Comment by minseongg** [comment]
https://github.com/kaist-cp/cs220/issues/199#issuecomment-1332454890

**Comment by minseongg** [comment]
Could you please try again?

**Comment by blziiiin** [comment]
now it works. thanks!

**Comment by blziiiin** [comment]
but i am getting those error messages...

`failures:

---- assignments::assignment11_grade::test::test_tv_room stdout ----
thread 'assignments::assignment11_grade::test::test_tv_room' panicked at 'not yet implemented', src/assignments/assignment11/tv_room.rs:59:9

---- assignments::assignment11_grade::test::test_linked_list stdout ----
thread 'assignments::assignment11_grade::test::test_linked_list' panicked at 'not yet implemented', src/assignments/assignment11/linked_list.rs:50:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- assignments::assignment11_grade::test::test_mock_storage stdout ----
thread 'assignments::assignment11_grade::test::test_mock_storage' panicked at 'not yet implemented', src/assignments/assignment11/mock_storage.rs:76:9
`

**Comment by minseongg** [comment]
I think one possible reason can be compression issue.

Could you please run `./scripts/prepare-submissions.sh` and then submit `./target/assignment11.zip`?

**Comment by blziiiin** [comment]
Problem solved. Thank you!!
