### ISSUE TITLE
[Homework 11] referencing temporary value error

### ISSUE THREAD

**Issue by cs0502** [kaist-cp/cs220#204]
Hi, I'm trying to return `Manager` with wrapping `Some` in `open` function, so I did

`TVRoomState::Closed => Some(Manager::new(&RefCell::new(TVRoomState::Opened)))`

and I got a following error:

error[E0515]: cannot return value referencing temporary value
  --> src/assignments/assignment11/tv_room.rs:58:17
   |
   |                 Some(Manager::new(&RefCell::new(TVRoomState::Opened)))
   |                 ^^^^^^^^^^^^^^^^^^^---------------------------------^^
   |                 |                  |
   |                 |                  temporary value created here
   |                 returns a value referencing data owned by the current function

How can I fix this problem?

**Comment by minseongg** [comment]
Hint: `RefCell` in the `TVRoom` should be shared among `Manager` and `Guest`.
