### ISSUE TITLE
Server stopped again

### ISSUE THREAD

**Issue by tlsdud020918** [kaist-cp/cs220#207]
The server is too slow right now. 
The server initialization message appears repeatedly when I click open folder. Can you fix the server problem?

**Comment by intellkim** [comment]
I also cannot access the server.

**Comment by minseongg** [comment]
Do you still have the same issue?

**Comment by tlsdud020918** [comment]
No, I think now it's okay.

**Comment by intellkim** [comment]
I think server go wrong again. I can't save the file and load long time.
