### ISSUE TITLE
[HomeWork 11] Not yet implemented error

### ISSUE THREAD

**Issue by sangdevil** [kaist-cp/cs220#208]
I did my homework by installing cargo on my computer without using a Kaist-cp server. The operating system is Windows 10.
Therefore, I can only check my assignment with the assignment 11_grade, and I couldn't use the sh files (it doesn't seem that the Linux command doesn't work in window), so I directly compressed the assignment 11 folder into a zip file and submitted it to the gg.
However, the error "not yet implemented" occurs as shown in this picture.
There was no problem when testing in the assignment11_grade file.
![화면 캡처 2022-12-02 153107](https://user-images.githubusercontent.com/101849478/205230715-a1558f24-4289-4a33-a207-07e0e7f80d67.png)

There seems to be no problem when I went to the line of the file pointed out in the log.
Of course, there is no todo!().

Also, when I tried to access the Kaist-cp server, both the password 123454321 and the token posted on the gg had different password, so I couldn't access it.
I'd appreciate your help.

**Comment by Lee-Janggun** [comment]
If you are manually zipping, you want to zip the three **files**, not the **folder**. Zipping creates a file where unzipping it will result in a folder containing the zipped element, so if you zip the folder, the unzipped folder will result in another folder.

**Comment by sangdevil** [comment]
Thank you, I zip 4 files entirely, not the folder, and success.
