### ISSUE TITLE
[HW11] Lifetimes in while loop with `while let`

### ISSUE THREAD

**Issue by m-spitfire** [kaist-cp/cs220#211]
Hello. I am trying to use `while let` loop like so:
```rust
struct Node<T> {
    next: Option<Box<Node<T>>>,
    val: T,
}

fn main() {
    let mut t = &mut Box::new(Node { next: Some(Box::new( Node { next: None, val: 0})), val: 1});
    while let Some(ref mut node) = t.next {
        t = node;
        if false {
            break;
        }
    }
    t.next.take();
}
```
[Link to playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=250b6bd282f4b8778ac44677e9bf56a6)

This works just fine. But I need to have the if condition before assigning the `t` to node. But it gives me error cannot borrow `t.next` as mutable more than once. I am not sure how this makes sense, since
1. previous code worked just fine, just by changing the order of if it makes compiler mad
2. the reference `node` is getting dropped at the end of while loop, so why am I borrowing it twice?
```rust
struct Node<T> {
    next: Option<Box<Node<T>>>,
    val: T,
}

fn main() {
    let mut t = &mut Box::new(Node { next: Some(Box::new( Node { next: None, val: 0})), val: 1});
    while let Some(ref mut node) = t.next {
        if false {
            break;
        }
        t = node;
    }
    t.next.take();
}
```
[Link to playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a8f4e5cbf1953ead6f1f6b0028eac0a8)

**Comment by minseongg** [comment]
Sorry, I'm not sure about the exact reason of that error..

However, the error could be solved by not putting a conditional break in the borrowed range of `t.next`.

```rust
struct Node<T> {
    next: Option<Box<Node<T>>>,
    val: T,
}

fn main() {
    let mut t = &mut Box::new(Node {
        next: Some(Box::new(Node { next: None, val: 0 })),
        val: 1,
    });
    while t.next.is_some() { // borrow occurs and used here
        if false {
            break;
        }
        let node = t.next.as_mut().unwrap(); // borrow occurs here
        t = node; // borrow used here
    }
    t.next.take();
}
```

[Link to playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=7076c36c4866fe7e172f2a3040a73534)

**Comment by m-spitfire** [comment]
After some search, I found the reason of the error, it's apparently a bug in the borrow checker: https://github.com/kaist-cp/cs220/issues/190#issuecomment-1328166152
Running tests with 
```
RUSTFLAGS="-Zpolonius" cargo +nightly test --lib assignment11
```
resolves the issue, but can't do it with the gg server, so I'll look at your suggestion.

**Comment by m-spitfire** [comment]
Thank you, worked perfectly!
