### ISSUE TITLE
panicked at 'not yet implemented', similar to previous issues

### ISSUE THREAD

**Issue by Eugen0011** [kaist-cp/cs220#212]
Hello, I ran the code on my machine, it works. However, I got this error from gg:

"
_running 3 tests
test assignments::assignment11_grade::test::test_linked_list ... FAILED
test assignments::assignment11_grade::test::test_tv_room ... FAILED
test assignments::assignment11_grade::test::test_mock_storage ... FAILED

failures:

---- assignments::assignment11_grade::test::test_linked_list stdout ----
thread 'assignments::assignment11_grade::test::test_linked_list' panicked at 'not yet implemented', src/assignments/assignment11/linked_list.rs:50:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- assignments::assignment11_grade::test::test_tv_room stdout ----
thread 'assignments::assignment11_grade::test::test_tv_room' panicked at 'not yet implemented', src/assignments/assignment11/tv_room.rs:59:9

---- assignments::assignment11_grade::test::test_mock_storage stdout ----
thread 'assignments::assignment11_grade::test::test_mock_storage' panicked at 'not yet implemented', src/assignments/assignment11/mock_storage.rs:76:9

failures:
    assignments::assignment11_grade::test::test_linked_list
    assignments::assignment11_grade::test::test_mock_storage
    assignments::assignment11_grade::test::test_tv_room

test result: FAILED. 0 passed; 3 failed; 0 ignored; 0 measured; 44 filtered out; finished in 0.00s

Test failed:    cargo test  --lib assignment11_grade
"_

I tried updating xcode and other stuff on my mac. Now when I run ./grade-11.sh I fail at cargo asan: 
"

_Running with cargo_asan...
Build failed! Error message:
   Compiling cs220 v0.1.0 (/Users/eugen/Documents/cs220/local_cs220)
error: linking with `cc` failed: exit status: 1
  |_
"

**Comment by minseongg** [comment]
Could you please refer to these?

- https://github.com/kaist-cp/cs220/issues/203#issuecomment-1333399271
- https://github.com/kaist-cp/cs220/issues/208#issuecomment-1334826405

**Comment by Eugen0011** [comment]
Hello, first link didn't work for me. However, I zipped the files together as per second link and it worked. Thank you!
