### ISSUE TITLE
[Homework 11] looping while reaching the end of the linked list

### ISSUE THREAD

**Issue by intellkim** [kaist-cp/cs220#213]
I get first node and get second node, and third node. I want to looping getting second node and getting third node. But when I make the second node is third node, `value assigned to 'blah' is never read` error occurs. How can I loop this work?

**Comment by zzz845zz** [comment]
Could you please try again after putting the `_` in the prefix of your variable?

e.g. `let blah = ...;` -> `let _blah = ...;`
