### ISSUE TITLE
# of people who succeed in the each assignment

### ISSUE THREAD

**Issue by 7dy109** [kaist-cp/cs220#214]
Excuse me, Can I know how many people succeed in each assignment from assignment 7 like assignments 1 to 6?

**Comment by minseongg** [comment]
You can see the success rate for assignment 7 to 11 here:

- Assignment 7: https://github.com/kaist-cp/cs220/issues/143#issuecomment-1336067016
- Assignment 8: https://github.com/kaist-cp/cs220/issues/144#issuecomment-1336067148
- Assignment 9: https://github.com/kaist-cp/cs220/issues/164#issuecomment-1336067262
- Assignment 10: https://github.com/kaist-cp/cs220/issues/166#issuecomment-1336067544
- Assignment 11: https://github.com/kaist-cp/cs220/issues/180#issuecomment-1336067638

**Comment by 7dy109** [comment]
Thank you!!!!! I will close the issue!
