### ISSUE TITLE
[Homework 12] Concurrency (due: 2022-12-16 23:59:58)

### ISSUE THREAD

**Issue by zzz845zz** [kaist-cp/cs220#216]
Understanding what's involved with the multi-threaded program.

- Read the description [here](https://github.com/kaist-cp/cs220/blob/main/src/assignments/assignment12.rs). You're going to fill out the `todo!()`s.

- You can grade your solution yourself by running `./scripts/grade-12.sh`.

- Submit your code [here](https://gg.kaist.ac.kr/assignment/79/).

- If you get a linking error when compiling, try `cargo clean`.

- We will accept pull requests until 12/09 for adding extra test cases. Feel free to make a PR if you think we need more test cases.

- **IMPORTANT**: If there are extra test cases, we will nullify all previous submissions on 12/09. Please keep this in mind and **submit your solution again after 12/09**.

- **IMPORTANT**: only the last submission counts. Please make sure the last submission succeeds.

- **IMPORTANT**: don't fork this repository. It'll be public!

**Comment by zzz845zz** [comment]
**NOTICE**: Submit your solution again after 12/09. 

We will nullify all previous submissions on 12/09 as the new test case was added in https://github.com/kaist-cp/cs220/commit/69330fbd0f6699d5815db56015601f7ab4b90d88.

**Comment by minseongg** [comment]
**IMPORTANT**: We added more test cases (https://github.com/kaist-cp/cs220/commit/69330fbd0f6699d5815db56015601f7ab4b90d88) and nullified all previous submissions. Please check it and submit again.

**Comment by minseongg** [comment]
The accepted rate for the homework 12 is as follows. (Except for the students who dropped the course)

- Total: 131
- Success: 117
- Success rate: 89.31%
