### ISSUE TITLE
[Homework 13] Parallelism (due: 2022-12-16 23:59:59)

### ISSUE THREAD

**Issue by zzz845zz** [kaist-cp/cs220#217]
Understanding the data parallelism.

- Read the description [here](https://github.com/kaist-cp/cs220/blob/main/src/assignments/assignment13.rs). You're going to fill out the `todo!()`s.

- You can grade your solution yourself by running `./scripts/grade-13.sh`.

- Submit your code [here](https://gg.kaist.ac.kr/assignment/83/).

- If you get a linking error when compiling, try `cargo clean`.

- We will accept pull requests until 12/09 for adding extra test cases. Feel free to make a PR if you think we need more test cases.

- **IMPORTANT**: If there are extra test cases, we will nullify all previous submissions on 12/09. Please keep this in mind and **submit your solution again after 12/09**.

- **IMPORTANT**: only the last submission counts. Please make sure the last submission succeeds.

- **IMPORTANT**: don't fork this repository. It'll be public!

**Comment by minseongg** [comment]
The accepted rate for the homework 13 is as follows. (Except for the students who dropped the course)

- Total: 131
- Success: 119
- Success rate: 90.84%
