### ISSUE TITLE
<'a> vs &'a or 'a

### ISSUE THREAD

**Issue by 7dy109** [kaist-cp/cs220#223]
Hello, all. First of all, I really appreciate the contribution of TAs to this course. Thank you for making this course wonderful!
Here is my question.

```rust
struct correct_struct<'a> {
    active: bool,
    username: &'a str, 
    email: &'a str, 
    sign_in_count: u64,
}
```
in this example, the lifetime of the `correct_struct` and the lifetime of `username` and `email` is the same by writing code like `correct_struct<'a>` and `&'a str`.
But I'm confused about the bottom thing.
"if the `'a` means the lifetime of the something that will come next(in this example, str), should we write code life bottom code?"

```rust
'a struct correct_struct {
    active: bool,
    username: &'a str, 
    email: &'a str, 
    sign_in_count: u64,
} //it is the pseudocode just I made for this question.
```

But, we don't write such code in rust.
Then, what is the actual meaning of the `<'a>` and `&'a` and `'a`?
I don't know if the question was well written as I intended.
Thank you in advance for your reply :)

**Comment by Lee-Janggun** [comment]
I'll first try and minimize the struct example and explain what it mean as is. 

In Rust, some struct definitions have lifetimes in angle brackets as follows.
```rust
struct Test<'a> {
    done : &'a bool,
    started : &'a mut bool,
}
```
Here, the `'a` is a generic parameter: it means that fields of this struct can use the lifetime in its type definitions. In the above example, struct test can be read as "for any given lifetime 'a, `Test` contains a reference to a `bool` named `done` and a mutable reference to a `bool` named `started`".

> "if the 'a means the lifetime of the something that will come next(in this example, str), should we write code life bottom code?"

I assume this is asking "should lifetime bounds in structs be explicitly written in actual usage of structs?"

The answer is no, and this is thanks to the Rust type checker inferring lifetimes for us, hence we do not need write down the lifetime explicitly most of the time.

The next question is then why do we need lifetime parameters in the first place, if it will be inferred? The answer is that we may want some fine-grained control over lifetime relations. Consider the following example with **two** lifetime parameters.

```rust
struct LeftRight<'a,'b>{
    left : &'a bool,
    right: &'b bool,
}
```
Here, we store references of two different lifetimes. The advantage of having different parameters is that we can choose to end the lifetime of **one** of `left` or `right`, allowing access back to the original variable, [while still using the other reference](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0356c70bf9ab53081c6a9c4b37cbde15).

One other crucial usage of lifetime parameters that will not be dealt in this course in when using raw pointers. Raw pointers in Rust are pointers without lifetime nor meaningful mutability information like C pointers. These are heavily used in the Rust standard library and concurrency libraries for efficiency and to go pass certain ownership checks that are too strict. When using them, we sometimes want to "act" as if raw pointers have some lifetime, and in those cases we use lifetime parameters to represent that.

**Comment by 7dy109** [comment]
I guess you mean 
1. Thanks to rust compiler designer
2. 'a is generic lifetime(which we can use in type definitions).
Then <'a> means "we will use 'a as generic lifetime in this type definition?
Thank you for your very kindful answer!

**Comment by Lee-Janggun** [comment]
Yes, that's what I mean.

**Comment by 7dy109** [comment]
Okay I resolved it! Thank you very much!!
