### ISSUE TITLE
Data race in chapter 4

### ISSUE THREAD

**Issue by blziiiin** [kaist-cp/cs220#224]
In Chapter 4.2 it says that 

> a data race happens when these behavior occur:
> Two or more pointers access the same data at the same time
> ...
> ...

but code below works with no error
```
fn main(){
    let x = 1;
    let y = &x;
    let z = &x;
    println!("{} {}", y, z);
}
```

Why `println!()` works even though both y and z are accessing to same data x?

**Comment by 7dy109** [comment]
Because y and z is just immutable reference to x. Rust allows multiple immutable reference.

**Comment by Lee-Janggun** [comment]
The condition in the book is not or, but and. Hence, you need to have multiple access where at least one is a write and that does not have proper synchronization.

In particular, you can never have data races when there are only reads.
