### ISSUE TITLE
Could you nullify submission for HW12?

### ISSUE THREAD

**Issue by choejms** [kaist-cp/cs220#227]
As far as I know, nullification of all previous submissions is expected for HW12.

Could you nullify the submissions?

**Comment by minseongg** [comment]
Yes, we nullified the previous submissions. Please submit again!

**Comment by yumincho** [comment]
Did you nullify HW13 too? I found HW12 was nullified but HW13 wasn't.

**Comment by m-spitfire** [comment]
there weren't any new test cases for hw13.

**Comment by yumincho** [comment]
I see. Thanks!
