### ISSUE TITLE
Can we use par_iter_sync in HW13?

### ISSUE THREAD

**Issue by Hado-lee** [kaist-cp/cs220#228]
I have some synchronization problem. But It seems there are no way to consider synchronization for IndexedParallelIterator.
I think using .collect_into_vec() is not a purpose of this HW...

**Comment by zzz845zz** [comment]
Can you explain more in detail? What kinds of synchronization problems do you have?

**Comment by Hado-lee** [comment]
For example, if I iterate through Multizipped lists parallel and send it's data through channel, or using Mutex, I can't guarantee that it's order is not conserved.
Basically, rayon crate's parallel iterator didn't conserve it's internal order. 

Let 
list1 = [1, 2, 3];
list2 = [4, 5, 6];
list3 = [7, 8, 9];
(multizip those three)=> Iterator consist with (1, 4, 7), (2, 5, 8) and (3, 6, 9)
Then if I iterate it parallel, possible case is
(1, 4, 7)
(2, 5, 8)
(3, 6, 9)  -> What I wanted
but other case also possible
(3, 6, 9)
(1, 4, 7)
(2, 5, 8)  -> I want to prevent this kind of cases.

**Comment by zzz845zz** [comment]
Oh, you don't need to send the data. It's okay to flatten the Multizipped lists and collect them into Vector.

**Comment by Hado-lee** [comment]
I got it.
Thank you!
