### ISSUE TITLE
[Homework12]: meaning of test_scoped_thread_concurrent() test

### ISSUE THREAD

**Issue by junsooo** [kaist-cp/cs220#229]
Hello, i'm doing hw12.

I'm having trouble with test_scoped_thread_concurrent() test.
What i'm thinking is that,
we have f1 and f2, which loops through 0 to 100 with i variable.
To not make timeout, we have to execute f1's first loop(i == 0) and stop it, and execute f2's first loop(i == 1) and stop, and f1's second loop(i == 1) ...... until loop finishes.
Is this meaning that do i have to check the "i" variable on use_scoped_thread to manually stop and start the f1 and f2 function?

So i think i'm not understanding the "Executes the given functions (f1, f2) in concurrent" 's meaning. How can i concurrently execute f1 and f2 with fairness(or exactly same time for executing time slice?)

**Comment by blziiiin** [comment]
I think running f1 and f2 concurrently means running f1 and f2 in multiple thread. That will compute loops in function concurrently and will reduce time

**Comment by junsooo** [comment]
Thank you, problem solved.
