### ISSUE TITLE
Why should we put impl when return value is closure?

### ISSUE THREAD

**Issue by 7dy109** [kaist-cp/cs220#230]
Why should we put impl when return value is closure?
`Code A-1`
```rust
    fn return_some_closure(any_value : i32) -> impl Fn(i32) -> i32 {
        move |mut x| {x + any_value}
    }
```
if we remove `impl`, 
`Code A-2`
```rust
    fn return_some_closure(any_value : i32) -> Fn(i32) -> i32 {
        move |mut x| {x + any_value}
    }
```
compiler says 
```
trait objects must include the `dyn` keyword
```
and I put dyn in this code,
`Code B`
```rust
    fn return_some_closure(any_value : i32) -> dyn Fn(i32) -> i32 {
        move |x| {x + any_value}
    }
```
compiler says
```
return type cannot have an unboxed trait object
for information on `impl Trait`, see <https://doc.rust-lang.org/book/ch10-02-traits.html#returning-types-that-implement-traits>
```
after reading some docs, I guess `dyn` is similar to `impl`. 
1. Why do such errors happen?
2. and why does rust reject code without `impl` or `dyn` like `Code A-2`?
3. And also why do we have to write `"Fn"(i32) -> i32` instead of writing `|i32| -> i32` like `Code C`? is it because we should specify return(or input) closure is `Fn` or `FnMut` or `FnOnce`?
`Code C`
```rust
    fn return_some_closure(any_value : i32) -> (|f32| -> i32) {
        todo!();
    } 
    fn input_some_closure(any_closure : |f32| -> i32) -> i32 {
        todo!();
    }
```

**Comment by 7dy109** [comment]
Oh thank you very much for your clear explanation!

**Comment by zzz845zz** [comment]
FYI: These links may help you to understand the difference between `impl Fn` and `Box<dyn Fn>`.
- https://doc.rust-lang.org/rust-by-example/trait/dyn.html
- https://doc.rust-lang.org/rust-by-example/trait/impl_trait.html
- https://blog.rust-lang.org/2018/05/10/Rust-1.26.html#impl-trait
- https://stackoverflow.com/questions/73807583/should-one-pass-rust-closure-as-boxdyn-fn-or-as-implfn
