### ISSUE TITLE
About the details of the final exam

### ISSUE THREAD

**Issue by taehokimmm** [kaist-cp/cs220#231]
Dear Professor and TAs,

It seems that the given time of each phase of the final exam is yet undecided. (TBA in #218)
How would the exam conducted in the final exam? Is the given time for each phase same with the midterm?

Also, I have briefly heard about the use of SSH servers in the short/long answer phase at the final lecture. Could you clarify the policy about it in the final exam?

Thank you.

**Comment by jeehoonkang** [comment]
- phases: I'll tell you that just before the exam starts.
- IDEs: you may use Rust Playground, vscode, or any editors of your preference. You may connect to SSH servers. But you should not open existing files.
