### ISSUE TITLE
"Compiler bug" as I try to 'Run Test' or to 'Debug'. Is it only happening to me or is it server issue?

### ISSUE THREAD

**Issue by Re-st** [kaist-cp/cs220#232]
After I pushed 'debug' button on some grade function, this is keep popping every time I try to Run Test or to Debug..

---------------------
note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.65.0 (897e37553 2022-11-02) running on x86_64-unknown-linux-gnu
---------------------

Googling out doesn't help me much on what to do..
Does anybody suffer similar situation, or have a clue?

**Comment by m-spitfire** [comment]
can you give a minimal example of the problematic code?

**Comment by Re-st** [comment]
I am working on my visual studio code, and any try to run assignment09_grade 's Run Test button or any other grade file buttons fail.
Below is the terminal message.
   Compiling cs220 v0.1.0 (/home/s20170233/cs220)
thread 'copy x6iooot93eeinva' panicked at 'no saved object file in work product', /rustc/897e37553bba8b42751c67658967889d11ecd120/compiler/rustc_codegen_ssa/src/back/write.rs:900:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_display
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:72:5
   3: core::panicking::panic_str
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/option.rs:1880:5
   5: rustc_codegen_ssa::back::write::execute_work_item::<rustc_codegen_llvm::LlvmCodegenBackend>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.65.0 (897e37553 2022-11-02) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

**Comment by Re-st** [comment]
Is this a very personal issue? I'll try to use rust playground for studying exam tomorrow.

**Comment by m-spitfire** [comment]
try to do cargo clean, or remove `./target` directory and run it again.

**Comment by Lee-Janggun** [comment]
Does running the script work?

**Comment by minseongg** [comment]
I also recommend you to run `cargo test --lib assignment11` in the terminal in VSCode.

**Comment by Re-st** [comment]
> try to do `cargo clean`, or remove `./target` directory and run it again. It's a bug in the compiler, where it tries to use previous build to do incremental build, but apparently there's no object files to do the build. I'd also suggest you to file a bug report too, but I'm not sure how reproducible your bug is.

Tried this and 2 proposals below, still dont' work. I think I'll focus on studying than trying to fix this.. Thanks for your support. 

*Trying to remove cs220/target faulted with message 
Error : EBUSY : resource busy or unlock, unlink '/home/MY______ID/cs220/target/debug/deps/SOME_FILE_NAME_WITH_NUMBERS



Anyhow, is the test organization not available?
