### ISSUE TITLE
[Homework 12] test_scoped_thread_concurrent timeout

### ISSUE THREAD

**Issue by HangKyu** [kaist-cp/cs220#233]
```
failures:

---- assignments::assignment12_grade::test::test_scoped_thread_concurrent stdout ----
thread 'assignments::assignment12_grade::test::test_scoped_thread_concurrent' panicked at 'timeout: the function call took 5000 ms. Max time 5000 ms', src/assignments/assignment12_grade.rs:47:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

My code works on my local test, but it makes timeout failure when I submit to gg.

Does it mean that my code is wrong? How do I solve this?

**Comment by minseongg** [comment]
Could you check if your repository is up to date? We added test cases (https://github.com/kaist-cp/cs220/commit/69330fbd0f6699d5815db56015601f7ab4b90d88) to check whether two threads are running in concurrent.

**Comment by HangKyu** [comment]
Thank you. I found out where I was wrong.
