### ISSUE TITLE
Assignment2: Integer Overflow in Chooses Assignment2

### ISSUE THREAD

**Issue by theonlyrealALEX** [kaist-cp/cs220#24]
Hi, 
I have the following Problem: I wrote a Algorithm which passes all tests apart from the last one where it for very large numbers it has a different result.
For the multiplication I tried both wrapping and saturating multiplication, both produce the same problem (however with different numbers for very large numbers).
For my code I used the following website as inspiration:
https://www.geeksforgeeks.org/space-and-time-efficient-binomial-coefficient/

Left side output:
`[1, 67, 2211, 47905, 766480, 9657648, 99795696, 869648208, 6522361560, 42757703560, 247994680648, 1285063345176, 5996962277488, 25371763481680, 97862516286480, 345780890878896, 1123787895356412, 3371363686069236, 9364899127970100, 24151581961607100, 57963796707857040, 129728497393775280, 271250494550621040, 530707489338171600, 768614336404564650, 737869762948382064, 709490156681136600, 683212743470724133, 658812288346769700, 636094623231363848, 614891469123651720, 595056260442243600, 576460752303423487, 558992244657865200, 558992244657865200, 576460752303423487, 595056260442243600, 614891469123651720, 636094623231363848, 658812288346769700, 683212743470724133, 709490156681136600, 737869762948382064, 768614336404564650, 530707489338171600, 271250494550621040, 129728497393775280, 57963796707857040, 24151581961607100, 9364899127970100, 3371363686069236, 1123787895356412, 345780890878896, 97862516286480, 25371763481680, 5996962277488, 1285063345176, 247994680648, 42757703560, 6522361560, 869648208, 99795696, 9657648, 766480, 47905, 2211, 67, 1]`,
Right side output:
`[1, 67, 2211, 47905, 766480, 9657648, 99795696, 869648208, 6522361560, 42757703560, 247994680648, 1285063345176, 5996962277488, 25371763481680, 97862516286480, 345780890878896, 1123787895356412, 3371363686069236, 9364899127970100, 24151581961607100, 57963796707857040, 129728497393775280, 271250494550621040, 530707489338171600, 972963730453314600, 1673497616379701112, 2703342303382594104, 4105075349580976232, 5864393356544251760, 7886597962249166160, 9989690752182277136, 11923179284862717872, 13413576695470557606, 14226520737620288370, 14226520737620288370, 13413576695470557606, 11923179284862717872, 9989690752182277136, 7886597962249166160, 5864393356544251760, 4105075349580976232, 2703342303382594104, 1673497616379701112, 972963730453314600, 530707489338171600, 271250494550621040, 129728497393775280, 57963796707857040, 24151581961607100, 9364899127970100, 3371363686069236, 1123787895356412, 345780890878896, 97862516286480, 25371763481680, 5996962277488, 1285063345176, 247994680648, 42757703560, 6522361560, 869648208, 99795696, 9657648, 766480, 47905, 2211, 67, 1]`
https://text-compare.com/

**Comment by jeehoonkang** [comment]
Maybe you can try https://en.wikipedia.org/wiki/Pascal%27s_triangle

**Comment by theonlyrealALEX** [comment]
I looked it up and followed exactly the Multiplicative formula and the Recursive formula in two different attempts.
The latter one runs for ever and never finishes, and the first one produces and integer overflow (even though it is the computationally most optimal formula according to Wikipedia).
I genuinely don't know how to pass the test_chooses with the insanely large numbers.
https://en.wikipedia.org/wiki/Binomial_coefficient#Computing_the_value_of_binomial_coefficients

**Comment by choejms** [comment]
Pascal's formula computes the binomial coefficients from bottom up, so given that your code has an integer overflow, there is probably an error in the code.
