### ISSUE TITLE
gg.kaist.ac.kr blocks the access to the course.

### ISSUE THREAD

**Issue by Dongyeongkim** [kaist-cp/cs220#248]
Hello, I tried to set my password and it was successful to log in to gg.kaist.ac.kr but cannot access to the course.

![Screenshot from 2023-08-30 14-52-23](https://github.com/kaist-cp/cs220/assets/42883224/3daaada7-1a37-4555-be85-3a5b578a3867)
![Screenshot from 2023-08-30 14-52-41](https://github.com/kaist-cp/cs220/assets/42883224/6d770d97-bfaa-409c-957c-ef75780a832b)

**Comment by jaehong21** [comment]
So am I. 
Professor just mentioned that not all students are registered to gg perhaps including me, and he'll do it until today.
+) Are we starting our attendance check in gg.kaist.ac.kr **from today**?

**Comment by Dongyeongkim** [comment]
@jeehoonkang It works now. Thank you for your sincere help!

**Comment by osutaiko** [comment]
@jeehoonkang I still cannot access the course at this time, could you perhaps check again if everyone is correctly enrolled in gg?

**Comment by AnHaechan** [comment]
@jeehoonkang  Can you check this again?

**Comment by AnHaechan** [comment]
> @jeehoonkang I still cannot access the course at this time, could you perhaps check again if everyone is correctly enrolled in gg?

Can you leave your student id and name?

**Comment by jeehoonkang** [comment]
@osutaiko please describe exactly how it works differently than you expected. in which stage the log in doesn't work?

**Comment by osutaiko** [comment]
@AnHaechan @jeehoonkang Thank you for your consideration, it works now. (I had encountered the same problem as the first submitter - )

> Hello, I tried to set my password and it was successful to log in to gg.kaist.ac.kr but cannot access to the course.
> 
> ![Screenshot from 2023-08-30 14-52-23](https://user-images.githubusercontent.com/42883224/264240852-3daaada7-1a37-4555-be85-3a5b578a3867.png)

**Comment by jeehoonkang** [comment]
Closing, but feel free to create a new issue if the problem persists for any of you.
