### ISSUE TITLE
[Assignment 1] submit.sh does not work

### ISSUE THREAD

**Issue by youngmin-yang1** [kaist-cp/cs220#250]
### Googling Result

https://www.google.com/search?q=submit.sh&sca_esv=561251984&sxsrf=AB5stBhZmP2Ao3tCwkHpQvFNXQrstQhxUQ%3A1693384529911&source=hp&ei=Uf_uZM2vNJrN2roP4qG84Ag&iflsig=AD69kcEAAAAAZO8NYcp7LRANzXfl3Y5Yx1ILHVgGkuX1&ved=0ahUKEwiNnPv6_IOBAxWaplYBHeIQD4wQ4dUDCAk&uact=5&oq=submit.sh&gs_lp=Egdnd3Mtd2l6IglzdWJtaXQuc2gyCBAAGIAEGMsBMgUQABiABDIFEAAYgAQyBRAAGIAEMgUQABiABDIFEAAYgARI6DZQ3AdYqDNwAngAkAEAmAGLAaABqAmqAQQwLjEwuAEDyAEA-AEBqAIDwgIHECMY6gIYJ8ICCBAAGIoFGJECwgILEC4YgAQYxwEY0QPCAgUQLhiABMICDRAAGIAEGMsBGEYY-QHCAgQQABgewgIGEAAYBRgewgIIEAAYigUYhgM&sclient=gws-wiz

### ChatGPT Result

https://chat.openai.com/?model=text-davinci-002-render-sha

### Your question here

```markdown
I tried to run submit.sh but zip file was not made.
```

**Comment by Dongyeongkim** [comment]
I think this is because of the lack of 'zip' library in your operating system. if you are using debian based linux, you can download via
```$ sudo apt-get install zip```

**Comment by youngmin-yang1** [comment]
I check this phenomena in line 21.
I use windows, so I downloaded winzip and run submit.sh but still not made.

**Comment by Dongyeongkim** [comment]
you can use [WSL](https://learn.microsoft.com/en-us/windows/wsl/install)

**Comment by youngmin-yang1** [comment]
The problem has been solved. Thank you.

**Comment by youngmin-yang1** [comment]
I do not know the problem is zip command, so I open many sites of result of searching "submit.sh". I spend more than 1 hour and write this issue, but was not enough. I am sorry to ask you insufficient questions.

**Comment by 08kmc09** [comment]
In my case in M1 Pro Mac, the for loop variable i expected to be 01, 02, ... and so on, but the value was 1, 2, ... so I revised the script with Chat GPT.

`
#!/usr/bin/env bash

set -e

BASEDIR=$(dirname "$0")/..

mkdir -p "$BASEDIR/target"

for i in {1..13} ; do
  formatted_i=$(printf "%02d" "$i")  # Format the number with leading zeros
  if [ "$i" -eq 5 ]; then
    if [ -f "$BASEDIR/target/assignment05.zip" ]; then
      rm "$BASEDIR/target/assignment05.zip"
    fi
    zip -rj "$BASEDIR/target/assignment05.zip" "$BASEDIR/assets/why3/assignment05"
    continue
  fi
  if [ -f "$BASEDIR/target/assignment$formatted_i.zip" ]; then
    rm "$BASEDIR/target/assignment$formatted_i.zip"
  fi
  zip -rj "$BASEDIR/target/assignment$formatted_i.zip" "$BASEDIR/src/assignments/assignment$formatted_i"
done`
