### ISSUE TITLE
Error occurred when pushing to private repository

### ISSUE THREAD

**Issue by 1starJ** [kaist-cp/cs220#251]
In order to do the assignments, I tried following the instructions on the README.md file.
Since I didn't have any knowledge and experience about Git, I had to start from the beginning.
I managed to have done the "cloning the upstream", and I got an error at pushing to my repository.
`$ git push -u origin main`
<img width="428" alt="image" src="https://github.com/kaist-cp/cs220/assets/143486921/f349e31f-1bd6-45c0-a6c8-2debfb615974">

I also tried `git pull origin main`, but it didn't work. What am I missing?

P.S. Sorry for my informal question; I couldn't find out any different way to ask the question.

**Comment by CarettaCaretta11** [comment]
From `README.md:` “If you want to manage your development in a Git server, please create your own private repository.”

Create a new repository (say “cs220”), change its visibility (from Settings) to “Private” and push your local clone there.

**Comment by woojinnn** [comment]
@1starJ 
The issue template is first adapted in this semester, and may require modification. What made you difficult to ask question? Any suggestion for issue template? I will update it.

**Comment by woojinnn** [comment]
Also, I highly recommend you to use [development server](https://cloud.fearless.systems/).

**Comment by 1starJ** [comment]
@CarettaCaretta11 
I created a private repository in Github. And then I tried pushing my local clone by `$ git push -u origin main` and it still doesn't work...

**Comment by jirheee** [comment]
Could you please post the error message? It is hard for us to answer without knowing the situation

**Comment by jirheee** [comment]
Also, please post them as text in a isolated codeblock, not as image.

**Comment by 1starJ** [comment]
```
To github.com:1starJ/cs220.git
 ! [rejected]          main -> main (non-fast-forward)
error: failed to push some refs to 'github.com:1starJ/cs220.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. If you want to integrate the remote changes,
hint: use 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by Dongyeongkim** [comment]
try ``` $ git pull ``` on original repository and then apply it to the private repo.

**Comment by 1starJ** [comment]
I tried `git pull origin main` and got this:
```
$ git pull origin main
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), 585 bytes | 29.00 KiB/s, done.
From github.com:1starJ/cs220
 * branch              main       -> FETCH_HEAD
 + 877b1a92...dd8012bf main       -> origin/main  (forced update)
fatal: refusing to merge unrelated histories
```
And then, I tried `git push -u origin main` and got this:
```
$ git push -u origin main
To github.com:1starJ/cs220.git
 ! [rejected]          main -> main (non-fast-forward)
error: failed to push some refs to 'github.com:1starJ/cs220.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. If you want to integrate the remote changes,
hint: use 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by Dongyeongkim** [comment]
check the README.md, line under the tools part.

To get updates from the upstream, fetch and merge upstream/main

``` $ git fetch upstream ```
``` $ git merge upstream/main ```

**Comment by 1starJ** [comment]
Thank you. I solved the problem. Still, I wonder why it bugged but after removing the README file in the local repository, I could pull and push the repositories successfully.
