### ISSUE TITLE
Mac OS: scripts troubleshooting

### ISSUE THREAD

**Issue by 08kmc09** [kaist-cp/cs220#252]
Hello, I'm the student who participates in CS220 class.

I'm struggling with the scripts in assignments. To reduce duplicated time-consuming, I posted my procedure in submit and grading scripts.

1. grade-utils.sh
In line number 83, I encountered the error 'timeout: command not found'.

I found this website that fixed my issue.
https://stackoverflow.com/questions/3504945/timeout-command-on-mac-os-x

We need to change command timeout to gtimeout.
```
gtimeout ${TIMEOUT:-20s} bash -c "$TEST_CMD 2> /dev/null" 1>&2
```

2. submit.sh
In my case in M1 Pro Mac, the for loop variable i expected to be 01, 02, ... and so on, but the value was 1, 2, ... so I revised the script with Chat GPT.

```
#!/usr/bin/env bash

set -e

BASEDIR=$(dirname "$0")/..

mkdir -p "$BASEDIR/target"

for i in {1..13} ; do
  formatted_i=$(printf "%02d" "$i")  # Format the number with leading zeros
  if [ "$i" -eq 5 ]; then
    if [ -f "$BASEDIR/target/assignment05.zip" ]; then
      rm "$BASEDIR/target/assignment05.zip"
    fi
    zip -rj "$BASEDIR/target/assignment05.zip" "$BASEDIR/assets/why3/assignment05"
    continue
  fi
  if [ -f "$BASEDIR/target/assignment$formatted_i.zip" ]; then
    rm "$BASEDIR/target/assignment$formatted_i.zip"
  fi
  zip -rj "$BASEDIR/target/assignment$formatted_i.zip" "$BASEDIR/src/assignments/assignment$formatted_i"
done
```

I hope this helps. Thank you!

**Comment by jirheee** [comment]
Thank you for the script! But please use the dev server we have provided.

**Comment by jirheee** [comment]
It is very hard for us to troubleshoot all sorts of environmental issues for every student, whereas the dev server we can inspect the problem right away

**Comment by jirheee** [comment]
But again, thank you for your help👍 We appreciate your kindness to help other people to troubleshoot the issue.🥹🥹

**Comment by 08kmc09** [comment]
Oh I see, I'll close the issue. Thank you.
