### ISSUE TITLE
How to solve rust analyzer error

### ISSUE THREAD

**Issue by leeyh0623** [kaist-cp/cs220#253]
![image](https://github.com/kaist-cp/cs220/assets/85305379/b36e2700-9e15-46cf-8ecb-488fadef8982)

I can't solve this problem. :(

**Comment by jeehoonkang** [comment]
Please paste texts, not images for texts. Temporarily closing this, but please reopen the issue after fixing the question.

**Comment by leeyh0623** [comment]
I fix the question!

**Comment by jeehoonkang** [comment]
- You should describe the error scenario more.
- You should paste googling results to solve the problem (in link).
- You should paste ChatGPT conversation to solve the problem (in text).

**Comment by leeyh0623** [comment]
I use googling, I can solve this problem. Thank you professor
