### ISSUE TITLE
Attendance Quiz (2023 Fall)

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs220#255]
- Along with the solution, please make any comments on the class.
- You may answer the solutions multiple times until getting right (without deduction).

**Comment by jeehoonkang** [comment]
20230904: https://gg.kaist.ac.kr/quiz/140/

**Comment by UrAverageDavid** [comment]
if I am unable to attempt the question, does that mean I got the answer right?

**Comment by jeehoonkang** [comment]
@UrAverageDavid probably. can you see "This quiz is already answered."?

**Comment by UrAverageDavid** [comment]
yes. I guess it's done properly then.

**Comment by jeehoonkang** [comment]
20230906: https://gg.kaist.ac.kr/quiz/142/

**Comment by jeehoonkang** [comment]
20231030: https://gg.kaist.ac.kr/quiz/143/
