### ISSUE TITLE
[Assignment 0] Error during cloning github (Very basic question!)

### ISSUE THREAD

**Issue by cyshello** [kaist-cp/cs220#256]
### Googling Result

https://stackoverflow.com/questions/13509293/git-fatal-could-not-read-from-remote-repository

### ChatGPT Result

https://chat.openai.com/share/0faf7e4e-577a-4ea5-9206-215dca0936e6

### Your question here

Hello, I tried to clone a repository in github without forking it in workspace using "Coder" website. Thus, I created an workspace and opened terminal, and wrote as followings: 

```
$ git clone --origin upstream git@github.com:kaist-cp/cs220.git
```

 However, I could find a error, "fatal : could not read from remote repository". How can I fix it? I am new to Git and Coder, so please explain it. Or if my understanding to open the repository is wrong, please point it out. Sorry for such a basic question and thanks in advance!

**Comment by 000wan** [comment]
Maybe you should clone with the HTTPS link:
```bash
git clone --origin upstream https://github.com/kaist-cp/cs220.git
```

**Comment by cyshello** [comment]
It solved my problem! Can you explain briefly how did it work?

**Comment by 000wan** [comment]
`https://github.com/kaist-cp/cs220.git`: we can clone with HTTPS ordinarily;
`git@github.com:kaist-cp/cs220.git`: this is a SSH url, so you need to configure ssh key to your github account
Referring to this article https://www.warp.dev/terminus/git-clone-ssh.

**Comment by cyshello** [comment]
Solved! Thanks very much :)
