### ISSUE TITLE
Delay in verification mail for resetting password

### ISSUE THREAD

**Issue by zoeyindaclouds** [kaist-cp/cs220#258]
I've been trying to reset my password for gg.kaist.ac.kr, at first there were no verification emails. After few hours I started receiving them, but it seems like link to reset the password has expired since mails took more than 30 min to get delivered. 

Is there anything I can do? Thank you

**Comment by jeehoonkang** [comment]
Hmm, strange. would you please try again?

**Comment by AnHaechan** [comment]
Please open the issue again if you have further discussion points.
