### ISSUE TITLE
[Assignment 1] Error while running grade.sh

### ISSUE THREAD

**Issue by cyshello** [kaist-cp/cs220#261]
### Googling Result

https://stackoverflow.com/questions/68593919/errore0601-main-function-not-found-in-crate-for-utilitary-file-for-a-custom

### ChatGPT Result

https://chat.openai.com/?model=text-davinci-002-render-sha

### Your question here

I wrote some code in small_exercises.rs and wrote following code in terminal.
`cs220/scripts/grade.sh 1`

And I could find two errors here.
It seems that the grading file is not valid to compile.
Can I modify the grade.sh file? If I can, how can I change it to work well?

<img width="360" alt="image" src="https://github.com/kaist-cp/cs220/assets/79438705/174df115-4e53-47f8-9e33-da335e3e2d22">

Additionally, I wanted compile the small_exercises_grade.sh, so I wrote:
`rustc small_exercises_grade.sh`

and I could see following error. 
Is this problem of the small_exercises.sh?
If not, how can I fix it?

<img width="527" alt="image" src="https://github.com/kaist-cp/cs220/assets/79438705/25f83ef6-d398-4f09-9d28-2b727fa00b22">

**Comment by AnHaechan** [comment]
Please check out #254. You may ask question again if #254 wasn't helpful

**Comment by woojinnn** [comment]
For the first question, I think you wrote down a wrong command, but I can't see what you wrote to the terminal. As Haechan said, [#254](https://github.com/kaist-cp/cs220/issues/254) would be helpful.
Also, please use the provided [development server](https://cloud.fearless.systems/)!

**Comment by cyshello** [comment]
Thanks for advising! I will be sure to find for similar issues next time! 
Also, I will try the solutions of #254

**Comment by AnHaechan** [comment]
You can reopen this issue for further questions.
