### ISSUE TITLE
[Assignment 11] In `graph.rs`, is it intended that `NodeHandle::add_edge(&self, to: NodeHandle)` is not `&mut self`?

### ISSUE THREAD

**Issue by tncks0121** [kaist-cp/cs220#262]
### Googling Result

https://stackoverflow.com/questions/59018413/when-to-use-self-self-mut-self-in-methods

### ChatGPT Result

https://chat.openai.com/share/877b7fd4-2ab9-4238-90fe-d159cab2e5c6

### Your question here

In `graph.rs`, `NodeHandle::add_edge` have `&self` while `SubGraph::add_node` have `&mut self`.

https://github.com/kaist-cp/cs220/blob/de69d3e07044d24660ebed38764ebcb53da76352/src/assignments/assignment11/graph.rs#L41-L53

https://github.com/kaist-cp/cs220/blob/de69d3e07044d24660ebed38764ebcb53da76352/src/assignments/assignment11/graph.rs#L76-L85

I believe both should be `&mut self`, since both somehow modifies the struct.

I thought maybe there is some contrived way like using `Rc` or `RefCell` or similar tools to bypass this restriction, and used ChatGPT to find that, but to no success. 

It would be grateful to know whether this difference is intended or not.

**Comment by woojinnn** [comment]
Yes, it's quite intended, and you found the point regarding mutability! Keep going💪

**Comment by tncks0121** [comment]
Ok, maybe I was too suspicious due to #259, thanks for clarifying.
