### ISSUE TITLE
[Announcement] Updates on assignment 7, 10, 11, 12

### ISSUE THREAD

**Issue by AnHaechan** [kaist-cp/cs220#264]
* Part of the skeleton code and test cases for **assignment 7, 10, 11, 12** have been updated.
  * Minor fixes on the test code: `assignment07/my_itertools_grade.rs`, `assignment10/labyrinth_grade.rs`, `assignment12/card_grade.rs`
  * Updates on both skeleton and test code: `assignment11/linked_list.rs`, `assignment11/linked_list_grade.rs`

* All the previous submissions on gg.kaist.ac.kr for assignment 7, 10, 11, 12 will be **NULLIFIED** at (September 13th, 15:25 KST).
  * That is, your previous submissions won't be count for grading.
 
* You must fetch **UPDATED VERSION** from this repository(https://github.com/kaist-cp/cs220.git).
  * First, check if this repository has been set as your `upstream`.
  ```bash
  $ git remote -v
  upstream        https://github.com/kaist-cp/cs220.git (fetch)
  upstream        https://github.com/kaist-cp/cs220.git (push) 
  ``` 
  * Then, fetch & merge from this repository.
  ```bash
  $ git fetch upstream
  $ git merge upstream/main
  ```

* Then, you must **RESUBMIT** your solution for assignment 7, 10, 11, 12 on gg.kaist.ac.kr.

* Sorry for inconvenience. As this course is being actively constructed, minor fixes do happen. Thanks for participating to this course!

**Comment by 2prolove** [comment]
Can I just copy and paste the changed code without patching in github ?

**Comment by AnHaechan** [comment]
@2prolove It's ok but not recommended, as there could be further updates on the code.
