### ISSUE TITLE
Cannot see the attendance quiz for week3

### ISSUE THREAD

**Issue by zee-doubleu-ee** [kaist-cp/cs220#265]
I checked at [gg website](https://gg.kaist.ac.kr/course/17/) but I don't see the attendance quiz for both Monday and Wednesday-Week3. Is it just me? Or there is no attendance quiz at all for week 3?

**Comment by sunji-moon** [comment]
me too

**Comment by jeehoonkang** [comment]
sorry, I didn't upload quizzes. week 3 attendance will not be considered in evaluation.
