### ISSUE TITLE
[Assignment 12] 'Test timed out: cargo test  --lib -- assignments::assignment12::card_grade' when submitted

### ISSUE THREAD

**Issue by tncks0121** [kaist-cp/cs220#267]
### Googling Result

Didn't google anything

### ChatGPT Result

https://chat.openai.com/share/50a03a35-3da1-4872-9ef7-00f270ddf7ad

### Your question here

When I submit to Assignment 12, test `card_grade` always times out with the following message

```
running 1 test
Test timed out: cargo test  --lib -- assignments::assignment12::card_grade
```

even with the simplest implementation possible (submission 22180).

```rs
impl Player {
    /// This function should return the index of the card to flip and the color to change to.
    pub fn flip_card_strategy(&mut self) -> (usize, Color) {
        (0, Color::White)
    }
}
```

Maybe it is because the test duration was changed from 1 second to 20 seconds very recently, and the default timeout in the server wasn't changed? https://github.com/kaist-cp/cs220/commit/d1c218bb9df0ec2cbd423960457e3ab7f5a548fc#diff-c562379e8dd5f5a7a0a80df756a01d828f4bbc2f76e868c6836f5e99604ba6e3

**Comment by tncks0121** [comment]
I temporarily changed `DURATION` to 15 and submitted, and the script didn't time out (submission 22183, my score didn't increase so no need to nullify this). Thanks for rooting the cause.

**Comment by woojinnn** [comment]
@tncks0121 Sorry for the late update. I just modified grade script
