### ISSUE TITLE
I have a question about "return" in rust.

### ISSUE THREAD

**Issue by intellkim** [kaist-cp/cs220#27]
In assignment01, I add the two numbers with wrapping up them and save in the other variable. And I return the saved variable. When I submit that code in the https://gg.kaist.ac.kr/course/12/, my code is wrong. However, I just add the two numbers in the last line in the function. I guess that automatically return the caculated result. When I submit the code in the https://gg.kaist.ac.kr/course/12/, I can pass the assignment. What is the difference between two codes? what is the role of the "return" statement?

**Comment by m-spitfire** [comment]
The grader on the gg server uses the script `./scripts/grade-01.sh`. That script checks your code for common mistakes using [`clippy`](https://github.com/rust-lang/rust-clippy). When you save a result of an expression into a variable, and return that variable using `return` keyword, `clippy` denies it. Relevant clippy lints: 
* https://rust-lang.github.io/rust-clippy/master/#needless_return
* https://rust-lang.github.io/rust-clippy/master/#let_and_return

**Comment by intellkim** [comment]
thank you.
