### ISSUE TITLE
[Assignment 5] Prover version misconfiguration

### ISSUE THREAD

**Issue by sean9892** [kaist-cp/cs220#273]
### Googling Result

https://github.com/OCamlPro/alt-ergo/releases

### ChatGPT Result

https://chat.openai.com/share/36910020-c0b1-4267-9a94-2f58ed8db1a0

### Your question here

[submit_log.txt](https://github.com/kaist-cp/cs220/files/12668577/submit_log.txt)

As the log is quite long, full text of it is attached as a file.

I am attaching the contents as a file due to the length of the log.

If you check the contents of lines 39 to 42, we can see that the version of Alter Ergo installed in the grader is 2.4.0, 2.4.1, and 2.4.2. However, from the logs on lines 62 to 69, it can be observed that there is an attempt to use version 2.4.3 of Alter Ergo for grading the submitted code. It seems that the grading process is not proceeding correctly because it is trying to invoke a version of the prover that is not installed. Please make the necessary corrections to address this issue.

**Comment by AnHaechan** [comment]
I've fixed the issue.
Sorry for inconvenience!
