### ISSUE TITLE
[Annoucement] Install the Safe Exam Browser for midterm exam

### ISSUE THREAD

**Issue by AnHaechan** [kaist-cp/cs220#274]
You will use the Safe Exam Browser(SEB) for the midterm exam.
Please follow the instructions below and see if it works for you.
Detailed instructions and a rehearsal will be held on the week before the midterm exam.

* Instructions: https://docs.google.com/presentation/d/1M8N8HTh7St-hfjuegpyOefxEXJdbdvv4Xr4wK7FXEn8/edit?usp=sharing
* The sample configuration file: [cs220_example1.zip](https://github.com/kaist-cp/cs220/files/12706722/cs220_example1.zip)

**Comment by woojinnn** [comment]
Check whether your response is correctly written here!
https://docs.google.com/spreadsheets/d/14jjBdpgfgtCQ-J75CWMsirMHrAGRRt_YU2RQftzRZY4/edit?usp=sharing

**Comment by AnHaechan** [comment]
Mentioned in #285
