### ISSUE TITLE
[Assignment 1] (Can't run grading script)

### ISSUE THREAD

**Issue by Rsln-M** [kaist-cp/cs220#276]
### Related Issue

Didn't find any

### Googling Result

https://users.rust-lang.org/t/rustup-command-not-found/78739

### ChatGPT Result

https://chat.openai.com/share/f63e7378-8b18-43b7-a3f7-5817c2ff70d9

### Your question here

Question is not about assignment 1 but more general. I am using provided development server. When I run `./scripts/grade.sh 1` in the terminal I get the following error:
`./scripts/grade-utils.sh: line 10: rustup: command not found`

I figured I should install rustup and ran this script:
`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`

However, the terminal says `error: cannot install while Rust is installed`, I have an option to continue installation, however, I'm not sure if I should do that. How can I solve this problem?

Note: I am able to test my code with `cargo test --lib assignment01 -- --nocapture`, the problem is only with grading script.

**Comment by jirheee** [comment]
Could you try `rustup --version` command?

**Comment by Rsln-M** [comment]
I get `rustup: command not found`

**Comment by jirheee** [comment]
Oh that is very strange... Can you  try it again after running `source $HOME/.cargo/env`?

**Comment by Rsln-M** [comment]
`bash: /home/ubuntu/.cargo/env: No such file or directory`

Apparently, I don't have any of those in .cargo folder.

**Comment by jirheee** [comment]
Then can you show what is in your `.cargo` directory? Especially in `.cargo/bin`. You can use `ls` command or `tree` command to do this.

**Comment by jirheee** [comment]
Also, this issue might help

- https://github.com/rust-lang/rustup/issues/686

**Comment by Rsln-M** [comment]
I only have `.package-cache` and `registry` directory in `.cargo`. 

Regarding the issue you have sent, I have already seen it. People there say to follow instrcution rustup.rs, which says to run this:

**Comment by Rsln-M** [comment]
Update: I went on with the installation despite the error. It seems to work now. Closing the issue.
