### ISSUE TITLE
[Assignment #3] (Regarding a test case of "organize" function)

### ISSUE THREAD

**Issue by CarettaCaretta11** [kaist-cp/cs220#278]
### Related Issue

None

### Googling Result

None

### ChatGPT Result

None

### Your question here

Why is it that "Sally", despite being added to the "Sales" department earlier than "Amir", appears **after** him on the list of people from the "Sales" department in the [following test case](https://github.com/kaist-cp/cs220/blob/55b86599eeff4f004da4df5a6aeb3c29bb120a91/src/assignments/assignment03/small_exercises_grade.rs#L79C20-L79C20)? The next test case, where people have been added according to the list of commands, shows this is not due to alphabetical ordering of people's names. Is this a typo? If not, please let me know what I'm missing.

    assert_eq!(
            organize(vec![
                "Add Amir to Engineering".to_string(),
                "Add Sally to Sales".to_string(),
                "Remove Jeehoon from Sales".to_string(),
                "Move Amir from Engineering to Sales".to_string(),
            ]),
            [(
                "Sales".to_string(),
                ["Amir".to_string(), "Sally".to_string()].into()    
            )]
            .into()
        );

    assert_eq!(
            organize(vec![
                "Add Jeehoon to Mathematics".to_string(),
                "Add Minseong to Mathematics".to_string(),
                "Add Seungmin to Computer-Science".to_string(),
                "Move Jeehoon from Mathematics to Computer-Science".to_string(),
                "Remove Minseong from Mathematics".to_string(),
                "Add Minseong to Computer-Science".to_string(),
            ]),
            [(
                "Computer-Science".to_string(),
                [
                    "Seungmin".to_string(),
                    "Jeehoon".to_string(),
                    "Minseong".to_string()
                ]
                .into()
            )]
            .into()
        );

**Comment by tncks0121** [comment]
Note that it is comparing HashSet against HashSet (consult what `into` function is doing), so the order doesn't matter
