### ISSUE TITLE
[Assignment #0] Cannot access development server

### ISSUE THREAD

**Issue by YoonJeongKim97** [kaist-cp/cs220#281]
### Related Issue

None

### Googling Result

None

### ChatGPT Result

None

### Your question here

I have problem on accessing development server. (https://dev.fearless.systems/login)
It worked last month.
Maybe i guess that access right is removed because I didn't submit for first assignments.
Could you check the access right?
Sorry for the late question about development settings. Thank you.

**Comment by jeehoonkang** [comment]
cloud.fearless.systems
