### ISSUE TITLE
[Assignment #4] Should I only fill in the "todo!()" part in the code?

### ISSUE THREAD

**Issue by 1starJ** [kaist-cp/cs220#282]
### Related Issue

None

### Googling Result

None

### ChatGPT Result

None

### Your question here

I wonder if I am supposed to only change the "todo!()" part of the code and touch nothing else.

I'm asking this question because I'm working on the `parse_command()` function and I want to make a new function.
I'm managing the "expression" and only way that came up in my mind is by using a recursive function.

**Comment by AnHaechan** [comment]
You can define new functions.

**Comment by 1starJ** [comment]
> You can define new functions.

Okay. But is there any other way that doesn't need new functions?

**Comment by AnHaechan** [comment]
There might be one, but I think that complicates the code a lot, so no point of doing so.
