### ISSUE TITLE
Reading assignment (for midterm exam)

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs220#283]
Hi all,

- While we didn't study "traits" yet, it's going to be covered in the midterm exam.
- Please read the following articles (no videos will be provided, as the articles are quite comprehensive already):
  + <https://doc.rust-lang.org/book/ch10-02-traits.html>
  + <https://docs.google.com/presentation/d/17G3SwkE_tq0H3lTt9N0ysIbHhqDZBfHkoWD5LwwAKSo/edit#slide=id.g152bee4a3f5_1_72>
- The midterm will be formally announced soon. Until then, please assume that this page marks the coverage: <https://docs.google.com/presentation/d/17G3SwkE_tq0H3lTt9N0ysIbHhqDZBfHkoWD5LwwAKSo/edit#slide=id.p>

**Comment by AnHaechan** [comment]
Mentioned in #285
