### ISSUE TITLE
[Assignment #5] Appropriate Form of Inputs +@

### ISSUE THREAD

**Issue by Logal0** [kaist-cp/cs220#284]
### Googling Result

None

### ChatGPT Result

None

### Your question here

I have two questions related to assignment 5.

1. binary_search
According to the answer of this question ([https://github.com/kaist-cp/cs220/issues/83]), 'binary_search' should return the smallest index of the given value.
To confirm this, I tried to make a simple main function like this:
let main () = binary_search [| 2; 3; 5; 7; 11; 13; 17; 19; 23; 29 |] 3
But it didn't work, and gave me the message: "error line 41, characters 32-72: This expression has type int -> int, but is expected to have type array.Array.array int @rho2"
What form should I use as the input of this function?

2. pascal
I tried to figure out what I should put in the invariant, tried to put some possible invariants (which is trivial) and read the given Wikipedia link several times, but I still cannot figure out why the invariant outside is unknown.
Can I get a hint how I should think about the connection between the unknown area and answer?

**Comment by AnHaechan** [comment]
1. The error message tells you that the expression at character 32-72 (which I assume to be `[| 2; 3; 5; 7; 11; 13; 17; 19; 23; 29 |]`) does not have an `array.Array.array int` type. Googling e.g., "why3 array initialization" or referring the documentaton for array (https://why3.lri.fr/stdlib/array.html) will be helpful.

2. Sorry, I cannot give detailed hints... The invariant is about the essence of how pascal triangle computes combinations, at each step. Concerning the structure of [the invariant of outer for-loop](https://github.com/kaist-cp/cs220/blob/main/assets/why3/assignment05/pascal.mlw#L31) will be helpful.

**Comment by AnHaechan** [comment]
Please re-open this issue if you have further questions :0
