### ISSUE TITLE
Midterm exam on October 18th (Wed), 13:00-15:00 in the lecture room

### ISSUE THREAD

**Issue by AnHaechan** [kaist-cp/cs220#285]
### Date and Place

We will conduct the **midterm exam on October 18th (Wed), 13:00-15:00 in the lecture room (E11 floor 3, room 304).**

### Range

* Everything you've learned until the midterm (lecture, slides, assignments, video lectures, etc)
  * Including the reading assignment 
* All the discussions we had during the lecture and GitHub issues

### Reading assignment

* While we didn't study "traits" yet, it's going to be covered in the midterm exam.
* Please read the following articles (no videos will be provided, as the articles are quite comprehensive already):
  * https://doc.rust-lang.org/book/ch10-02-traits.html
  * https://docs.google.com/presentation/d/17G3SwkE_tq0H3lTt9N0ysIbHhqDZBfHkoWD5LwwAKSo/edit#slide=id.g152bee4a3f5_1_72

### Presence

* You must be **physically present** in the lecture room.
* You must not take a break for restrooms or other reasons.
* You may leave 30 minutes after the beginning.

### Supplies

* You should bring **your own laptop** to take the exam.
* If you don't any, please borrow one from the CS admin office by sending an email to [Mr. Gwonhyu Jin](https://cs.kaist.ac.kr/people/view?idx=594&kind=staff&menu=25) with me cc'ed.
* You should have **a valid Google account** because the problem/answer sheet will be given as a Google Form
* You will use the **Safe Exam Browser (SEB)** for the exam. Install and test SEB before the exam. We will have a **rehearsal on Oct 11th (Wed) lecture**.
  * Instructions: https://docs.google.com/presentation/d/1M8N8HTh7St-hfjuegpyOefxEXJdbdvv4Xr4wK7FXEn8/edit?usp=sharing
  * Sample configuration file: [cs220_example1.zip](https://github.com/kaist-cp/cs220/files/12706722/cs220_example1.zip)
* You should bring your **student ID card.** If you don't have any, bring a government-issued ID card.
* You may use pencil and paper, but you must not use calculators, tablets, and text editors.

### Organization
* The exam will be split into two phases: the T/F phase and the short/long answer phase.
* In T/F phase, you will answer T/F questions in the google form.
* In short/long answer phase, you will do Rust programming to answer the questions in the google form.

### Screen Policy

On the laptop screen, you can only look at the following websites:

* https://gg.kaist.ac.kr/

  * Go to https://gg.kaist.ac.kr/course/17/ and click the exam event.

  * Here, you can see the "event token" (see below).

  * Here, you can also ask questions.
    If your question is not answered for 10 minutes, please let us know.
Your questions can be written either in English or Korean. Answers will be in English.

* The problem/answer sheet as a Google Form

  * It will be announced in gg.

  * To answer the Google Form, you need to (1) log in with a Google account, and (2) fill out your KAIST email address, name, student ID, and the event token.

  * The problems will be in English. You may answer either in English or Korean.

  * Frequently save your answer.
    Google Forms does not automatically save your answers unless you "submit" them.
    You are allowed to resubmit the answers as many times as you want, so it is strongly recommended that you submit your answers frequently.
    It is your responsibility to maintain your answers reliably and we will not make any exceptions due to technical problems such as network disconnections, web browser crashes, web browser hanging, etc.

  * Here's a [practice answer sheet](https://docs.google.com/forms/d/1gdHk2z2vMt5bOWEH7kLzALDLhCBvuG5q9ZjxkCm0jQo/viewform). Please make sure you successfully submitted your solution to the practice sheet **before taking the exam.**
  
* VS Code
  * We will provide a cloud environment that you can access via VS Code. It will be similar enviornment as the VMs you used for assignments. 
  * You will do Rust programming for short/long-answers questions, with this environment.

### Remote Participation Policy

* If you really cannot be physically present in the lecture room, send an email to [jeehoon.kang@kaist.ac.kr](mailto:jeehoon.kang@kaist.ac.kr) to **ask for explicit permission for remote participation.**
  Without such explicit permission, you will be regarded as absent from the exam.

<details>
<summary> Details on remote participation policy </summary>

* You should **join two Zoom rooms with two Zoom accounts:** ["Announcement" room](https://kaist.zoom.us/my/jeehoon.kang) and the "CCTV" room (privately emailed).
  If you have only one account, please sign up once again.

* Join the Announcement room with a device (probably a desktop/laptop) in which you'll solve the exam problems.
  Turn off the camera and microphone.

* Join the CCTV room with another device (probably a laptop/mobile) that observes you during the exam.
  **For the entirety of the meeting, you need to (1) turn on the camera and microphone; (2) show your hand, paper, keyboard, and monitor; and (3) turn off the speaker.**
  (For privacy concerns: please be noted that you agreed to do this at the beginning of the semester.)
I've attached the model scene from the experienced TA below.

* **You should be properly present in both the Announcement and CCTV rooms 10 minutes before the beginning to the end of the exam.**
  If you disappear from the camera after the exam starts, we will assume that you gave up on the exam and your score will be automatically zero.
  Network disconnections and/or power outages will not be excuses. Make sure you find a place where you can get a reliable internet connection and power supply.

* Your Zoom name should be in the form of "200711632 강지훈". Otherwise, you may be disqualified.

* At the beginning of the exam, you will be asked to show your student card.
  Please show it in front of the CCTV camera.

* Frequently read Announcement Zoom room messages. We'll DM you when your CCTV doesn't work properly.
</details>

**Comment by AnHaechan** [comment]
I'll fix some details on this announcement, so pleas wait a moment...

**Comment by AnHaechan** [comment]
If you want to practice using the midterm environment, refer #290 .

**Comment by jirheee** [comment]
statistic    | number
-- | --
total | 110
average | 65.14285714
stdev | 15.89206277
median | 66
max | 98

histogram: https://docs.google.com/spreadsheets/d/e/2PACX-1vQYIZjCUgfyBkAHNRc2Ao-3XSqv5pJEA_Y39jegi7vXMrrFlwYPH98lFdzqlzf_fZA6sSnQqhCg3FTU/pubchart?oid=998875432&format=interactive

**Comment by jirheee** [comment]
- We will upload the scores for individuals so you can check the points for each section here: https://gg.kaist.ac.kr/course/17/


midterm (total score) | 0 | 110
-- | -- | --
midterm (8. Why3 - Division, Any) | 0 | 20
midterm (7. LoggedQueue) | 0 | 10
midterm (6. EventObserving) | 0 | 10
midterm (5. ParseShell) | 0 | 10
midterm (4. mode) | 0 | 3
midterm (3. chooses) | 0 | 3
midterm (2. count_occurences) | 0 | 3
midterm (1. t/f) | 0 | 51


- If you want to make a claim, please send an email to jungin.rhee@cp.kaist.ac.kr by **this Thursday, 2023-10-26, 23:59:59**.
- Please follow the below format so that I can quickly send you the answers.
  - Title: "[CS220 Midterm] Claim for \<your student ID\> \<your name\>"
  - Content: For each claim, label each as the following.
    ```
      * \<Category name\>: \<Points you got\>
      * \<Short description about what you want to claim\>
    ```
  - Category name: T/F, Rust struct/enum, ...
- If there are any changes in the general grading scheme, I will provide an update in this issue here, so please check it before you send me an email.

**Comment by Coll1ns-cult** [comment]
I can't see all of my scores though, is there any problem with it?

**Comment by jirheee** [comment]
We will upload all the scores until midnight :)

**Comment by AnHaechan** [comment]
The scores have been uploaded on the gg.kaist.ac.kr now.

**Comment by AnHaechan** [comment]
NOTE: scores for (7. LoggedQueue) have been updated. (Therefore, also total scores have been updated).
There was some issue during grading, so your scores might have changed a lot. 
Very sorry for the inconvenience.

**Comment by jirheee** [comment]
NOTE: scores for (3. chooses) have been updated. This is because some people's implementation failed due to overflow, which should be ignored.


total | 110
-- | --
average | 66.60714286
stdev | 18.1087863
median | 66
max | 98

**Comment by tncks0121** [comment]
After regrading, my total score does not equal to the sum of each problem's score. Could you please recheck?

**Comment by AnHaechan** [comment]
@jirheee Can you check if you updated total scores as well when updating scores for (3. chooses)?

**Comment by jirheee** [comment]
I believe it is now fixed. Sorry for the confusion.
