### ISSUE TITLE
About borrowing a PC from SoC administration team

### ISSUE THREAD

**Issue by rzhsynv** [kaist-cp/cs220#288]
Hi. My PC has a Linux OS, and Safe Exam Browser software is not available for Linux. At the start of the semester, I mentioned this to professor, and he told that I could borrow a laptop from SoC administration team. However, today I payed them a visit after the lecture, and they told me that there is essentially no such thing as "borrowable laptops". Now, I am really confused about what to do next, and I hope you could help me at your earliest convenience.

**Comment by alex9801** [comment]
SoC administration team used to lend laptops to students in the past, but not anymore. I contacted KAIST IT Service (정보통신팀) as well but to no avail.

**Comment by AnHaechan** [comment]
We, TAs, will resolve this issue ASAP. Thanks for reporting this.

**Comment by AnHaechan** [comment]
Please refer #289
