### ISSUE TITLE
Midterm) For those who don't have Windows/macOS laptops

### ISSUE THREAD

**Issue by AnHaechan** [kaist-cp/cs220#289]
* As we mentioned, you need to bring Windows or macOS laptop with SEB installed, for the exam. 
  * #285
  * If you already have one, you can skip this announcement.
* However, we've found out that borrowing laptops from SoC is not available currently.
  * #288 
* So, if you don't have Windows or macOS laptop, we first propose two options.
  * If you have a laptop with different OS (e.g. Linux), try dual-booting Windows.
  * Borrow Windows/macOS laptops from your friends. (This should be the simplest solution from our experience)
* If the above two options are really not possible, mail us **by this Thursday(Oct 12th)**. Then we will try to get some laptops.
  * We will **NOT** respond mails after this Thursday, as we need time to prepare laptops.

**Comment by woojinnn** [comment]
@alex9801 Reflecting the nature of the situation, we decided to allow you using a external monitor. However, we are  not sure whether SEB allows extended display. Please bring your monitor tomorrow, and let's check whether it works in the rehearsal session. If it doesn't work, you have to find out other ways(Borrowing from external rental companies, etc...).
