### ISSUE TITLE
Different log between server and good game

### ISSUE THREAD

**Issue by seoyeonB** [kaist-cp/cs220#29]
When I run code through ssh it worked, but when I submit the code in good game it don't work. Can you help me find the reason why?

**log in ssh**
`s20200292@kaist-cp-cs220:~/cs220$ ./scripts/grade-02.sh
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.63.0 (4b91a6ea7 2022-08-08)

info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'

  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.65.0-nightly (c2804e6ec 2022-09-07)

info: checking for self-updates
    Finished dev [unoptimized + debuginfo] target(s) in 0.20s
Running with cargo...

running 8 tests
test assignments::assignment02_grade::test::test_capitalize ... ok
test assignments::assignment02_grade::test::test_farenheit ... ok
test assignments::assignment02_grade::test::test_lyrics ... ok
test assignments::assignment02_grade::test::test_chooses ... ok
test assignments::assignment02_grade::test::test_fibonacci ... ok
test assignments::assignment02_grade::test::test_sum_array ... ok
test assignments::assignment02_grade::test::test_up3 ... ok
test assignments::assignment02_grade::test::test_zip ... ok

test result: ok. 8 passed; 0 failed; 0 ignored; 0 measured; 4 filtered out; finished in 0.00s

Running with cargo --release...

running 8 tests
test assignments::assignment02_grade::test::test_capitalize ... ok
test assignments::assignment02_grade::test::test_chooses ... ok
test assignments::assignment02_grade::test::test_farenheit ... ok
test assignments::assignment02_grade::test::test_lyrics ... ok
test assignments::assignment02_grade::test::test_fibonacci ... ok
test assignments::assignment02_grade::test::test_sum_array ... ok
test assignments::assignment02_grade::test::test_up3 ... ok
test assignments::assignment02_grade::test::test_zip ... ok

test result: ok. 8 passed; 0 failed; 0 ignored; 0 measured; 4 filtered out; finished in 0.00s

Running with cargo_asan...

running 8 tests
test assignments::assignment02_grade::test::test_farenheit ... ok
test assignments::assignment02_grade::test::test_capitalize ... ok
test assignments::assignment02_grade::test::test_sum_array ... ok
test assignments::assignment02_grade::test::test_up3 ... ok
test assignments::assignment02_grade::test::test_lyrics ... ok
test assignments::assignment02_grade::test::test_fibonacci ... ok
test assignments::assignment02_grade::test::test_chooses ... ok
test assignments::assignment02_grade::test::test_zip ... ok

test result: ok. 8 passed; 0 failed; 0 ignored; 0 measured; 4 filtered out; finished in 0.00s

Running with cargo_asan --release...

running 8 tests
test assignments::assignment02_grade::test::test_capitalize ... ok
test assignments::assignment02_grade::test::test_fibonacci ... ok
test assignments::assignment02_grade::test::test_sum_array ... ok
test assignments::assignment02_grade::test::test_chooses ... ok
test assignments::assignment02_grade::test::test_farenheit ... ok
test assignments::assignment02_grade::test::test_up3 ... ok
test assignments::assignment02_grade::test::test_lyrics ... ok
test assignments::assignment02_grade::test::test_zip ... ok

test result: ok. 8 passed; 0 failed; 0 ignored; 0 measured; 4 filtered out; finished in 0.00s

Running with cargo_tsan...

running 8 tests
test assignments::assignment02_grade::test::test_capitalize ... ok
test assignments::assignment02_grade::test::test_chooses ... ok
test assignments::assignment02_grade::test::test_farenheit ... ok
test assignments::assignment02_grade::test::test_fibonacci ... ok
test assignments::assignment02_grade::test::test_lyrics ... ok
test assignments::assignment02_grade::test::test_sum_array ... ok
test assignments::assignment02_grade::test::test_up3 ... ok
test assignments::assignment02_grade::test::test_zip ... ok

test result: ok. 8 passed; 0 failed; 0 ignored; 0 measured; 4 filtered out; finished in 0.00s

Running with cargo_tsan --release...

running 8 tests
test assignments::assignment02_grade::test::test_capitalize ... ok
test assignments::assignment02_grade::test::test_chooses ... ok
test assignments::assignment02_grade::test::test_farenheit ... ok
test assignments::assignment02_grade::test::test_fibonacci ... ok
test assignments::assignment02_grade::test::test_lyrics ... ok
test assignments::assignment02_grade::test::test_sum_array ... ok
test assignments::assignment02_grade::test::test_up3 ... ok
test assignments::assignment02_grade::test::test_zip ... ok

test result: ok. 8 passed; 0 failed; 0 ignored; 0 measured; 4 filtered out; finished in 0.00s`

**log when i submit in goodgame**
`[2022-09-08 14:51:24,450: WARNING/ForkPoolWorker-32] Demoting to runner...
info: downloading installer
info: profile set to 'default'
info: default host triple is x86_64-unknown-linux-gnu
warning: Updating existing toolchain, profile choice will be ignored
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.63.0 (4b91a6ea7 2022-08-08)

Rust is installed now. Great!

To get started you may need to restart your current shell.
This would reload your PATH environment variable to include
Cargo's bin directory ($HOME/.cargo/bin).

To configure your current shell, run:
source "$HOME/.cargo/env"
Cloning into 'cs220'...
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.63.0 (4b91a6ea7 2022-08-08)

info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'

  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.65.0-nightly (c2804e6ec 2022-09-07)

info: checking for self-updates
    Checking cs220 v0.1.0 (/app/files/checks/11d6f18a-271c-4b74-8174-720fb2cbc43a/cs220)
    Finished dev [unoptimized + debuginfo] target(s) in 0.28s
Running with cargo...
[0;31m[1mBuild failed![0m
[0;31m[1mTest failed:    cargo test  --lib assignment02_grade[0m`

Thank you

**Comment by zzz845zz** [comment]
Could you please try again after pulling the `main` branch? It seems you're using an outdated version because the grader doesn't run [`test_gcd()`](https://github.com/kaist-cp/cs220/blob/main/src/assignments/assignment02_grade.rs#L33).

**Comment by seoyeonB** [comment]
> Could you please try again after pulling the `main` branch? It seems you're using an outdated version since the grader doesn't run [`test_gcd()`](https://github.com/kaist-cp/cs220/blob/main/src/assignments/assignment02_grade.rs#L33).

Thank you!

**Comment by seoyeonB** [comment]
Thank you!
