### ISSUE TITLE
Exam rehearsal on October 11th (Wed) in the lecture room announcement

### ISSUE THREAD

**Issue by woojinnn** [kaist-cp/cs220#290]
As previously announced https://github.com/kaist-cp/cs220/issues/285, **tomorrow's class will involve a rehearsal session**. The primary objective of this session is to familiarize ourselves with the test environment using the Safe Exam Browser (SEB) tool. Your active participation in tomorrow's rehearsal is strongly encouraged to help prevent any potential penalties related to the test environment.

In preparation for the class, we kindly request that you **bring your laptop, equipped with the SEB software, in a fully charged state.**

---

We are going to explain below stuffs in the class tomorrow:
1. Download [cs220_rehearsal.zip](https://github.com/kaist-cp/cs220/files/12857829/cs220_rehearsal.zip) and open `cs220_rehearsal_part1`
1. Check whether your answer is correctly recorded in the sheet: [Part1 responses](https://docs.google.com/spreadsheets/d/1qFVYRMxAuzfXEHccZxFKJ1St7b04Vq6CxkSOBQAAy1o/edit?usp=sharing)
1. Open `cs220_rehearsal_part2`
1. Check whether your answer is correctly recorded in the sheet: [Part2 responses](https://docs.google.com/spreadsheets/d/1ClVRYYJEfxZZEwIt59nA_RtULWNzfZcLmwHPKTJRbSg/edit?usp=sharing)

**Comment by AnHaechan** [comment]
The password for sample configuration file is `cs220`.

**Comment by AnHaechan** [comment]
+ Tutorial slide: https://docs.google.com/presentation/d/1M8N8HTh7St-hfjuegpyOefxEXJdbdvv4Xr4wK7FXEn8/edit#slide=id.g282156dfff9_0_10

**Comment by Lee-Janggun** [comment]
Some students may want to practice on their own, so I suggest pinning this issue and leaving it open until the exam is over.
