### ISSUE TITLE
Issues that occurred during the rehearsal session

### ISSUE THREAD

**Issue by woojinnn** [kaist-cp/cs220#293]
## About Midterm (MUST READ)
1. **Exam structure**: The exam is composed of two distinct components: `Part 1`, comprising True/False questions, and `Part 2`, featuring long-answer programming questions. All students are required to commence `Part 1` and `Part 2` simultaneously, awaiting the announcement from administrators to initiate. Even if students complete `Part 1` ahead of time, they must adhere to the designated starting time for `Part 2` as determined by the administrators.
2. **Power supply**: We will endeavor to provide power strips; however, we cannot assure that all students will have access to them. Please ensure your laptop is fully charged prior to the examination.
3. **Google form format revision**: We will amend our Google Form to enable access to `gg.kaist.ac.kr` and `remote server` from every page.
4. **Cell phone usage for first minute**: For students who uses 2FA for Google login, we will allow you to use cellphone for the first minute.
5. **Remote server**
   1. We will install `cargo` and 2 VSCode extensions(`rust-analyzer` and `CodeLLDB`) so that you can run your code on the server.
   2. We are going to disconnect network so that students cannot access online materials through remote server.
   3. We will announce again after we set remote server properly. Stay tuned.
6. Make sure you are familiar with SEB environment(moving windows back and forth, etc...). Rehearse with provided example SEB files.

## SEB Troubleshooting (For students who struggled during the rehearsal)
1. Accessing `gg.kaist.ac.kr`
   1. If you are unable to access `gg.kaist.ac.kr` by clicking on it, please hold down the Command (cmd) key while clicking. This issue has been a common occurrence for Mac users.
   2. To switch between windows, such as Google Form and other applications like `gg.kaist.ac.kr`, simply hover over the SEB icon located at the bottom left of the screen. Additionally, on some machines, you may also use the "Alt" + "Tab" key combination for window switching.
2. Google login
   1. The redirection to Google Form hangs after logging in: We were unable to determine the root cause of this issue, but it appears that pressing the "Back" button can resolve it.
3. SEB
   1. Installation: If the installation program fails to proceed, please consider utilizing the release files available on the SEB GitHub homepage. For macOS, you can access the release files at [seb-mac](https://github.com/SafeExamBrowser/seb-mac/releases), and for Windows, they are available at [seb-windows](https://github.com/SafeExamBrowser/seb-win-refactoring/releases/tag/v3.5.0). When opting for a release file from the release page, ensure that you also install the specified requirements as mentioned. If some functions(Unable to access `gg.kaist.ac.kr` by clicking on it, doesn't redirect you to `gg.kaist.ac.kr`, etc...) doesn't work, check whether your SEB version is up-to-date. If not, reinstall the SEB.

**Comment by tncks0121** [comment]
Hi, is there any plans on the development server to test with? It would be helpful to at least have Dockerfile, since then I can use github codespaces by myself.

**Comment by woojinnn** [comment]
@tncks0121 Writing now!!! I will post it in an hour.
