### ISSUE TITLE
Extended midterm exam time, Development Server is configured now.

### ISSUE THREAD

**Issue by woojinnn** [kaist-cp/cs220#294]
## Administrative

- Midterm Exam Notice
  - **Date:** October 18th, Wednesday
  - **Time:** **13:00 - 15:30** (Originally announced as 13:00 - 15:00 (https://github.com/kaist-cp/cs220/issues/285), revised for extended time)
  - **Location:** Lecture Room, E11, 3rd Floor, Room 304

We wish to inform you about an important update regarding the midterm exam scheduled for tomorrow. Initially, the exam was scheduled to be conducted from 13:00 to 15:00. However, after careful consideration, we have decided to extend the duration to provide students with more time. We apologize for any confusion this may have caused.

- **Exam Structure:**
  - Part 1: True/False (T/F) Questions
    - Duration: 60 minutes

  - Part 2: Programming Questions
    - Duration: 90 minutes

  - **Important:** All students are required to commence both `Part 1` and `Part 2` simultaneously, awaiting the official announcement from the administrators. Even if students complete `Part 1` ahead of time, they must adhere to the designated starting time for `Part 2` as determined by the administrators.

- **Development Server:**

  - As part of `Part 2`, we will provide a development server for programming questions.
  - Please carefully review the following information regarding the development server.

- **SEB:**

  - The Google Forms used during the rehearsal session remain accessible. It is important that you are acquainted with the use of SEB (Safe Exam Browser) as we may not be able to address sudden issues during the exam.

## Development Server

- **Access Link:** https://cloud-exam.fearless.systems/workspaces

For `Part 2`, students will be required to create a workspace and write code within it. You are not allowed to use code editors installed on your personal laptops. Prior to the exam, please ensure that you are well-versed in using the provided development server.

- **List of Editors Provided:**
  - Visual Studio Code
  - Vim and Emacs (Accessible via terminal)
- **List of Installed Programs:**
  - Rustup
  - VSCode Extensions: rust-analyzer, codelldb
- **Network Availability:** Please note that **network access will be unavailable on the development server**, and you are only permitted to use the aforementioned programs. However, rust-analyzer will be available. You can use this instead of Rust std documentation.
- **Important:** The development server will be reset prior to the midterm exam, and any workspaces created before the exam will be removed.
- **Workspace Configuration Instructions:**
  - Navigate to `Templates`.
  - Select `Create Workspace` for the 'cs220' template.
  - Enter a `Workspace Name` (anything is acceptable).
  - Click `Create Workspace`.
  - Your workspace will be generated shortly. Utilize `code-server` (not 'VS Code Desktop') or the `terminal` for your coding tasks.

We wish you the best of luck in your midterm exam. If you have any questions or require further clarification, please do not hesitate to reach out to the administrators.

**Comment by jirheee** [comment]
# Important Notice About Laptop Batteries

To ensure we're all set for the event, please ensure your laptops are fully charged beforehand since only a limited number of outlets will be available. If you're concerned about your laptop's battery lasting throughout the exam, please arrive early to secure a seat close to a power source. Your cooperation is much appreciated!
