### ISSUE TITLE
Cannot use development server

### ISSUE THREAD

**Issue by zee-doubleu-ee** [kaist-cp/cs220#299]
I went to https://cloud.fearless.systems/ to access my development server but it's not working.
![Screenshot 2023-10-24 at 22-14-47 Something went wrong](https://github.com/kaist-cp/cs220/assets/73657186/2d720680-599b-479e-846a-121be09d59bc)

**Comment by jeehoonkang** [comment]
Try again with private mode? (or after clearing cookies?)

**Comment by zee-doubleu-ee** [comment]
The same error. And, I can't also submit my assignments at gg.

**Comment by jeehoonkang** [comment]
- try other machines?
- gg: please describe the symptom in more detail.

**Comment by zee-doubleu-ee** [comment]
For [https://cloud.fearless.systems](https://cloud.fearless.systems) I also tried making a new one from **dev** template but still has the same problem.

**Comment by AnHaechan** [comment]
#301
