### ISSUE TITLE
I did not get the e-mail about the KAIST CS Honor Code.

### ISSUE THREAD

**Issue by Youhyeon1013** [kaist-cp/cs220#3]
The professor said that he e-mailed the honor code to all the students. I checked my mails, but there are no mails about it. Could you e-mail me again? Below is my e-mail address.

zxdsa123@kaist.ac.kr

**Comment by jeehoonkang** [comment]
Sorry for the confusion. The honor code sign form will be shared next week.

**Comment by Youhyeon1013** [comment]
Oh, I see. Thank you.

**Comment by jeehoonkang** [comment]
@Youhyeon1013 i believe an email has been sent to your kaist email address.

**Comment by Youhyeon1013** [comment]
> @Youhyeon1013 i believe an email has been sent to your kaist email address.

Yes, I received the email and completed the form. Thank you.
