### ISSUE TITLE
[HW1] Does 'filtered out' is not matter?

### ISSUE THREAD

**Issue by tlsdud020918** [kaist-cp/cs220#30]
I see below result when I run my HW1 code in the gg website and the return code is zero. But there are **9 filtered out cases**, so is there any problem to get full credit?
test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; **9 filtered out**; finished in 0.00s

**Comment by m-spitfire** [comment]
No it doesn't. 9 filtered out cases is for assignment 2 which is not relevant for hw#1. If your "Success" column is "Yes" for the submission, then you're good.
