### ISSUE TITLE
[Assignment 10] Pythagorean ordering

### ISSUE THREAD

**Issue by 08kmc09** [kaist-cp/cs220#300]
### Googling Result

https://en.wikipedia.org/wiki/Pythagorean_triple#Enumeration_of_primitive_Pythagorean_triples

### ChatGPT Result

https://chat.openai.com/c/f91d1d26-b7f8-4921-8969-8d4177955d3e

### Your question here

I tried to generate primitive pythagorean triple on the ordering of cantor_pairing.

But the cantor_pairing order that holds m > n > 0 & m+n is odd, gcd(m,n) = 1 does not produces the correct order in the increasing order of c (m^2 + n^2).

The provided document explain only about cantor pairing. What's the problem?

**Comment by jirheee** [comment]
You don't have to enumerate Pythagorean triples using cantor pairing. The document was given to explain what primitive Pythagorean triples are, not to show the algorithm.

**Comment by 08kmc09** [comment]
Oh I see, I'll try with different approach.
