### ISSUE TITLE
[Assignment 13] Issue with the grade script

### ISSUE THREAD

**Issue by 08kmc09** [kaist-cp/cs220#302]
### Googling Result

-

### ChatGPT Result

-

### Your question here

failures:

---- assignments::assignment13::small_exercises_grade::test::dot_product_test stdout ----
thread 'assignments::assignment13::small_exercises_grade::test::dot_product_test' panicked at 'not yet implemented', src/assignments/assignment09/matmul.rs:38:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- assignments::assignment13::small_exercises_grade::test::vec_add_test stdout ----
thread 'assignments::assignment13::small_exercises_grade::test::vec_add_test' panicked at 'not yet implemented', src/assignments/assignment09/matmul.rs:18:5

---- assignments::assignment13::small_exercises_grade::test::matmul_test stdout ----
thread 'assignments::assignment13::small_exercises_grade::test::matmul_test' panicked at 'not yet implemented', src/assignments/assignment09/matmul.rs:71:5

failures:
    assignments::assignment13::small_exercises_grade::test::dot_product_test
    assignments::assignment13::small_exercises_grade::test::matmul_test
    assignments::assignment13::small_exercises_grade::test::vec_add_test

test result: FAILED. 2 passed; 3 failed; 0 ignored; 0 measured; 102 filtered out; finished in 0.01s

Test failed:    cargo test  --lib -- assignments::assignment13::small_exercises_grade::test
Your score: 0/1

I think the grading script must implement the matmul, dot_product, vec_add in assignment09.

**Comment by woojinnn** [comment]
That's intended. Stuffs that test code checks are: `Correctness` and `Performance`.
But in case that you want to check your code's correctness first, I will divide them(There will be no partial points, though).
I will let you know once I'm done modifying it!

**Comment by woojinnn** [comment]
@08kmc09  I modified it.

**Comment by 08kmc09** [comment]
Oh, I already submitted Assignment09.. but Assignment 13 does not checked properly. I will fetch the upstream and recheck it.

**Comment by 08kmc09** [comment]
My guess is that the grading script only gets assignment 13, so it keeps failing because it doesn't have the implementation included in assignment 9 to compare it to.

**Comment by woojinnn** [comment]
Oh I see... That's not the problem of test code. I will modify script accordingly.

**Comment by woojinnn** [comment]
@08kmc09 I modified the script. Can you fetch and resubmit your file?

**Comment by 08kmc09** [comment]
Now submitted correctly! I appreciate for your help😀
