### ISSUE TITLE
[Assignment 8] How Rc::clone() and count_strong() works in specific case?

### ISSUE THREAD

**Issue by Engineer-JJHaMa** [kaist-cp/cs220#305]
### Googling Result

https://doc.rust-lang.org/std/rc/struct.Rc.html

### ChatGPT Result

https://chat.openai.com/share/20b5de89-345e-4292-bb65-26e39bd448c8

### Your question here

I tried to implement to_usize by counting strong_count of function f when I apply some function f to church numeral n.
I implemented function mult like below code
```
pub fn mult<T: 'static>(n: Church<T>, m: Church<T>) -> Church<T> {
    Rc::new(move |f| {
        let m_result = m(n(f.clone()));
        // to inc strong_count of f
        println!("mulA: {}", Rc::strong_count(&f));
        Rc::new(move |x| m_result(x))
    })
}
```
I expected that print will show "mulA: {m*n}". Howver, it show value n, not n*m.
So I tried to find how reference counter works for this case. And I found f has strong_count n, and n has strong_count m.
My question is cloning n(f) does not increase strong_count of f? Then why it works like that?

**Comment by jirheee** [comment]
I did not notice there was a question. Sorry for the late answer :(

Regarding your solution, I think you are on the wrong track to implement `to_usize`, I recommend trying another approach that does not look into the reference counter.

For some hint, `n` in church numeral is `\lambda f.\lambda x. f^n(x)`, which applies the function `f` `n` times to some `x`. Therefore, you should devise some method(maybe give your own `f` and `x`?) to use this fact to somehow calculate `n` as `usize`.

**Comment by Engineer-JJHaMa** [comment]
Thank you!
