### ISSUE TITLE
[Assignment 7] How to implement iterator trait for generator

### ISSUE THREAD

**Issue by 1starJ** [kaist-cp/cs220#308]
### Googling Result

https://docs.rs/generator/latest/generator/

### ChatGPT Result

https://chat.openai.com/share/1d376923-4011-4359-8e33-532e5039cfd0

### Your question here

In assignment 7, I have a question.
To implement the iterator trait for `generator`, I have to define the `next` method.
I think I can do the "return part", I take the function `f` to `state`. But I should advance `self`, and I don't know how to do that.
I don't know how to do that because I think that the function `f` has input of state, so it has to have output of state.
But the output of `f` is different from the state, and its type is T. Why is it?

Here is my code:
```
//! Generators
//!
//! HINT: Look at the `generator_grade.rs` file to see how the generator is used.

/// Yielded value. It can be either a value or a stop signal.
enum Yielded<T> {
    Value(T),
    Stop,
}

/// Generator
/// - You can call `next()` method to get the next value.
/// - The generator should stop when it yields `Yielded::Stop`.
///
/// Reference:
/// - [Python generator](https://python-reference.readthedocs.io/en/latest/docs/generator/)
#[allow(missing_debug_implementations)]
pub struct Generator<T, S> {
    state: S,
    f: fn(&mut S) -> Yielded<T>,
}

impl<T, S> Iterator for Generator<T, S> {
    type Item = T;

    fn next(&mut self) -> Option<Self::Item> {
        match (self.f)(&mut self.state) {
            Yielded::Value(s) => Some(s),
            Yielded::Stop => None,
        }
    }
}


/// Returns a generator that yields fibonacci numbers.
///
/// HINT: Consult <https://en.wikipedia.org/wiki/Fibonacci_sequence>
pub fn fib_generator(first: usize, second: usize) -> Generator<usize, (usize, usize)> {
    Generator { state: (first, second), f: func1 }
}

/// Returns a generator that yields collatz numbers.
///
/// HINT: Consult <https://en.wikipedia.org/wiki/Collatz_conjecture>
pub fn collatz_conjecture(start: usize) -> Generator<usize, usize> {
    todo!()
}
```

**Comment by jirheee** [comment]
First of all, please do not post your answer here.

For your question, the generic type `T` and `S` has different usage.

```
pub struct Generator<T, S> {
    state: S,
    f: fn(&mut S) -> Yielded<T>,
}

impl<T, S> Iterator for Generator<T, S> {
    type Item = T;

    fn next(&mut self) -> Option<Self::Item> {
        match (self.f)(&mut self.state) {
            Yielded::Value(s) => Some(s),
            Yielded::Stop => None,
        }
    }
}
```

Looking at the above signature, you can see that `S` is generic for the state, whereas `T` is generic for the item type of each generator step.

This design allows the user of this generator to use arbitrary type for the state, independent of the generated item.

Also, regarding advancing the generator's state, please look at the type signature of the `f` field of the generator carefully.

**Comment by 1starJ** [comment]
Okay, I will not post my answer here. Excuse me for violating the rule.

I understand that `T` and `S` are independent generics because we want `state` to be consisted of many items.

I'm not clear about the exact meaning of `state` and `item`. Are they corresponded to the initial condition and entry of a sequence?

Also, I think that I should be able to access to the components of `S` in order to advance the `state`. For example, (a,b) -> (b,a+b). But I think I cannot do that because `S` is independent to `T`. Am I in the wrong direction?

**Comment by jirheee** [comment]
When you look at the signature of f, receives a mutable reference to the state S. Does this answer your question?

**Comment by jirheee** [comment]
I think maybe you did not understand how the generator works. Did you look at the test cases for the assignment?

**Comment by 1starJ** [comment]
I was thinking too difficultly and overthought things. Thank you so much for your explanation. I'm pretty sure I know what to do now.
One last question is, in the `fib_generator` function, it returns `Generator<usize, (usize, usize)>`. And `f` has to get an input `&mut S`. But tuple is not mutable, then how do I change the `state`?
I ask this question because I tried my code and got an error: 
`cannot assign to immutable argument`

**Comment by 1starJ** [comment]
Thanks. I solved an error.
