### ISSUE TITLE
[Assignment 9] grade.sh seems to wrong

### ISSUE THREAD

**Issue by 2prolove** [kaist-cp/cs220#309]
### Related Issue

none

### Googling Result

none

### ChatGPT Result

none

### Your question here

./grade.sh 9's result was strange, so I checked it, and there seems to be an error in the TEST09) part of the grade.sh file. I think the matmul_grade.sh part should be added.
TEST09)
        TESTS=(
            "assignments::assignment09::bigint_grade::test"
            "assignments::assignment09::small_exercises_grade::test"
        )
        ;;
Above is the current grade.sh file status.

**Comment by jirheee** [comment]
@woojinnn Woojin could you please have a look?

**Comment by woojinnn** [comment]
@2prolove I just modified it. Thank you for your report! Can you check it again?

**Comment by 2prolove** [comment]
It is solved! Thank you.
