### ISSUE TITLE
[HW1] The server's evaluation results differ from your own evaluation

### ISSUE THREAD

**Issue by sangdevil** [kaist-cp/cs220#31]
As announced,
I checked the code in the assignmentgrade_01.rs using .\scripts\grade-01.sh, and it says that there is nothing wrong, 
but when I submit the code to the submitting site, there's NO appear in "Success?".
I'm sorry to ask a question late.
![화면 캡처 2022-09-09 225512](https://user-images.githubusercontent.com/101849478/189367419-492710e3-5c56-4a1e-b0dc-bffc39e509fd.png)
![화면 캡처 2022-09-09 225826](https://user-images.githubusercontent.com/101849478/189367437-cb90a09b-e6a1-4d87-a481-c5bd2ecb02f9.png)

**Comment by m-spitfire** [comment]
check the logs of submission by clicking "log".

**Comment by sangdevil** [comment]
Thank you.
