### ISSUE TITLE
[Assignment #8] Timeout in test case i_said_engineering_isnt_just_mathematics()

### ISSUE THREAD

**Issue by Coll1ns-cult** [kaist-cp/cs220#314]
### Googling Result

https://users.rust-lang.org/t/increment-operator-in-rust/86684/22?page=2

### ChatGPT Result

https://chat.openai.com/c/d97eee93-bcdc-4712-b577-003dd4e586fc

### Your question here

I was trying to pass the test case i_said_engineering_isnt_just_mathematics() (777777777777777). Which first converts the constant number to church_numeral, then translates back to `usize`. The problem with this test case is the timeout that I face. I believe from_usize is correctly implemented because the debug string that I put after the function prints. And I tested it against small numbers where timeout doesn't occur, and it seems to be correct. So I believe the time-consuming part of the test case is to_usize(). I implemented to_usize() by defining a counter owned by two variables which can be mutated. I did it with the help of `Rc<RfCell<T>> `In my function f that I pass to Church numeral, I mutate the counter by` counter += 1`. I would like to know if there's a faster way of incrementing, or counting, other than the way I did, or Generally,  my scope on fault localisation is wrong, and indeed problem is in the from_usize (I don't how it is printed, maybe compiler do some magic ?)

**Comment by AnHaechan** [comment]
As I mentioned in the email, the question is directly related to the implementation so we cannot give answers.
