### ISSUE TITLE
[Assignment 10] Can I add fields to the Pythagorean struct?

### ISSUE THREAD

**Issue by Wonigox** [kaist-cp/cs220#316]
### Googling Result

N/A

### ChatGPT Result

N/A

### Your question here

Are we allowed to modify the Pythagorean struct to include custom fields or should we keep it as empty? 

If we are supposed to keep it as empty, I am not sure how to create an iterator over it since we should have some way of "remembering" where the iterator is. Any hints would be appreciated.

**Comment by woojinnn** [comment]
Yes, you may add custom fields in to `Pythagorean` struct.
