### ISSUE TITLE
[Assignment 9] question about position_median function

### ISSUE THREAD

**Issue by bscho99** [kaist-cp/cs220#317]
### Googling Result

None

### ChatGPT Result

None

### Your question here

This is a question about provided test cases of position_median function in assignment09/small_exercises.rs
According to the specification, if 'n', which is the number of distinct elements in a collection is even, the median of the collection is '(n/2)+1'-th smallest element.
For example, for the collection [1, 3, 3, 6, 7, 8, 9], since there are 6 distinct elements, which is an even number, the median of the collection should be (6/2)+1 = 4th smallest number, which is 7, and thus, if the algorithm is correctly implemented, should be returning Some(4).
However the test case provided in assignment09/small_exercises_grade.rs does not seem to reflect this fact. I'll add a screenshot of the problematic code down below.
![image](https://github.com/kaist-cp/cs220/assets/76726231/4ad204ee-a38c-4e22-aa49-10b2d2227ab0)

I suppose there might be something that I have missed or wrongly understood. Please let me know!

**Comment by woojinnn** [comment]
> if 'n', which is the number of distinct elements in a collection
There is no specification about "distinct" elements.
