### ISSUE TITLE
[Assignment 9] invalid octal number while grading

### ISSUE THREAD

**Issue by cyshello** [kaist-cp/cs220#319]
### Googling Result

none

### ChatGPT Result

none

### Your question here

when I ran the test of assignment09 by myself, I got all correct.
By the way, when I ran grade.sh 09, I found some strange result :

ubuntu@cs220:~/cs220$ scripts/grade.sh 09
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.74.0 (79e9716c9 2023-11-13)

info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'

  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.76.0-nightly (a1a37735c 2023-11-23)

info: checking for self-update
    Finished dev [unoptimized + debuginfo] target(s) in 0.24s
Running with cargo...
scripts/grade.sh: line 27: printf: 09: invalid octal number

which is invalid octal number.

Can you give me an idea what happened?

**Comment by cyshello** [comment]
Also, I have already got the modified code of grade.sh.

**Comment by woojinnn** [comment]
Sorry for the late response. Try `scripts/grade.sh 9` (not 09). Hope it works well

**Comment by cyshello** [comment]
solved ! Thx :)
