### ISSUE TITLE
Office hour for 2022 Fall

### ISSUE THREAD

**Issue by zzz845zz** [kaist-cp/cs220#32]
For this semester, we will have office hour every week.

- Office Hour: Fri 9:00am-10:00, [Zoom room](https://zoom.us/j/71923059728) (passcode: same as the class, announced at KLMS.)
- It is not required, but if you want to come, do so by 9:15 am.
- See [this](https://github.com/kaist-cp/cs220#rules) for office hour policy.

**Comment by jeehoonkang** [comment]
Closing (the same information at https://github.com/kaist-cp/cs220#logistics)
