### ISSUE TITLE
Schedule guide for remaining classes

### ISSUE THREAD

**Issue by woojinnn** [kaist-cp/cs220#321]
We are almost done! ᕦ( ᐛ )ᕡ
This is the announcement about the schedules of remaining classes:
- 11/29 (Wed) => No class (University admission interview).
- 12/4 (Mon) => Video lecture (Content will be announced soon).
- 12/6 (Wed) => Face-to-face lecture as usual (Q&A session before the final exam).
- 12/11 (Mon) => No class (Exam week).
- 12/13 (Wed) => Final exam.

**Comment by AnHaechan** [comment]
Alternative lecture announced #324
