### ISSUE TITLE
[Assignment 11] Grading server error

### ISSUE THREAD

**Issue by sehyeondev** [kaist-cp/cs220#322]
### Googling Result

None

### ChatGPT Result

None

### Your question here

When I submit to the grading server, I got the following errors in the log.
I got the full score when testing in the given remote server.
Is this an error from grading server or my code?

/* ... */
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: latest update on 2023-11-30, rust version 1.76.0-nightly (b10cfcd65 2023-11-29)

info: downloading component 'rust-src'
/* Some downloadings */
info: downloading component 'rustfmt'

info: removing previous version of component 'rust-src'
/* Some removings */
info: removing previous version of component 'rustc'

warning: during uninstall component rustc was not found
info: removing previous version of component 'rustfmt'
warning: during uninstall component rustfmt was not found

info: installing component 'rust-src'
/* Some installings */
info: installing component 'rustc'

info: rolling back changes
error: could not rename component file from '/home/runner/.rustup/tmp/_yvsy68ygz0u2__e_dir/bk' to '/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/etc'
error: could not rename component file from '/home/runner/.rustup/tmp/y6hjgceuprxe1yad_dir/bk' to '/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/share/zsh'
error: could not rename component file from '/home/runner/.rustup/tmp/xqoo0mrd9b0lvj77_dir/bk' to '/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src'
/* So many repeated errors for renaming component files */
error: failed to install component: 'rustc-x86_64-unknown-linux-gnu', detected conflict: 'bin/rust-gdb'

**Comment by jeehoonkang** [comment]
@sehyeondev sorry, would you please try again?

**Comment by sehyeondev** [comment]
@jeehoonkang It works fine now. Thanks!
