### ISSUE TITLE
[Dec 4th] Alternative Lecture

### ISSUE THREAD

**Issue by AnHaechan** [kaist-cp/cs220#324]
* On December 4th (Mon), instead of the regular lecture, you will read [Chapter 20 of the Rust book](https://doc.rust-lang.org/book/ch20-00-final-project-a-web-server.html), to recap concepts learned so far in this semester.

* Although not necessary, we **highly recommend** you to clone-code through the chapter (that is, manually write the code snippets in the chapter and actually `cargo run` those programs).
  * Because it is more fun & fulfulling to write and run your program, than just reading the document.
  * Because the code snippets will be covered in the final exam.
  * Hopefully, it won't be a much burden as you're just replicating what is written in the document.

* You don't need to come to the classroom.

**Comment by 08kmc09** [comment]
Did you mean that Chapter 20 is also the scope of the final exam?

**Comment by AnHaechan** [comment]
@08kmc09 Yes, it is.
