### ISSUE TITLE
[Assignment 12] Occasionally succeeded to pass the test case

### ISSUE THREAD

**Issue by Dongyeongkim** [kaist-cp/cs220#325]
### Googling Result

none

### ChatGPT Result

none

### Your question here

in the card_grade, because the strategy does not know about the ground truth of the card field, therefore the strategy itself should be fixed. Therefore I wrote a strategy related to this setting, but it occasionally pass or not. Can you clarify the card.rs could be solved with deterministic algorithm? thank you.

**Comment by woojinnn** [comment]
For now, if you pass the test on the grading server(i.e., gg.kaist.ac.kr) for the last submitted one, you will get the full grade.
