### ISSUE TITLE
[Assignment 13] Having error while doing tests.

### ISSUE THREAD

**Issue by kim-j-h** [kaist-cp/cs220#327]
### Related Issue

cannot find 

### Googling Result

cannot find

### ChatGPT Result

https://chat.openai.com/share/5ffe0d7d-9346-41b2-b148-e4b0f1452045

### Your question here

 *  Executing task: cargo test --package cs220 --lib -- assignments::assignment13::small_exercises_grade::test --nocapture 

   Compiling cs220 v0.1.0 (/home/ubuntu/cs220)
thread 'copy tczeibz9tfvwzrg' panicked at 'no saved object file in work product', /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/compiler/rustc_codegen_ssa/src/back/write.rs:895:45
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_display
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:150:5
   3: core::panicking::panic_str
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:134:5
   4: core::option::expect_failed
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/option.rs:1932:5
   5: rustc_codegen_ssa::back::write::execute_work_item::<rustc_codegen_llvm::LlvmCodegenBackend>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.71.0 (8ede3aae2 2023-07-12) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
thread '<unnamed>' panicked at '/rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/compiler/rustc_codegen_ssa/src/back/write.rs:1535:21: worker thread panicked', compiler/rustc_middle/src/util/bug.rs:36:26
stack backtrace:
   0: std::panicking::begin_panic::<alloc::string::String>
   1: rustc_middle::util::bug::opt_span_bug_fmt::<rustc_span::span_encoding::Span>::{closure#0}
   2: rustc_middle::ty::context::tls::with_opt::<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, !>::{closure#0}
   3: rustc_middle::ty::context::tls::with_context_opt::<rustc_middle::ty::context::tls::with_opt<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
   4: rustc_middle::util::bug::bug_fmt
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.71.0 (8ede3aae2 2023-07-12) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
thread 'rustc' panicked at '/rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/compiler/rustc_codegen_ssa/src/back/write.rs:1899:17: panic during codegen/LLVM phase', compiler/rustc_middle/src/util/bug.rs:36:26
stack backtrace:
   0: std::panicking::begin_panic::<alloc::string::String>
   1: rustc_middle::util::bug::opt_span_bug_fmt::<rustc_span::span_encoding::Span>::{closure#0}
   2: rustc_middle::ty::context::tls::with_opt::<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, !>::{closure#0}
   3: rustc_middle::ty::context::tls::with_context_opt::<rustc_middle::ty::context::tls::with_opt<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
   4: rustc_middle::util::bug::bug_fmt
   5: <rustc_session::session::Session>::time::<rustc_codegen_ssa::back::write::CompiledModules, <rustc_codegen_ssa::back::write::OngoingCodegen<rustc_codegen_llvm::LlvmCodegenBackend>>::join::{closure#0}>
   6: <rustc_codegen_ssa::back::write::OngoingCodegen<rustc_codegen_llvm::LlvmCodegenBackend>>::join
   7: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::join_codegen
   8: <rustc_interface::queries::Linker>::link
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.71.0 (8ede3aae2 2023-07-12) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `cs220` (lib test)

 *  The terminal process "cargo 'test', '--package', 'cs220', '--lib', '--', 'assignments::assignment13::small_exercises_grade::test', '--nocapture'" terminated with exit code: 101. 
 *  Terminal will be reused by tasks, press any key to close it. 

While testing my code for assignment 13, I suddenly got this. I don't remember anything signeficant job I've done that results to this. The same error occurs when I test previous assignment which had no problem before.

**Comment by woojinnn** [comment]
https://stackoverflow.com/questions/70401821/error-could-not-compile-time-when-using-cargo-to-compile
https://github.com/kaist-cp/cs431/issues/269

I found some related issues.
Would you try `cargo clean` and re-running it?
Does this problem happen in your provided development server(I mean, https://cloud.fearless.systems/)?

**Comment by kim-j-h** [comment]
Thanks for your advice.

Chat GPT suggested cargo clean as well as rustup update and cargo build, so I've tried.
However, cargo clean could not compile becauwse of my debug folder is not empty, so I manually deleted the contents of debug folder and retried. However, my error have not beel resolved.

Yes, I've been doing my assignments via vscode connected to the development server.

**Comment by kim-j-h** [comment]
.
