### ISSUE TITLE
[Assignment 12] Card game strategy & concurrency

### ISSUE THREAD

**Issue by jsk3040** [kaist-cp/cs220#328]
### Googling Result

N/A

### ChatGPT Result

N/A

### Your question here

Hello, I think that I am misunderstanding the purpose of the card game overall. I see that in the skeleton code, we are provided with Arc and Mutex, so I am guessing that some concurrency must be used to beat the computer's strategy (after all, assignment 12 is focused on concurrency). However, I also think that the player is only limited to being 1 thread, so I am not sure if Arc or Mutex should ever be used in our player strategy. So I don't understand how this part of assignment 12 is related to concurrency.

Overall, I am having difficulties trying to beat the computer. It seems that there is something that I am not understanding from the assignment. I have understood that the computer threads are basically assigned a region and each thread sequentially flips the cards in its region (sleeps for 10 microseconds if already Blue). However, with the lack of information the player has (doesn't know the state of the cards), I can't seem to improve my solution further (current solution gets around 4000 white cards in the end).

Any high-level insight/hints would be very much appreciated (if allowed).

**Comment by woojinnn** [comment]
Thanks for the question. Basically, this is an open-ended question. Hence, I cannot answer for the implementation strategy. Sorry about that.
As commented in the `card.rs` file, you have to start from `card_grade.rs` file, and figure out what the Bot's strategy is. I think you did this one.
> However, with the lack of information the player has (doesn't know the state of the cards)

The player doesn't know about the state of the cards, but you may utilize(not necessary though) memory in the given code. Also, you can figure out at least the bot's strategy.


> I have understood that the computer threads are basically assigned a region and each thread sequentially flips the cards in its region (sleeps for 10 microseconds if already Blue).

You got the point. Yes, the bots sleep for 10 microseconds if they meet the Blue card. Why don't you try using this feature to freeze bots?

> However, I also think that the player is only limited to being 1 thread, so I am not sure if Arc or Mutex should ever be used in our player strategy.


Regarding the usage of `Arc` and `Mutex`, you may not use them if you don't want to. It's not necessary to use them.

**Comment by jsk3040** [comment]
Thanks for the reply. 
I focused on trying to delay the progress of the bot threads and managed to increase the chance of winning by quite a bit! 
I'll leave the issue opened until tonight in case someone else might need some help in solving this assignment.
