### ISSUE TITLE
how to solve this error?

### ISSUE THREAD

**Issue by albinjeon** [kaist-cp/cs220#33]
![캡처](https://user-images.githubusercontent.com/12196529/189385203-a6e24252-7331-47d4-a09f-ade471d77afd.PNG)
![캡처2](https://user-images.githubusercontent.com/12196529/189385215-9f3fb06a-efe1-45cb-b182-a7971f0bb1ca.PNG)

This error suddenly occurred while running "assignment02_grade.srs" to test the code. This did not happen before, but after this error, other files in cs220 are not running either. However, the rust file in the other folder is executed. How do I solve this? If I have to delete the folder and download it again, I want to know how to do it. :(

**Comment by Lee-Janggun** [comment]
Can you try running 'cargo clean' first and running the test again?

**Comment by jeehoonkang** [comment]
Please write down your code as text, not image. Closing due to images. Please create a new issue.

**Comment by albinjeon** [comment]
> Can you try running 'cargo clean' first and running the test again?

thanks!

**Comment by albinjeon** [comment]
> Please write down your code as text, not image. Closing due to images. Please create a new issue.

using cargo clean
