### ISSUE TITLE
[Assignment 13] GG can not find the function of assignment 9.

### ISSUE THREAD

**Issue by dachshoon** [kaist-cp/cs220#331]
### Related Issue

none

### Googling Result

none

### ChatGPT Result

none

### Your question here

I used interleave3 function, which i implemented in assignment 9. However, I think GG can not find the function. Can't I use the function that i made before?
![스크린샷 2023-12-10 174743](https://github.com/kaist-cp/cs220/assets/143372559/500ef4fe-b442-4311-aed0-22b8c7f0b85b)

**Comment by woojinnn** [comment]
Is this your problem?
https://github.com/kaist-cp/cs220/issues/302
If so, please update the repository to the most recent version and try again.

**Comment by dachshoon** [comment]
thanks!
