### ISSUE TITLE
[Assignment 12] Is the bots' strategy a bit different in gg server from grade.sh file?

### ISSUE THREAD

**Issue by 1starJ** [kaist-cp/cs220#332]
### Related Issue

https://github.com/kaist-cp/cs220/issues/328

### Googling Result

None

### ChatGPT Result

None

### Your question here

I'm asking if the gg server code is a bit different from the grade.sh code, because I got 100% winning rate so far when I grade my code with grade.sh, but I failed to win when I submitted it to gg server. Is gg server grading code completely same to the grade.sh code? Or are some numerical values in gg server code altered from the grade.sh code?

**Comment by woojinnn** [comment]
No, they are identical. Some reasons for different result can be 1) workload imposed to grade server may differ by time 2) difference between your development server's thread scheduler and grade server, or etc. If you are quite confident with your result, you may submit multiple times. We grade only with the latest score.

**Comment by 1starJ** [comment]
Thanks. I was having an error because of print, not related to grading code.
