### ISSUE TITLE
SEB login to Google Not Working

### ISSUE THREAD

**Issue by Coll1ns-cult** [kaist-cp/cs220#334]
### Related Issue

..

### Googling Result

..

### ChatGPT Result

..

### Your question here

Hi, 

I tried to log in to google form for the final exam rehearsal seb file, but it just shows loading animation. I tried to login with different accounts, they weren't successful either.  I successfully logged in my friend's desktop though. I don't know exact cause of the problem, as I never ran this problem in the midterm exam. (My laptop is air mac m1)

**Comment by woojinnn** [comment]
It was common error in Mac. After you log in, press back button until you see the questions. Don't know the reason but it worked.
