### ISSUE TITLE
[Assignment 13] (Submission Problem at GG)

### ISSUE THREAD

**Issue by mzisyraf** [kaist-cp/cs220#338]
### Googling Result

No result

### ChatGPT Result

https://chat.openai.com/share/3bd06fa9-368a-455f-bb5e-f3a01f4a7328

### Your question here

![image](https://github.com/kaist-cp/cs220/assets/85271020/c85a73bd-ea22-45cd-89f6-4e681eec1cf3)
My code works fine with the test cases in the small_exercises_grade.rs and it passed all tests. But when I submit it says that it needs the assignment13/matmul.rs which is not an actual file

**Comment by tncks0121** [comment]
https://github.com/kaist-cp/cs220/commit/41b699cf1ae06a9bfdd9be369ec63f56a316f8e7 This should be relevant

**Comment by chochanwoo** [comment]
Is this issue currently solved? I think I am having same problem, but my friend has submitted without any problem. Sorry for asking twice.

**Comment by AnHaechan** [comment]
Please email your zip file for assignment13 to one of the TAs, before the deadline(11:59 pm today) if you're having this issue.
Sorry for the late response.

**Comment by woojinnn** [comment]
Can you pull the repository to the latest version and try it again? As @tncks0121 mentioned, I think this issue is solved.

**Comment by woojinnn** [comment]
@chochanwoo @mzisyraf

**Comment by chochanwoo** [comment]
I've solved the issue. Thanks so much!

**Comment by mzisyraf** [comment]
The issue is solved. Thank you very much
