### ISSUE TITLE
Final exam is graded, Claim schedule

### ISSUE THREAD

**Issue by woojinnn** [kaist-cp/cs220#339]
## Final exam score
Final exam is graded. You can check the result in https://gg.kaist.ac.kr/course/17/.
statistic    | number
-- | --
total | 110
average | 42.34939759
max | 97
min | 19
1st quartile | 30
median | 37
3rd quartile | 50.5

histogram: https://docs.google.com/spreadsheets/d/e/2PACX-1vQHufBWi_YFdy7p3MlTl4HsBEWUISa2twp91TYSa9-866LGGiD1ALuF330FhbDxMTtPlDS1_TNdc4CB/pubchart?oid=2009788784&format=interactive

## Claim session
* The claim session will be held next Tuesday, 12/19 15:30 at E3-4432.

**Comment by AnHaechan** [comment]
Hi all, the grades on gg was not properly recorded.
I will correct them by today.
Sorry for the inconvenience.

**Comment by AnHaechan** [comment]
The grades on gg were updated fixed for three students: 20180510, 20180637, 20180904.
There was an issue in the student id but it has been fixed.

**Comment by Rsln-M** [comment]
Is the claim period over? I have sent you an email with a claim previously since I was not in Korea and couldn't physically attend the claim session. I haven't received an answer yet.

**Comment by woojinnn** [comment]
@Rsln-M Can you send an email again? Cannot find in my mailbox.

**Comment by jirheee** [comment]
**Announcement**: There was a mistake while grading problems 4 and 5 in part 2. All the people who received 3 points received 6 and 8 points, respectively. So if you got 3 points for both 4 and 5, you got 6 and 8 points. It will not be updated in gg, but the updated scores will be used in the final grading.
