### ISSUE TITLE
[Assignment#2] Implementing both Copy and Clone? 

### ISSUE THREAD

**Issue by quanxi1** [kaist-cp/cs220#34]
#[derive(Debug, Clone, Copy)] 
I read Rust book and learned that this macro automatically generates the implements of Debug, Clone and Copy traits. 

I got that Vec2 and Mat2 types can be annotated as Copy because they purely consist of stack-only data(u64, which is Copy either),

But if a type has Copy trait, why does it need to be Clone? Because it is Copy, when an instance is assigned to another it will simply copy the data on stack, which is same behavior as .clone() method in this case I guess. Why both of them should be implemented?

**Comment by m-spitfire** [comment]
Short answer: See the [docs](https://doc.rust-lang.org/std/marker/trait.Copy.html).
Long answer: `Clone` is supertrait of `Copy`, so if a type implements `Copy`, it must also implement `Clone`.
`Clone` trait [source](https://doc.rust-lang.org/src/core/marker.rs.html#382-384)
```rust
pub trait Copy: Clone {
    // Empty.
}
```
See the docs for Copy and Clone or [this question](https://users.rust-lang.org/t/why-copy-need-clone-as-trait-bound/68852) for further information.

**Comment by quanxi1** [comment]
@m-spitfire Thanks it helped a lot
