### ISSUE TITLE
Final Exam Online Claim Request

### ISSUE THREAD

**Issue by jsk3040** [kaist-cp/cs220#340]
Hello, I post this issue because I won't be able to physically attend the claim session. Is there any way I could claim online?
Thanks

**Comment by woojinnn** [comment]
Can you send us an email with the problems you want to claim?

**Comment by Rsln-M** [comment]
Should other students also send an email @woojinnn ?

**Comment by AnHaechan** [comment]
@Rsln-M Please send mail to all of the TAs.
[Haechan An](https://cp.kaist.ac.kr/haechan.an), [Jungin Rhee](https://cp.kaist.ac.kr/jungin.rhee), [Woojin Lee](https://cp.kaist.ac.kr/woojin.lee).
You can pick a recipient and CC the other two.
Please send emails **by next Monday**.
