### ISSUE TITLE
[Assignment 3] Mastering common programming concepts (2/2) (due: 10/04, 23:59:59 (KST))

### ISSUE THREAD

**Issue by Lee-Janggun** [kaist-cp/cs220#346]
Re-learn the common programming concepts in Rust, part 2.

- Read the description [here](https://github.com/kaist-cp/cs220/blob/main/src/assignments/assignment03/mod.rs). You're going to fill out the `todo!()`s.

- You can grade your solution yourself by running `./scripts/grade.sh 3`.

- Submit your code [here](https://gg.kaist.ac.kr/assignment/133/).

- **IMPORTANT**: only the last submission counts. Please make sure the last submission succeeds.

- **IMPORTANT**: don't fork this repository. It'll be public!

**Comment by nailegg** [comment]
Can i modify derive of enumeration?

**Comment by Lee-Janggun** [comment]
@nailegg What derive do you want to add?

**Comment by eorb6502** [comment]
Can I disable some specific clippy lints??
I met 'if chain' error, so I want to disable clippy::comparison::chain

**Comment by Jaewookim08** [comment]
@eorb6502 Could you use a match-case statement instead? If you prefer using an if-else chain for specific reasons, please provide an explanation along with the code.
