### ISSUE TITLE
[Assignment 5] Program correctness and logic (due: 10/11, 23:59:59 (KST))

### ISSUE THREAD

**Issue by Lee-Janggun** [kaist-cp/cs220#348]
Prove simple programs in why3.

- Read the description [here](https://github.com/kaist-cp/cs220/tree/main/assets/why3/assignment05). You're going to fill out the `TODO!`s.

- Submit your code [here](https://gg.kaist.ac.kr/assignment/135/).

- **IMPORTANT**: only the last submission counts. Please make sure the last submission succeeds.

- **IMPORTANT**: don't fork this repository. It'll be public!

**Comment by Akais24** [comment]
The link in second line does not work.
It seems like to change with the changed path of `assets/why3`

**Comment by Lee-Janggun** [comment]
@Akais24 Thank you. I fixed the links.

**Comment by Jaewookim08** [comment]
For those using Why3 in the browser, ensure you run the verification with a sufficient number of steps. If the step count is too low, Why3 might not be able to verify the correct solution

![image](https://github.com/user-attachments/assets/5bf3fc02-0151-474e-8b4c-1a7932759b1a)

Related issue: https://github.com/kaist-cp/cs220/issues/379#issuecomment-2392827429
