### ISSUE TITLE
Permission denied (bublickey)

### ISSUE THREAD

**Issue by Amchoking** [kaist-cp/cs220#35]
When I type "git clone --origin upstream git@github.com:kaist-cp/cs220.git", I got an error.

Cloning into 'cs220'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

How can I fix it.

**Comment by minseongg** [comment]
You need to add a SSH key in your working environment to your GitHub account.

Could you please follow [this instruction](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account) and then try again?
