### ISSUE TITLE
[Assignment 7] Mastering advanced types (2/2) (due: 11/08, 23:59:59 (KST))

### ISSUE THREAD

**Issue by Lee-Janggun** [kaist-cp/cs220#350]
Get used to using advanced types in Rust, part 2.

- Read the description [here](https://github.com/kaist-cp/cs220/blob/main/src/assignments/assignment07/mod.rs). You're going to fill out the `todo!()`s.

- You can grade your solution yourself by running `./scripts/grade.sh 7`.

- Submit your code [here](https://gg.kaist.ac.kr/assignment/137/).

- **IMPORTANT**: only the last submission counts. Please make sure the last submission succeeds.

- **IMPORTANT**: don't fork this repository. It'll be public!

**Comment by kimsuhyeong** [comment]
```
vec![2, 4, 6, 8, 10],
 ...
range(Endpoint::Exclusive(1), Endpoint::Inclusive(10), 2).collect(),
range(Endpoint::Exclusive(1), Endpoint::Inclusive(11), 2).collect(),
 ...
range(Endpoint::Exclusive(1), Endpoint::Exclusive(11), 2).collect(),
range(Endpoint::Exclusive(1), Endpoint::Exclusive(12), 2).collect(),
```

I think this is not a major problem with solving the task, but the usage of concept **step** in ```RangeIter```, in ```small_exercises.rs``` is quite different compared to the ordinarily used one.

test cases say that the above iterators from range() must iterate from 2 to 10 with step 2.

However, if we start, for example, with left exclusive endpoint 1. doesn't the first iterating step denotes 3, not 2?

Maybe the test wants us to make **step** denote that ```RangeIter``` must go through **the multiples of the integer step** within the range? (which is not, usually?)

Sorry if the test is intended to be implemented in that way, thanks.
