### ISSUE TITLE
[Assignment 9] Iterators (1/2) (due: 11/29, 23:59:59 (KST))

### ISSUE THREAD

**Issue by Lee-Janggun** [kaist-cp/cs220#352]
Get used to using iterators in Rust, part 1.

- Read the description [here](https://github.com/kaist-cp/cs220/blob/main/src/assignments/assignment09/mod.rs). You're going to fill out the `todo!()`s.

- You can grade your solution yourself by running `./scripts/grade.sh 9`.

- Submit your code [here](https://gg.kaist.ac.kr/assignment/139/).

- **IMPORTANT**: only the last submission counts. Please make sure the last submission succeeds.

- **IMPORTANT**: don't fork this repository. It'll be public!

**Comment by Jaewookim08** [comment]
@add-ict Thanks! We have added the missing test. We have nullified the previous submissions, so make sure to submit them again.
