### ISSUE TITLE
[Assignment 13] Parallelism (due: 12/20, 23:59:59 (KST))

### ISSUE THREAD

**Issue by Lee-Janggun** [kaist-cp/cs220#356]
Get a taste of using parallelism in Rust.

- Read the description [here](https://github.com/kaist-cp/cs220/blob/main/src/assignments/assignment13/mod.rs). You're going to fill out the `todo!()`s.

- You can grade your solution yourself by running `./scripts/grade.sh 13`.

- Submit your code [here](https://gg.kaist.ac.kr/assignment/143/).

- **IMPORTANT**: only the last submission counts. Please make sure the last submission succeeds.

- **IMPORTANT**: don't fork this repository. It'll be public!

**Comment by seo-rii** [comment]
If submission fails with `mv: cannot stat '../submission/matmul.rs': No such file or directory` message, you should update `submit.sh` to latest version. You can manually copy [this content](https://github.com/kaist-cp/cs220/blob/main/scripts/submit.sh) into `scripts/submit.sh` or execute this command:

```sh
$ git remote add upstream https://github.com/kaist-cp/cs220.git
$ git pull upstream main --rebase --autostash
```

**Comment by Jaewookim08** [comment]
Local runs might fail due to limited CPU cores or just bad luck with scheduling. If your local tests fail but you're confident that your code is correct, try submitting it on GG.

**Comment by Perspectxve** [comment]
It worked! Thank you!
