### ISSUE TITLE
Question about resetting password.

### ISSUE THREAD

**Issue by s8ngyu** [kaist-cp/cs220#361]
### Googling Result

.

### ChatGPT Result

.

### Your question here

I'm not getting any email from authentik for resetting password.
My name is Soongyu Kwon and KAIST email is `master@kaist.ac.kr`.

Thank you.

**Comment by Lee-Janggun** [comment]
We'll look into it ASAp.

**Comment by D6-Byun** [comment]
저도 동일하게 password 리셋 시도 시 이메일을 받지 못하는 상태입니다.
id: 20170323
email: bighc0107@kaist.ac.kr입니다. 확인 부탁드립니다!

**Comment by Dyuk31** [comment]
I am also not getting any email when trying to reset password. My email is dyuk._.k@kaist.ac.kr and ID 20230950. I could not do the attendance check, is it excused this week? 
Thank you in advance.

**Comment by Lee-Janggun** [comment]
Can you all try again?

**Comment by Jaewookim08** [comment]
We have made some adjustments to fix the issue. Please try again and tell us if you still experience the same problem.

Also, you don't need to worry about the attendence checks not done for this week.

**Comment by s8ngyu** [comment]
@Lee-Janggun @Jaewookim08 Issue still remains.

**Comment by Jaewookim08** [comment]
@s8ngyu Could you tell us your student number?

**Comment by Junhajang-0562** [comment]
@Jaewookim08 아직도 비밀번호 리셋 이메일을 받지 못합니다. 장준하 / jh0302@kaist.ac.kr / 20190562 입니다.

**Comment by jeehoonkang** [comment]
Would you all please also check mails classified as spams?

**Comment by Junhajang-0562** [comment]
스팸메일함에도 받은 메일이 없습니다

**Comment by s8ngyu** [comment]
@Jaewookim08 It's 20230045.

**Comment by jeehoonkang** [comment]
If you registered for the course after Sep 1, I'll add you all in Saturday.

**Comment by D6-Byun** [comment]
Hello!
Although there is still an issue with the password reset, I guess it's happening because my course registration date is after September 1 in my case.
Thank you for checking, and I will try again after the date professor mentioned :)

**Comment by choi-wooyoung** [comment]
I sent email about same issue before, but I still can't receive email to reset password. I registered this class before Sep 1.

ID: 20190659
Email: wooyoung.choi@kaist.ac.kr

**Comment by Junhajang-0562** [comment]
I still have problem,,,
ID : 20190562
Email : jh0302@kaist.ac.kr

**Comment by Jaewookim08** [comment]
We're looking into it..

**Comment by jeehoonkang** [comment]
Would you all please try again?

**Comment by Junhajang-0562** [comment]
I success to reset password and now be able to login gg, thank you

**Comment by choi-wooyoung** [comment]
It's still not working...

**Comment by s8ngyu** [comment]
It's been fixed for me. thanks.

**Comment by D6-Byun** [comment]
I successfully changed my password. Thanks!

**Comment by Jaewookim08** [comment]
I'll leave this thread open until everyone's able to login.

**Comment by Jaewookim08** [comment]
I'll leave this thread open until everyone's able to login.

**Comment by JaggerST** [comment]
Hello! 
I also have the problem of not beeing able to reset my password. I don't have an @kaist.ac email address, my mail is jakob.m.steinke@gmail.com
 My student ID is 20246492
Thanks for helping

**Comment by jeehoonkang** [comment]
@JaggerST I believe by now you can have an @kaist.ac.kr address. Would you please create it and let me know the address? For security reasons, gg/cloud.kaist.ac.kr allows only @kaist.ac.kr addresses.

**Comment by JaggerST** [comment]
@jeehoonkang I have a @kaist.ac.kr address now and it works, thank you!

**Comment by Jaewookim08** [comment]
@choi-wooyoung is it still not working for you?

**Comment by choi-wooyoung** [comment]
> @choi-wooyoung is it still not working for you?

yes... It still not working

**Comment by jeehoonkang** [comment]
@choi-wooyoung try with your email address uy0417@kaist.ac.kr

**Comment by choi-wooyoung** [comment]
> @choi-wooyoung try with your email address [uy0417@kaist.ac.kr](mailto:uy0417@kaist.ac.kr)

That's the email I was using before. My email is now `wooyoung.choi@kaist.ac.kr` and there is no way to access my old email

**Comment by jeehoonkang** [comment]
@choi-wooyoung try again with wooyoung.choi@kaist.ac.kr

**Comment by choi-wooyoung** [comment]
> @choi-wooyoung try again with [wooyoung.choi@kaist.ac.kr](mailto:wooyoung.choi@kaist.ac.kr)

It works. thank you!!
