### ISSUE TITLE
[Assignment 1] (Problem; auto grading does not work)

### ISSUE THREAD

**Issue by Jeong-jin-Han** [kaist-cp/cs220#362]
Description
I encountered an issue while trying to run the grading script on the server provided for the assignment. The script fails with the following error message:

./scripts/grade-utils.sh: line 10: rustup: command not found

Steps to Reproduce:

Run the following command in the terminal:

./scripts/grade.sh 01
The script fails, indicating that rustup is not installed or not found.

What I Tried:

I attempted to check the installation of rustc and cargo using:

rustc -V
cargo -V
Both commands returned errors:

rustc: command not found
cargo: command not found

I attempted to run sudo apt update to resolve the issue, but my user account does not have sudo privileges on the server.

Environment:
![image](https://github.com/user-attachments/assets/06192174-bc46-4021-b1c6-e6a1238c2902)

Related Links:

I found a related issue on the Rustup GitHub repository: [GitHub Issue #686](https://github.com/rust-lang/rustup/issues/686)
ChatGPT suggested checking the installation of rustc and cargo, and running sudo apt update.
Expected Behavior
The grading script should run successfully without encountering the rustup: command not found error.

Actual Behavior
The grading script fails due to the missing rustup command.

Additional Information
My account does not have sudo privileges, so I am unable to install rustup or perform a system update.
I am using the server resources provided by the course.

**Comment by kingdoctor123** [comment]
1. Did you try `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh` ? I just confirmed that this simply works.
2. In fact, you can do `sudo ...` on the development server. So if you want, you can run `sudo apt update` or something like this.

**Comment by Jeong-jin-Han** [comment]
Sorry, I misunderstood. When I write sudo -V, terminal show to me write down the password, so I guess that I can not use the sudo ....

I try the "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh" then rust is installed.
Thank you!!
