### ISSUE TITLE
[Assignment 01] Problem with run submit.sh. "zip: command not found"

### ISSUE THREAD

**Issue by Akais24** [kaist-cp/cs220#363]
### Related Issue

https://github.com/kaist-cp/cs220/issues/250

### Googling Result

https://www.tecmint.com/install-zip-and-unzip-in-linux/

### ChatGPT Result

https://chatgpt.com/share/5b1fec2e-22bb-406d-933a-bca78c595564

### Your question here

I'm having problem on executing `scripts/submit.sh` on development server.
```
./scripts/submit.sh: line 21: zip: command not found
```
It seems like zip package is not installed in the environment that i created in coder with cs220 template.
Even though I create a new workspace in coder, zip package didn't exist.

Did I miss something? Or do I have to install it manually by `sudo apt install zip`?

**Comment by Ahmadsm2005** [comment]
What I did was to install it manually using `sudo apt install zip` and it worked well!

**Comment by blackkarn** [comment]
I've gone through same issue.
I am on windows,

I just installed chocolatey and used 

choco install zip 

on windows powershell, solving the problem.
Hope this helps.

**Comment by Akais24** [comment]
I understand about the problem and I think I know about how to solve it (Actually, i don't having problem in my local environment)
I experienced it on `development server`, and I feel strange about the submission script wasn't running on the server prepared for the submission.
So I feel like I miss something. Or maybe missing in cs220 template.

So I made issue and ask about "Did I miss something?"

**Comment by Jaewookim08** [comment]
Thanks for reporting the issue! We'll add the missing packages to the server template later, but we don't have any immediate plans. I'm sorry for the inconvenience.

Until the template is fixed, please use `sudo apt install` commands to install the missing packages.

**Comment by Jaewookim08** [comment]
I'll leave this issue open for the people with the same problem.

**Comment by Jaewookim08** [comment]
We have added zip to the cs220 template. You can click the 'update workspace' button to work with the updated template.

You would still have to install `rustup` by yourself, either by (1) running `sudo apt install rustup`, or by (2) running `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`. The latter allows for more customized installation.
