### ISSUE TITLE
[Assignment #5] Error when submitting Assignment 5?

### ISSUE THREAD

**Issue by Ahmadsm2005** [kaist-cp/cs220#364]
When attempting to submit my assignment 5 solution, the server attempts to install some packages which then fails and does not grade my solution.

Can it please be fixed? I have attached a screenshot below:

![image](https://github.com/user-attachments/assets/cafd18b2-d535-4c43-a99e-7f69ce0fbbbc)

**Comment by Jaewookim08** [comment]
I'll be looking into it.

**Comment by Lee-Janggun** [comment]
See #365. We'll fix it ASAP.

**Comment by Lee-Janggun** [comment]
We fixed submission for assignment 5. Can you try again?

**Comment by Ahmadsm2005** [comment]
Thank you so much! It now works well! Even faster than I expected and the time limit is much more generous than I thought!
