### ISSUE TITLE
Nullification of Assignment Submissions and Current Issues.

### ISSUE THREAD

**Issue by Lee-Janggun** [kaist-cp/cs220#365]
TL;DR

* **All previous assignment submissions are nullified**. Please re-submit your assignments.
* Assignment 13 is having some troubles, and we are working on a fix.

* Nuliffication:
  * We have noticed an error is the grading script at gg, invalidating the current submissions.
  * We have fixed it, and also nullified all previous submissions. Please re-submit your assignments.

* Assignment 13:
  * We are experiencing some issues in the grading server for assignment 13.
  * We are working on a fix, but until then, gg won't be able to give scores even for correct solutions.

**Comment by Lee-Janggun** [comment]
Assignment 5 is fixed.

**Comment by Jaewookim08** [comment]
We have corrected assignment 13. I verified that all current submissions receive max scores in both the original and corrected versions, so nullification won't be necessary. Closing the issue.
