### ISSUE TITLE
9/11 출석에 관련한 문의

### ISSUE THREAD

**Issue by zzupi06** [kaist-cp/cs220#368]
안녕하세요 cs220 과목을 수강하고 있는 임준영 입니다. 금일 출석을 위해 gg에 접속하여 출석 체크 정답을 입력했는데, 오답이라는 문구가 뜨며 server error 500 오류가 발생하여 출석이 완료 된 건지 확인하지 못하여 문의 드립니다. 제 학번은 20240619이고, email은 zzupi06@kaist.ac.kr입니다.

**Comment by kingdoctor123** [comment]
Hello, I confirmed that you have correctly submitted the answer for today(9/11)'s quiz. So you don't need to worry about it.
