### ISSUE TITLE
It looks like gg isn't working

### ISSUE THREAD

**Issue by daehwan5024** [kaist-cp/cs220#369]
### Googling Result

.

### ChatGPT Result

.

### Your question here

When submitting a homework to gg.kaist.ac.kr, it only shows 'waiting' in the VALID? column, and isn't actually grading the submitted file.
Is it a problem caused by my machine, or a problem with gg?

**Comment by killerwhalee** [comment]
I'm experiencing the same problem, so maybe it's the problem with gg.
![image](https://github.com/user-attachments/assets/2da26bfc-057f-467d-a897-de5ff62ef563)

**Comment by Jaewookim08** [comment]
It's definitely a problem with gg. We're looking into it.

**Comment by jeehoonkang** [comment]
I just rebooted the gg server. would you please try again?

**Comment by daehwan5024** [comment]
I think it's still not working

![image](https://github.com/user-attachments/assets/215c2454-2cf3-4f10-905c-c36cd50aff2e)

**Comment by jeehoonkang** [comment]
sorry, I believe it's now resolved. can you try again?

**Comment by daehwan5024** [comment]
It's now working. Thanks
