### ISSUE TITLE
[Attendance Check] 안녕하세요, 출석 체크 시작 일자와 관련해 문의드립니다.

### ISSUE THREAD

**Issue by jihwan01** [kaist-cp/cs220#371]
안녕하세요, CS220 과목을 수강하고 있는 20190395 오지환입니다.

이전 9/9 수업 때 gg 접속 관련하여 아직 이슈가 있는 학생들로 인해 출석 체크 시작일자가 미뤄진다고 들었던 것으로 기억하고 있습니다. 
그런데 gg에 들어가보면 9/9 출석 체크 퀴즈 역시 올라와 있는 상황이라 혹여나 제가 잘 못 들었던 것인지를 여쭙고자 질문드립니다.
9/11부터 모든 출석 체크 퀴즈를 푼다면 출석에 만점을 받을 수 있는 것이 맞나요?

글 읽어주셔서 감사합니다.

**Comment by jeehoonkang** [comment]
attendance check for 9/9 (and before) will be ignored.

**Comment by jihwan01** [comment]
감사합니다.
