### ISSUE TITLE
[Assignment 4] Is it okay to make and use a function other than filling in the todo?

### ISSUE THREAD

**Issue by Junhajang-0562** [kaist-cp/cs220#372]
### Related Issue

.

### Googling Result

.

### ChatGPT Result

.

### Your question here

I wonder if the only part I can write in the assignment is todo. I made and used 2 more functions to use in the parse_command function while working on the 4th assignment, is it okay to do the assignment in this way?

**Comment by Jaewookim08** [comment]
Yes it's okay to define and use helper functions, unless the assignment explictly tell you to only modify the target line (ex. assignment 5).

**Comment by Jaewookim08** [comment]
Yes it's okay to define and use helper functions, unless the assignment explictly tell you to only modify the target line (ex. assignment 5).
