### ISSUE TITLE
[Attendance] 09/11 출석 관련 질문

### ISSUE THREAD

**Issue by choi-wooyoung** [kaist-cp/cs220#373]
안녕하세요, 20190659 최우영입니다.

이전 Closed 된 이슈 (#371, #368)에서 09/11 출석이 포함되는 것을 확인하였습니다.

하지만 저는 비밀번호 리셋 문제(#361)로 인해 09/15 이후 gg에 접속이 가능해졌습니다.

혹시 이런 경우에는 출석이 어떻게 처리되는 걸까요?

**Comment by Lee-Janggun** [comment]
출석 처리시 고려하도록 하겠습니다.
