### ISSUE TITLE
[Assignment 1] Trivial problem in /scripts/submit.sh

### ISSUE THREAD

**Issue by GianniLee** [kaist-cp/cs220#374]
### Googling Result

https://stackoverflow.com/questions/8789729/how-to-zero-pad-a-sequence-of-integers-in-bash-so-that-all-have-the-same-width

### ChatGPT Result

https://chatgpt.com/share/66f500ea-15c0-8007-a509-22fa6bdf545b

### Your question here

When I run submit.sh, it cannot find the assignment01 directory properly since it tries to find `./scripts/../src/assignments/assignment1`, not assignment**01**, although in the code it goes through `for i in {01..13}`.
I tried to find the reason why it works like this in my environment, so can I manually modify `submit.sh` so that it can find properly?

**Comment by kingdoctor123** [comment]
Yes. `submit.sh` is provided for convenience, so changing the file will not affect the grading in gg, provided that the submitted zip file is made correctly.
