### ISSUE TITLE
[Assignment #4] Pest version deprecated

### ISSUE THREAD

**Issue by Perspectxve** [kaist-cp/cs220#376]
### Related Issue

.

### Googling Result

.

### ChatGPT Result

.

### Your question here

For assignment 4, the comment in parser.rs states

"For associativity of each operator, please follow [here](https://docs.rs/pest/latest/pest/prec_climber/struct.PrecClimber.html#examples)." and the prec pest::prec_climber is used, but this is a deprecated structure. Pratt Parser is the currently used construct. Can we use this instead?

**Comment by Lee-Janggun** [comment]
Yes, you can use it, as long as it passes on gg.
