### ISSUE TITLE
[Assignment 5] How can I found the counterexample of my code?

### ISSUE THREAD

**Issue by leedonghyun222** [kaist-cp/cs220#377]
### Googling Result

https://www.why3.org/doc/manpages.html

### ChatGPT Result

https://chatgpt.com/share/66fa4526-67a4-8002-9efd-a10b23288bc6

### Your question here

![image](https://github.com/user-attachments/assets/6dd74cdf-aa10-4b13-a17e-6e5ef2a04173)

I ran my code on Why3's online platform(https://www.why3.org/try/), but I encountered some issues during the proof process. I believe the problem arises because there is a counterexample in my code, so I tried to find it.

I found that the command "why3 prove --ce <your_file.mlw>" can generate counterexamples, so I downloaded Why3 and ran the command locally. However, the issue is that my code is marked as Valid when I run it locally! Initially, I thought this was due to the difference in solvers (since I used the Z3 solver at first), so I checked the solver used on the Why3 online platform and found that it uses Alt-Ergo. I don’t know the exact version, so I used Alt-Ergo 2.6.0, but with this solver, my code was also marked as Valid.

I'm not sure why my code is marked invalid on the online platform, and I would appreciate your help in finding the issue.

Additionally, I noticed that the Why3 online platform doesn’t always prove my code on the first try. I have to click the "Magic Wand" button several times before it proves successfully. Could you also help me understand why this happens?

**Comment by Lee-Janggun** [comment]
Does your code pass in gg?

**Comment by leedonghyun222** [comment]
What does it mean to pass gg? Isn't gg supposed to only tell me if an assignment was submitted successfully?

**Comment by Lee-Janggun** [comment]
@leedonghyun222 If you click on log, you will be able to see the log of your submission, which should tell you if you failed or passed the assignment.

**Comment by leedonghyun222** [comment]
Thank you!
