### ISSUE TITLE
[Assignment #5] finding good loop invariant

### ISSUE THREAD

**Issue by brongs2** [kaist-cp/cs220#379]
### Googling Result

https://stackoverflow.com/questions/2935295/what-is-the-best-way-of-determining-a-loop-invariant

### ChatGPT Result

https://chatgpt.com/c/66fe4982-506c-8003-abf7-9f09b1ae39bb

### Your question here

To find the loop invariant of pascal's triangle
I can observe that elements of new_row is same to comb r k, but this invariant does not pass the test
loop invariant preservation error since my loop invariant is not good invariant
can anyone help what I missing?
thank you

**Comment by brongs2** [comment]
thank for your comment
by Array make r+1 1, end edge and first edge satisfy the condition, and by the loop context, from first to some point or end point, new_row satisfy the condition.
Do I need to specify the pascal's triangle's charteristic in loop invariant? 
Thank you

**Comment by Jaewookim08** [comment]
I'll have to check, but I'm fairly certain you don't need to since the lemma should already be in the library.

**Comment by brongs2** [comment]
to induce row[c] =  r-1Cc,
suppose row[c] = r-1Cc if new_row[0] =rC0 , new_row[r] = rCr, if 1 <= i < c, then new_row[i] = row[i] + row[i-1], then by lemma, new_row[i] =  = r-1Ci + r-1Ci-1 = rCi, so I expect that row[c] = new_row[c] = rCc for all c
then why the machine cannot induce row[c] = rCc?

**Comment by Jaewookim08** [comment]
The issue was troubleshot during office hours. It was caused by using too few steps when working with www.why3.org/try/.

For all students, try using 1,000 to 5,000 steps if Why3 in the browser is not working as expected. I'll add warnings in the instructions.
