### ISSUE TITLE
[Assignment All] About the grading policy

### ISSUE THREAD

**Issue by jihwan01** [kaist-cp/cs220#380]
### Related Issue

.

### Googling Result

.

### ChatGPT Result

.

### Your question here

Hello,

If we submit the files for each assignment on GG and they are all marked as valid, can we assume that we have received full marks for the assignment? Or are there hidden cases or regrading processes involved?

Thank you

**Comment by brongs2** [comment]
you can check the log and find score

**Comment by jihwan01** [comment]
> you can check the log and find score

Yes, what I want to ask is whether the score is the final score, or if there will be regrading through hidden cases or other means.

Thank you

**Comment by Jaewookim08** [comment]
- The 'Yes' under 'Valid' indicates that your solution has been successfully built and tested. It is not related to your score.
- To check the score, please refer to the bottom of the log.
- There are no hidden test cases. The score displayed in the log is your final score.

**Comment by jihwan01** [comment]
Thank you for your answer :)
