### ISSUE TITLE
[Assignment #1] Is this correctly submitted?

### ISSUE THREAD

**Issue by daehwan5024** [kaist-cp/cs220#383]
### Related Issue

.

### Googling Result

.

### ChatGPT Result

 .

### Your question here

![image](https://github.com/user-attachments/assets/9dbdf0ee-782e-4f80-95f0-89dc986ec6bf)
Do I get graded using the one that has Yes on the VALID? column or is it a wrong submission that will get 0 points?
The submitions that has waiting on the VALID? column was due to error with gg

**Comment by kingdoctor123** [comment]
All previous submissions will be ignored, and only the latest submission will be considered. So, if your latest submission (id=26664) does not pass the test, then you will get 0 points even though your previous submission (id=26368) has valid=true.

**Comment by daehwan5024** [comment]
The latest submission has the exact same file as the previous three submission.
Will I get a score same as the one with ID=26368?

**Comment by kingdoctor123** [comment]
@daehwan5024 Can you send us (me: sunho.park@cp.kaist.ac.kr, head TA: janggun.lee@cp.kaist.ac.kr) your student ID? I will check your submission and let you know.
