### ISSUE TITLE
[Assignment #4] Can we not use PEST?

### ISSUE THREAD

**Issue by Ahmadsm2005** [kaist-cp/cs220#384]
### Related Issue

NA

### Googling Result

NA

### ChatGPT Result

NA

### Your question here

Is it allowed not to use PEST and implement everything from scratch? I found it much easier especially that PEST is not well documented.. I already submitted and got full score by implementing everything from scratch.

**Comment by Jaewookim08** [comment]
You are allowed to use your own implementation if it passes on GG.

**Comment by Ahmadsm2005** [comment]
Thank you!
