### ISSUE TITLE
[Assignment 1] 계속 waiting만 떠있습니다

### ISSUE THREAD

**Issue by joon0725** [kaist-cp/cs220#386]
### Googling Result

.

### ChatGPT Result

.

### Your question here

![Screenshot_20241007_010916_Samsung Internet](https://github.com/user-attachments/assets/d0db727e-0ad9-4e1e-8773-6159e00ca067)

9월 13일에 assignment 1,2,3을 모두 제출했는데 waiting..으로 되어 있길래 재출 기한 당일 한번에 채점되는줄 알고 기다렸는데 아직까지도 waiting 상태입니다.

**Comment by Jaewookim08** [comment]
It's due to https://github.com/kaist-cp/cs220/issues/369

Can you give me your student ID?

**Comment by joon0725** [comment]
20240468 입니다

**Comment by Jaewookim08** [comment]
I will make sure you receive your score properly. However, please note that I won’t be able to make exceptions like this in the future, so be sure to check the outputs after you submit.

**Comment by Jaewookim08** [comment]
@joon0725   I checked, and your submission was not saved on the server. Please email us your submissions for assignments 1-3 and evidence showing they were completed on time. If you have a private Git repository, you can share it as proof by inviting me to the repo.

**Comment by Jaewookim08** [comment]
The student seems to have dropped the course. Closing the issue.
