### ISSUE TITLE
[Assignment 6] Due date of Assignment 6 is October 11 or 18?

### ISSUE THREAD

**Issue by soominsuh** [kaist-cp/cs220#387]
### Googling Result

N/A

### ChatGPT Result

N/A

### Your question here

I have question about due date of assignment 6.
In slide book, it says deadline  is 10/18 (Fri) 23:59:59 (KST).
In gg, it says deadline is 10/11(Fri) 23:59:59(KST).
When is correct?

**Comment by Jaewookim08** [comment]
It's 10/18. Sorry for the late response. We have corrected the deadlines in gg and in #349.
