### ISSUE TITLE
[Assignment 3] gg에서 valid?:no 가 무엇을 의미하나요?

### ISSUE THREAD

**Issue by ShinDongHeon** [kaist-cp/cs220#389]
### Related Issue

.

### Googling Result

.

### ChatGPT Result

.

### Your question here

지난주에 제출한 과제3번에서 valid? 란에 no 라고 적혀있는 것을 오늘 확인하였습니다.
제 노트북에서 실행했을 때 your score: 3/3이라고 뜨는것을 본 후 바로 ./scripts/submit.sh 한 후 제출했기에
굳이 저 항목이 평가되고 있는 동안 체크하지 않고 마무리했습니다.
방금 invalid? : no 를 확인하였고 다시 다운받아서 제 pc에서 돌려보니 your score:3/3이 나오는데
저것이 왜 저렇게 표시되고 있는지 모르겠습니다

**Comment by Jaewookim08** [comment]
What does the log say in gg?

**Comment by ShinDongHeon** [comment]
it says
Cloning into 'cs220'...
fatal: unable to access 'https://github.com/kaist-cp/cs220.git/': Failed to connect to github.com port 443 after 136439 ms: Couldn't connect to server

**Comment by Jaewookim08** [comment]
I suppose it was a temporary network issue. I'm not sure if I can assign scores for this situation; I'll need to discuss it with the other TAs. I'll let you know our decision.

By the way, you should always check the GG results, as they may differ from your local run for various reasons.

**Comment by Jaewookim08** [comment]
Could you provided your student id?

**Comment by ShinDongHeon** [comment]
its 20190339 thank you

**Comment by Jaewookim08** [comment]
@ShinDongHeon We have decided to provide scores for this case as a one-time exception, but this will not be allowed for future assignments.
However, I noticed that your submission is not saved on the server. Could you please follow the instructions provided in https://github.com/kaist-cp/cs220/issues/386#issuecomment-240440348 for Assignment 3?

**Comment by ShinDongHeon** [comment]
Thanks but my visual code studio can't be the evidence that i finished this assignment before duedate because i double checked my own code when i decided to post a question on github. I think it will be better to download my code submitted on gg.kaist infront of you, then email it. I can go to your lab and be checked or after tomorrow's session does it sounds okay?

**Comment by Lee-Janggun** [comment]
@ShinDongHeon yes, please come to the class tomorrow, and we can look at it together.

**Comment by ShinDongHeon** [comment]
Okay thanks!
