### ISSUE TITLE
How can I download file_assignment 3 

### ISSUE THREAD

**Issue by albinjeon** [kaist-cp/cs220#39]
How can I download files related to assignment3 form the git without changing my files?

**Comment by m-spitfire** [comment]
Hello. First commit your changes on your local repo:
```sh
$ git add -A
$ git commit -m "some message"
```
Then you need to [sync with upstream](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork#syncing-a-fork-branch-from-the-command-line):
```sh
$ git fetch upstream
$ git merge upstream/main
```
In this example the remote branch's name was `upstream`. If you have followed the instructions on the README that would be the case for you. But the remote's name could be different so check it with `git remote -v`. 
Second thing: There could be merge conflicts, when you merge the upstream branch, you can follow the [instructions here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line) to resolve them.
