### ISSUE TITLE
[Assignment 5] (Late Submission?)

### ISSUE THREAD

**Issue by dbekzhan** [kaist-cp/cs220#393]
### Related Issue

no 

### Googling Result

no 

### ChatGPT Result

no 

### Your question here

Hello, I cannot find information about the late submission policy. Are we allowed to submit late? If so, what is the penalty system?

**Comment by Jaewookim08** [comment]
We don't allow late submissions. I believe this has been announced in the class.

**Comment by dbekzhan** [comment]
Thank you for reminding me! I just wanted to confirm
