### ISSUE TITLE
Exam rehearsal on October 16th (Wed) in the lecture room

### ISSUE THREAD

**Issue by Lee-Janggun** [kaist-cp/cs220#394]
As previously announced https://github.com/kaist-cp/cs220/issues/382, **tomorrow's class will involve a rehearsal session**. The primary objective of this session is to familiarize ourselves with the test environment using the Safe Exam Browser (SEB) tool. Your active participation in tomorrow's rehearsal is strongly encouraged to help prevent any potential penalties related to the test environment.

In preparation for the class, we kindly request that you **bring your laptop, equipped with the SEB software, in a fully charged state.**

---

We are going to explain below stuffs in the class tomorrow:
1. Download [cs220_rehearsal.zip](https://github.com/user-attachments/files/17395270/cs220_rehearsal.zip) and open `cs220_rehearsal_part1`
    1. Password for sample configuration file is cs220.
1. Read the [tutorial slides](https://docs.google.com/presentation/d/1M8N8HTh7St-hfjuegpyOefxEXJdbdvv4Xr4wK7FXEn8/edit#slide=id.g282156dfff9_0_10) for how to use SEB.
1. Check whether your answer is correctly recorded in the sheet: [Part1 responses](https://docs.google.com/spreadsheets/d/1qFVYRMxAuzfXEHccZxFKJ1St7b04Vq6CxkSOBQAAy1o/edit?usp=sharing)
1. Open `cs220_rehearsal_part2`
1. Check whether your answer is correctly recorded in the sheet: [Part2 responses](https://docs.google.com/spreadsheets/d/1ClVRYYJEfxZZEwIt59nA_RtULWNzfZcLmwHPKTJRbSg/edit?usp=sharing)

**Comment by Lee-Janggun** [comment]
I'll also have a free Q&A session after the rehearsal, if time permits.

**Comment by Lee-Janggun** [comment]
Common issues

* need phone for 2fa: yes use it.
* In mac, can't go pass white screen during login: press 'previous page' in top left.
* can't open link: try cmd/ctrl + click
* can't copy and paste: try drag and drop

**Comment by Jaewookim08** [comment]
- You should use cs220_rehearsal.zip in this issue, not the cs220_example1.zip file in #382

**Comment by Lee-Janggun** [comment]
We updated the seb files https://github.com/kaist-cp/cs220/issues/403.
