### ISSUE TITLE
Why3 task for lecture tomorrow 

### ISSUE THREAD

**Issue by jakobsteinke** [kaist-cp/cs220#395]
### Related Issue

-

### Googling Result

-

### ChatGPT Result

-

### Your question here

Hello, is it possible to show how to solve these 2 problems in the pre midterm lecture tomorrow?
![image](https://github.com/user-attachments/assets/99a5b5eb-ea52-4d55-bc2a-272fb4b765f2)
![image](https://github.com/user-attachments/assets/f09b9661-488a-42df-9521-0dc60b9ef139)
Thank you in advance!

**Comment by Jaewookim08** [comment]
Sure! Feel free to ask us during the Q&A session.
