### ISSUE TITLE
[Assignment 06] About unused ~ of type ~ in semiring

### ISSUE THREAD

**Issue by ShinDongHeon** [kaist-cp/cs220#396]
### Related Issue

d

### Googling Result

d

### ChatGPT Result

only says Unused variable을 무시: #[allow(unused_variables)] sth like this

### Your question here

In implementing semilog, i declared another hashmap for polynomial.coefficient/cloned original coefficients and did modifications on that hashmap. Returning Polynomial { hashmap } for the output. but compiler says hashmap is unused. What should i do in this case?

**Comment by Jaewookim08** [comment]
I can't fully interpret your situation, but compilers are rarely wrong. If a compiler says a variable is unused, then it is unused, and you should remove it.
