### ISSUE TITLE
Announcement on Assignment Grading.

### ISSUE THREAD

**Issue by Jaewookim08** [kaist-cp/cs220#397]
For Assignments 1-5, we have assigned scores to all valid submissions, even if they were not automatically graded due to unexpected server errors (#383, #386, #389). If you submitted any of these assignments but did not receive a score because of an error, please report the issue by October 22.

**Only the log of your most recent submission will be used for evaluation for future assignments, with no exceptions.** Please carefully look at the **GG log** after submission to ensure the recorded scores match your expectations. Note that a "yes" under "Valid" only indicates that the tests were executed; it does not represent the total score.

**Comment by dbekzhan** [comment]
Where can we see the graded scores?

**Comment by ICubE-** [comment]
If the VALID? column says yes, then you can open the link in the LOG column to check your score at the end of the file.
