### ISSUE TITLE
[Rehearsal] code server seems not having cargo

### ISSUE THREAD

**Issue by killerwhalee** [kaist-cp/cs220#398]
I created my workspace in code page using `CS220` docker image.
However, this docker image seems not having cargo installed.
Can you check this issue? Thank you.

**Comment by Lee-Janggun** [comment]
That is very strange, does creating a fresh workspace instance solve the issue?

**Comment by killerwhalee** [comment]
Problem resolved. It seems only `cs220_example1.seb` does not contain cargo inside it.
I checked file for rehearsal and cargo was configured correctly.
Sorry for the inconvenience🥺
