### ISSUE TITLE
[Midterm exam rehearsal] Unable to acces code-server in coder

### ISSUE THREAD

**Issue by Akais24** [kaist-cp/cs220#399]
### Googling Result

.

### ChatGPT Result

.

### Your question here

When I use SEB, it does not open the code-server in Coder. Only white page loaded

**Comment by edoszhan** [comment]
I had similar issue, so I updated to the latest version of macOS Sequoia and it solved the error for me.

**Comment by Akais24** [comment]
> * Is your OS updated to the most recent OS? (see [[Midterm exam rehearsal] Unable to acces code-server in coder #399 (comment)](https://github.com/kaist-cp/cs220/issues/399#issuecomment-2416415076))

Do I have to update my OS to recent OS? I really want to avoid update my OS due to some compatibility issues...
Even I have to upgrade my OS, Sequoia seems to be too dangerous because it have been only 1 months after release

> * Does the same problem persist with the new seb rehearsal files ([Updated Rehearsal SEB files for Midterm practice #403](https://github.com/kaist-cp/cs220/issues/403))?

I still have same problems after using the updated SEB. Also, looping in a white screen during login still exists

**Comment by Lee-Janggun** [comment]
If you don't update your OS, we really can't help you. We don't have access to a mac with an old OS that can reproduce your issue.

**Comment by Akais24** [comment]
Then, can I know about the minimum version of OS that recommend to upgrade?
Actually, I was using Monterey now...

**Comment by Lee-Janggun** [comment]
We recommend the latest OS.

**Comment by Akais24** [comment]
After upgrading to Ventura, it works.
Thanks for help
