### ISSUE TITLE
[Homework #2] About Lyrics problem

### ISSUE THREAD

**Issue by YoonseokJeong** [kaist-cp/cs220#40]
/// Writes down the lyrics of "twelve days of christmas".
///
/// Hint: Google the song title for lyrics and look at the test code for the expected result.

Above is the instruction of the lyrics problem of homework #2 and I can't figure out what this problem is intended for.

What does this problem ask us to implement? Just copy and paste is enough?(Surely I don't think so)

I think we need more specifications on this problem.

**Comment by jeehoonkang** [comment]
- Copy-and-paste will give you the full mark...
- Though I wish you could think of the underlying structure of the lyrics and computationally represent it using loops.
