### ISSUE TITLE
[Rehearsal] about sign in and open links in seb

### ISSUE THREAD

**Issue by gyh0507** [kaist-cp/cs220#401]
### Googling Result

.

### ChatGPT Result

.

### Your question here

When I sign in the google forms, error message "access to "" is not allowed according to the current configuration" occurs. 
Also when I try to open the links in the google forms, page where url is about:blank#blocked opens.
![KakaoTalk_20241016_155128599](https://github.com/user-attachments/assets/90609f58-e4bd-4389-a739-f51a4e27faa7)
![KakaoTalk_20241016_155128599_01](https://github.com/user-attachments/assets/2cbce384-e2fd-40d5-8050-60ba1632c394)

**Comment by Lee-Janggun** [comment]
1. Are you using the seb files uploaded to https://github.com/kaist-cp/cs220/issues/394, not https://github.com/kaist-cp/cs220/issues/382?
2. What OS are you using?

**Comment by gyh0507** [comment]
1. I use cs220_rehearsal file
2. I use windows

**Comment by Lee-Janggun** [comment]
1. Can you try out the new SEB files in https://github.com/kaist-cp/cs220/issues/403?
2. Are you using the most recent SEB version?

**Comment by gyh0507** [comment]
Now it works.
Thank you
