### ISSUE TITLE
Updated Rehearsal SEB files for Midterm practice

### ISSUE THREAD

**Issue by Lee-Janggun** [kaist-cp/cs220#403]
Hi, we have updated the seb files based on the feedback from the practice session below. The new seb files should hopefully:

* For windows, be able to copy-and-paste between google from and vs-code desktop well.
* For mac, not loop in a white screen during login.

Zipped seb files: [cs220_rehearsal.zip](https://github.com/user-attachments/files/17395270/cs220_rehearsal.zip)
 
 Please try out the new seb files, and tell us if there are any problems.
 
 Also, make sure you are using the most recent SEB version and OS version.

**Comment by Jaewookim08** [comment]
If you are unable to paste in VSCode, try going to the settings and disabling the 'Paste as' feature. This should also help resolve the issue of not being able to copy comments.

**Comment by Jaiwooyu** [comment]
I'm Mac user, and there is still loop in a white screen during login.

**Comment by Lee-Janggun** [comment]
@Jaiwooyu 

1. Are you using a recent OS version? I have only tested it on Sequoia.
2. Does pressing the back button on the top left solve the issue?

**Comment by brongs2** [comment]
I tested seb in Mac os but it does not work yet
my mac is sequoia 15.0.1 which is latest

**Comment by Lee-Janggun** [comment]
@brongs2 what is your exact problem?

**Comment by brongs2** [comment]
> @brongs2 what is your exact problem?

when I log in to my google account 
![1-b0743935](https://github.com/user-attachments/assets/55221599-52b7-4f01-968b-f9e2b9ebbdff)
this screen repeated

**Comment by Lee-Janggun** [comment]
@brongs2 Does clicking on the "previous tab" button on the top left help?

**Comment by brongs2** [comment]
> @brongs2 Does clicking on the "previous tab" button on the top left help?

thank you I can login but cannot access gg in the google form how can I access the gg link? thank you

**Comment by Lee-Janggun** [comment]
@brongs2 If just clicking on the link doesn't work, try cmd + click.
