### ISSUE TITLE
Question regarding definition of loop invariant preservation

### ISSUE THREAD

**Issue by jakobsteinke** [kaist-cp/cs220#405]
### Related Issue

-

### Googling Result

-

### ChatGPT Result

-

### Your question here

Hello! Does loop invariant preservation mean that once the loop invariant is true, it must remain true? So even if loop invariant init is false (and the loop invariant remains false), loop invariant preservation could be correct, because the loop invariant never was true? 
Thanks in advance!

**Comment by Lee-Janggun** [comment]
Yes, you are correct. 

In the specific case where the invariant is false, the loop invariant will be preserved, but it cannot be initialized.
This is also why initialization is important.
