### ISSUE TITLE
[Assignment 9] (What is the meaning of pruposes in bigint.rs)

### ISSUE THREAD

**Issue by queendoctor123** [kaist-cp/cs220#408]
### Related Issue

N/A

### Googling Result

N/A

### ChatGPT Result

N/A

### Your question here

I don't know the meaning of "pruposes" in this [line](https://github.com/kaist-cp/cs220/blob/main/src/assignments/assignment09/bigint.rs#L28)

**Comment by kingdoctor1234** [comment]
https://chatgpt.com/share/67121423-5b20-8012-bb8f-74a8278f3d6b

It seems like a typo, I think the correct word is "purposes". You need to ask it to the ChatGPT before you create an issue!

**Comment by queendoctor123** [comment]
Oh, ok, thank you! kingdoctor1234

**Comment by kimdoctor123** [comment]
Also, I think there is another typo here:

https://github.com/kaist-cp/cs220/blob/main/src/assignments/assignment09/small_exercises.rs#L12

**Comment by queendoctor123** [comment]
Oh good catch, thank you kimdoctor123

**Comment by kingdoctor123** [comment]
Something strange happening in this issue...

**Comment by 33577** [comment]
By the way, thanks for the typo report!
