### ISSUE TITLE
[Homework 4] Designing a calculator (due: 2022-10-07 23:59:59)

### ISSUE THREAD

**Issue by zzz845zz** [kaist-cp/cs220#41]
Understand the parser library [pest](https://pest.rs/) and design a simple arithmetic calculator.

- Read the description [here](https://github.com/kaist-cp/cs220/blob/main/src/assignments/assignment04/mod.rs). You're going to fill out the `todo!()`s.

- You can grade your solution yourself by running `./scripts/grade-04.sh`.

- Run `./scripts/prepare-submissions.sh` and then submit `./target/assignment04.zip` [here](https://gg.kaist.ac.kr/assignment/70/).

- We will accept pull requests until 9/30(Fri) for adding extra test cases. Feel free to make a PR if you think we need more test cases.

- **IMPORTANT**: we will nullify all previous submissions on 9/30. Please keep this in mind and **submit your solution again after 9/30.**

- **IMPORTANT**: only the last submission counts. Please make sure the last submission succeeds.

- **IMPORTANT**: don't fork this repository. It'll be public!

**Comment by minseongg** [comment]
**IMPORTANT**: Please do not implement your solution to pass only the inputs in the test cases.

For example: `fahrenheit_to_celsius` function in assignment 2 ([Problem](https://github.com/kaist-cp/cs220/blob/main/src/assignments/assignment02.rs#L14-L17), [Test cases](https://github.com/kaist-cp/cs220/blob/main/src/assignments/assignment02_grade.rs#L6-L9))

```rust
pub fn fahrenheit_to_celsius(degree: f64) -> f64 {
    if degree == 32.0 {
        0.0
    } else {
        100.0
    }
}
```

**Comment by jeehoonkang** [comment]
Hint: https://pest.rs/book/#sample tells you how to parse an expression. You may need to change a few things, but I strongly encourage you to start from the code snippet provided there. You don't need to fully understand the code; all you need to do is just changing a few things a little bit.

**Comment by intellkim** [comment]
[https://pest.rs/book/#sample](url) is down when I access the site, so I can see the contents in this site. Is there another site to see the similar contents?

**Comment by minseongg** [comment]
The above reference is down, so please follow these:

- https://github.com/pest-parser/book/blob/master/src/intro.md#sample
- https://github.com/pest-parser/book/blob/master/examples/calculator/src/main.rs

**Comment by vm3fk5dla2** [comment]
I cannot enter the pest.rs website...

**Comment by minseongg** [comment]
@vm3fk5dla2 It seems like the pest.rs website is down, please follow the references in my previous comment.

**Comment by znunc** [comment]
@minseongg The precedence and price_climber part is missing from your new link. Should we get the information by ourselves?

**Comment by zzz845zz** [comment]
@znunc Please see this document: https://docs.rs/pest/2.3.0/pest/prec_climber/struct.PrecClimber.html

**Comment by vm3fk5dla2** [comment]
Can I use other "use declaration (use:: ... ) " that doesn't exist before?

**Comment by m-spitfire** [comment]
> Can I use other "use declaration (use:: ... ) " that doesn't exist before?

yes, you can. You will need to use the "use" for HW 4.

**Comment by vm3fk5dla2** [comment]
> > Can I use other "use declaration (use:: ... ) " that doesn't exist before?
> 
> yes, you can. You will need to use the "use" for HW 4.

Aha... Thank you!! Then, how about "macro"?? Can I use it?

**Comment by m-spitfire** [comment]
> > > Can I use other "use declaration (use:: ... ) " that doesn't exist before?
> > 
> > 
> > yes, you can. You will need to use the "use" for HW 4.
> 
> Aha... Thank you!! Then, how about "macro"?? Can I use it?

I think you are free to use whatever you are capable of, unless otherwise said so(ex: writing function based on test case)

**Comment by vm3fk5dla2** [comment]
**I get all passed in my vs-code by running ./script/grade-04.sh.** 
However, when I submit this, it panics at comment which exists before editting... (thread 'assignments::assignment04_grade::test::test_parse' panicked at 'not yet implemented: fill here', src/assignments/assignment04/**parser.rs:24:5**)
parser.rs:24 is comment... (/// For associativity of each operator, please follow [here](https://docs.rs/pest/latest/pest/prec_climber/struct.PrecClimber.html#examples).)
How can I get score?...

**Comment by minseongg** [comment]
@vm3fk5dla2 I think one possible reason can be compression issue. (https://github.com/kaist-cp/cs220/issues/46#issuecomment-1249541497)

Could you please run `./scripts/prepare-submissions.sh` and then submit `./target/assignment04.zip`?

**Comment by vm3fk5dla2** [comment]
> @vm3fk5dla2 I think one possible reason can be compression issue. [#46 (comment)](https://github.com/kaist-cp/cs220/issues/46#issuecomment-1249541497)
> 
> Could you please run `./scripts/prepare-submissions.sh` and then submit `./target/assignment04.zip`?

I don't know what to say..... You're awesome!!!
I’m really grateful for your help :)
