### ISSUE TITLE
About VScode code server in midterms exam

### ISSUE THREAD

**Issue by Ahmadsm2005** [kaist-cp/cs220#412]
Hello! I wanted to inquiry about the VScode Code Server. Are we allowed to save any past codes or references in that server or is the server going to be reset for the midterm exam? Thank you!

**Comment by Jaewookim08** [comment]
The server will be reset for the midterm.

**Comment by ssamt** [comment]
Does that mean we will have to reinstall cargo and stuff when we take the exam?

**Comment by Jaewookim08** [comment]
@ssamt Cargo and other required tools will already be installed. Please run midterm_rehearsal_2.seb file in #403 to test out the exam environment.
