### ISSUE TITLE
About seb

### ISSUE THREAD

**Issue by brongs2** [kaist-cp/cs220#413]
### Related Issue

.

### Googling Result

.

### ChatGPT Result

.

### Your question here

I am using Mac os sequoia and after I log in the google form, I cannot access given gg link, so I can't get the token
How can I access that link? clicking the link does not work.

**Comment by Lee-Janggun** [comment]
Does cmd + click work?

**Comment by brongs2** [comment]
> Does cmd + click work?

Thank you it works
