### ISSUE TITLE
[Homework 4] Multiple Ways of Parsing Possible for HW4

### ISSUE THREAD

**Issue by choejms** [kaist-cp/cs220#42]
Hi if the given string for parsing is "1 + 2 + 3"
we can parse the string into either
1) 1 + (2 + 3)
2) (1 + 2) + 3

The resulting command struct would be different. 
Which one should we choose?

**Comment by zzz845zz** [comment]
Please follow the associativity [here](https://docs.rs/pest/latest/pest/prec_climber/struct.PrecClimber.html#examples) for each operator.
