### ISSUE TITLE
[Assignment 8] to_usize feels impossible

### ISSUE THREAD

**Issue by ssamt** [kaist-cp/cs220#425]
### Googling Result

N/A

### ChatGPT Result

N/A

### Your question here

Here's my reasoning: due to the traits of T, only Fn(T) -> T that are possible are |x| -> x and |x| -> T::default(). But calling n with either of them does not provide any information of n.

Is my reasoning incorrect? Or is there something else I'm missing?

**Comment by Lee-Janggun** [comment]
You are correct, but I'm unsure why you think that makes `to_usize` impossible.
As the Church number representing  `n` is a function that applies the given function `n` times, you need to count the number of function applications somehow.

Hint: look at the imports given in the skeleton code.

**Comment by ssamt** [comment]
I solved it. Thank you for the hint.
