### ISSUE TITLE
[Assignment 13] (I can not submit assignment 13)

### ISSUE THREAD

**Issue by Jeong-jin-Han** [kaist-cp/cs220#427]
### Related Issue

.

### Googling Result

.

### ChatGPT Result

.

### Your question here

```text
Rust is installed now. Great!

To get started you may need to restart your current shell.
This would reload your PATH environment variable to include
Cargo's bin directory ($HOME/.cargo/bin).

To configure your current shell, you need to source
the corresponding env file under $HOME/.cargo.

This is usually done by running one of the following (note the leading DOT):
. "$HOME/.cargo/env"            # For sh/bash/zsh/ash/dash/pdksh
source "$HOME/.cargo/env.fish"  # For fish
Archive:  submission.zip
  inflating: submission/small_exercises.rs  
  inflating: submission/small_exercises_grade.rs  
  inflating: submission/mod.rs       
Cloning into 'cs220'...
mv: cannot stat '../submission/matmul.rs': No such file or directory
```

Could you resolve this problem? [gg.kaist.ac.kr/assignment13]
I can not submit the file...

**Comment by Jaewookim08** [comment]
How did you make the .zip file?

By the way, you can format code (or logs) by surrounding the text with backticks: ````code````.

**Comment by Lee-Janggun** [comment]
You probably downloaded the wrong submission file. Are you sure you downloaded the one for assignment 13?

**Comment by Jeong-jin-Han** [comment]
![image](https://github.com/user-attachments/assets/8fa97f78-2d2f-4849-842e-26a8653ad790)

I submitted several assignment13.zip files, but all of them were rejected.
The above figure shows the log of the situation.
