### ISSUE TITLE
[Assignment 13] Bug in gg judgement script

### ISSUE THREAD

**Issue by seo-rii** [kaist-cp/cs220#429]
### Related Issue

https://github.com/kaist-cp/cs220/issues/427

### Googling Result

.

### ChatGPT Result

.

### Your question here

GG judgement script is trying to copy `../submission/matmul.rs`, which does not exist, so it exits with code 1. It seems only `small_exercises_grade.rs` exists for assignment 13 currently. https://github.com/kaist-cp/cs220/tree/main/src/assignments/assignment13

**Comment by Jaewookim08** [comment]
I believe submit.sh for Assignment 13 would take the matmul.rs from Assignment 9.

**Comment by seo-rii** [comment]
Ah, I missed that submit.sh was updated. I forked repo before the update so it didn't work. Sorry for confusion.
