### ISSUE TITLE
Homework 2_self-grader

### ISSUE THREAD

**Issue by riskyben** [kaist-cp/cs220#43]
When I run assignment02_grade.rs all the tests pass 
![image](https://user-images.githubusercontent.com/112473256/190604534-c5e3c8ff-9bc7-4af8-baf6-d4917e79959f.png)
But when I upload on gg.kaist I get No for success and I tried the self-grader script as well and I get this as a response
![image](https://user-images.githubusercontent.com/112473256/190605334-49d1831f-f7fe-4033-aead-60abfbadad4a.png)
How do I fix this?

**Comment by minseongg** [comment]
In self-grader, formatter and linter are performed before executing tests. (Related issue: https://github.com/kaist-cp/cs220/issues/13)

Please apply the suggestions of `cargo fmt --check` and `cargo clippy`, then rerun self-grader.

**Comment by riskyben** [comment]
> In self-grader, formatter and linter are performed before executing tests. (Related issue: #13)
> 
> Please apply the suggestions of `cargo fmt --check` and `cargo clippy`, then rerun self-grader.

I already applied the changes of 'cargo fmt --check' but when I run it again it still recommends the same changes

**Comment by minseongg** [comment]
Could you please do `cargo fmt --all` and then try again?

**Comment by riskyben** [comment]
> It sounds strange...
> 
> Could you please do `cargo fmt --all` and then try again? It automatically apply the suggestions of `cargo fmt --check`.

it worked now for cargo fmt and stopped showing the changes, but the suggested changes by cargo clippy that i applied are still being suggested

**Comment by minseongg** [comment]
Could you please do `cargo clippy` again to check whether you applied the suggestions well?

**Comment by riskyben** [comment]
> Could you please do `cargo clippy` again to check whether you applied the suggestions well?
> 
> If it still suggests the same things, then I think there was a problem while applying the suggestions. (e.g., file saving error)

I double checked but it kept on suggesting the same changes so i just ignored cargo clippy and kept on applying the changes suggested by the log in gg.kaist. It finally said Yes under the Success column. Once it says yes that means i get full score even if grade-02.sh doesn't work right?

**Comment by jeehoonkang** [comment]
Closing, as the error message is posted as an image. Please re-create another issue with text `like this`

```rust
fn or_like_this() {}
```
