### ISSUE TITLE
[Assignment 11] assignment11/graph.rs typo - remove_node() description

### ISSUE THREAD

**Issue by jidnjs** [kaist-cp/cs220#430]
### Related Issue

#287

### Googling Result

.

### ChatGPT Result

.

### Your question here

```
/// Adds a node to the subgraph. Returns true iff the node is successfully removed.
pub fn remove_node(&mut self, node: &NodeHandle) -> bool {
    todo!()
}
```

It is very minor issue, but I think there is typo in the description of remove_node function.

This typo was fixed and committed in #287 , but I think there was merge conflict.

**Comment by Jaewookim08** [comment]
Thanks for reporting the issue. We'll fix it shortly.

**Comment by Jaewookim08** [comment]
Fixed with https://github.com/kaist-cp/cs220/commit/0e95aa028d43b597a42d9648c8d52b35e87f8ec0.
