### ISSUE TITLE
[Assignment 10] Why we need to use RefCell<vector> in labyrinth problem?

### ISSUE THREAD

**Issue by Junhajang-0562** [kaist-cp/cs220#431]
### Related Issue

no

### Googling Result

no

### ChatGPT Result

chatGPT do not suggest any proper reason for question

### Your question here

과제 10의 labyrinth 문제를 보면 처음에 Husband 구조체에 brain이라는 field가 이미 존재합니다. 이 brain이라는 field는 RefCell로 감싸진 벡터이고 크기가 100으로 주어져있는데 이 field가 왜 필요한지 그리고 다른 field를 정의해서 사용해도 괜찮은지 궁금합니다. 
벡터에 0번 index부터 순차적으로 방문한 방번호를 저장하려면 50이면 충분할테고 만약 벡터를 탐색하면서 어디까지 탐색했는지를 확인하는 방식의 구현을 원하는 것이라면 제 생각에는 Husband 구조체에 시작점을 나타내는 field를 추가해줘야 할 것 같습니다. 그런데 다른 field를 추가해서 구현하는 것이 가능하다면 벡터가 아닌 단순하게 RefCell로 감싼 usize 변수를 업데이트 해가면서 구현이 가능해서 굳이 그럴 필요가 없을 것 같습니다. 하여 미리 주어진 brain이 어떤 의미를 가지고 주어진 것인지 질문드립니다.

1. 미리 주어진 brain field를 없애고 다른 field를 정의해서 test를 통과하고 gg에 제출하였는데 Valid 하고 log에서 점수가 부여된것도 확인하였는데 이대로 괜찮은 것인가요? 
2-1. 만약 반드시 brain field를 사용해야 한다면 다른 field를 추가하는 것도 금지되나요?
2-2. brain field만 사용해야 한다면 크기 100을 전부 활용하는 코드로 구현해야 하는 것일까요? 
(영어로 질문하면 의미가 달라질까봐 한글로 썼으나 밑에 번역한 것도 추가하였습니다!)

In the problem of Labyrinth in Assignment 10, the Husband struct already has a brain field defined. This brain field is a vector wrapped with RefCell, and its size is given as 100. I am wondering why this field is necessary and whether it is acceptable to define and use other fields instead.

If the intention is to store the visited room numbers sequentially starting from index 0 in the vector, then 50 would be sufficient. Alternatively, if the intention is to track the current position during exploration by searching the vector, I believe we need to add a field representing the starting point to the Husband struct. However, if adding other fields is acceptable, we could achieve this more simply by updating a RefCell-wrapped usize variable instead of using the vector. In that case, the brain field would not be necessary. Hence, I am asking what significance the pre-defined brain field holds.

1. I removed the pre-defined brain field and defined other fields to pass the test and submit it to GG. I confirmed it was valid and that points were assigned in the log. Is this approach acceptable as it stands?
2-1. If the brain field must be used, is adding other fields also prohibited?
2-2. If only the brain field can be used, does that mean the code must utilize all 100 entries of the vector?

**Comment by Lee-Janggun** [comment]
The brain field can be freely modified, the type used in the skeleton is what we have in the model solution.
