### ISSUE TITLE
[Assignment #11] Can I change definition of struct Node?

### ISSUE THREAD

**Issue by ssamt** [kaist-cp/cs220#432]
### Googling Result

N/A

### ChatGPT Result

N/A

### Your question here

linked_list.rs:
```
/// Node of the list.
#[derive(Debug)]
pub struct Node<T: Debug> {
    /// Value of current node.
    pub value: T,

    /// Pointer to the next node. If it is `None`, there is no next node.
    pub next: Option<Box<Node<T>>>,
}

impl<T: Debug> Node<T> {
    /// Creates a new node.
    pub fn new(value: T) -> Self {
        Self { value, next: None }
    }
}
```

Can I make changes to this part of the code of linked_list.rs?

I think to implement some functions like push_front, at some point two nodes would have to point at the same Node. So I want to try changing Box to Rc. Is this unnecessary?

**Comment by park-sunho** [comment]
You may freely change the struct. You only need to make sure that your solution is accepted by grading script and gg. But current definition of `Node` is sufficient to do the assignment.
