### ISSUE TITLE
[Assignment 12] Card problem

### ISSUE THREAD

**Issue by Jaiwooyu** [kaist-cp/cs220#433]
### Related Issue

N/A

### Googling Result

N/A

### ChatGPT Result

N/A

### Your question here

In the card problem, the grade file shows that the 25 bots use a strategy of sequentially exploring the card pool in 25 sections. Therefore, I also used a simple strategy where I sequentially explore the entire card pool divided into 25 sections. However, since I cannot access values like the Mutex or other values from card.rs in card_grade.rs, I had no choice but to use this simple strategy. When implementing this, sometimes the result comes out correct, but other times it results in a small margin of error. In this case, is this a wrong approach? Is there a strategy that guarantees a certain victory?

Edit on 11/29 00:03
I'm not sure, but I submitted the implementation of the zip function as a zip file on GG, and the check result came out as perfect. Did I solve it correctly? And in this case, will it be reflected as a full score in my grade?

**Comment by Jaewookim08** [comment]
- There are several strategies to solve the card problem, some more efficient than others. However, a simple solution is enough to pass our test.
- **Only your last submission results will be graded.** If your last submission has a full score, you're all set.
