### ISSUE TITLE
[Assignment 13] small exercise problem

### ISSUE THREAD

**Issue by Jaiwooyu** [kaist-cp/cs220#434]
### Related Issue

N/A

### Googling Result

N/A

### ChatGPT Result

N/A

### Your question here

In Assignment 13, I implemented all five functions using data parallelism. For vec_add_par, I also used the .par_iter() method to implement it with data parallelism. When I submitted the zip file to GG, the other four functions always passed, while vec_add_par sometimes passed and sometimes didn't. I thought the effect of parallelism is negligible because vec_add_par is a simple function that only adds elements of vectors. And that cause these inconsistency. Is this right, or is my implementation wrong?
Also, my final submission on GG is recorded as a full score—will this be reflected as a full score in my grade?

**Comment by Lee-Janggun** [comment]
The parallelism tests we have will also have some amount of random factor due to scheduling luck; if it passes in gg, it should be fine.
