### ISSUE TITLE
Non-mandatory Q&A Session on December 11th

### ISSUE THREAD

**Issue by Lee-Janggun** [kaist-cp/cs220#437]
During the class on December 11th, the TAs will have a Q&A session that is not mandatory.

You can ask questions about lecture materials, homework, or exam environment (i.e., SEB).

**Comment by GianniLee** [comment]
I wonder if the date is correct, since we don't have class on Tuesdays!
Also, is assignment 12, 13 included in the final exam scope?

**Comment by Lee-Janggun** [comment]
@GianniLee 
* Thanks, I updated the date.
* Yes, it'll be included.
