### ISSUE TITLE
hw2 gg grader

### ISSUE THREAD

**Issue by kang-hyeok** [kaist-cp/cs220#44]
![image](https://user-images.githubusercontent.com/113456004/190636361-eb63266c-3036-4b18-8543-34972480bb54.png)
i can see score in vscode 
but, there are not any score or other error message on gg.
that picture is the last part of gg checker. how can i fix it?

**Comment by minseongg** [comment]
Does your code pass self-grader? (`./scripts/grade-02.sh`)

In self-grader, formatter and linter are performed before executing tests. ([scripts/grade-02.sh#L20-L22](https://github.com/kaist-cp/cs220/blob/main/scripts/grade-02.sh#L20-L22))

If your code does not pass the self-grader, please apply the suggestions of `cargo fmt --check` and `cargo clippy`, then rerun self-grader.

**Comment by kang-hyeok** [comment]
after 'cargo clippy'  it said "Finished dev [unoptimized + debuginfo] target(s) in 0.19s"
but gg does not show 'how many success/fail test result'

**Comment by minseongg** [comment]
Could you do `cargo fmt --all` and then try again?

**Comment by RosFuDah** [comment]
cargo fmt --all shows nothing,
and if i run cargo clippy,
cargo clippy
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
but if i run my self grader, it shows cargo asan failed.
How could i fix this error?

**Comment by kang-hyeok** [comment]
i don't know why it works....
anyway, after make 'cargo fmt --all' there are anything change, but now it works in gg. thatnk you:)

**Comment by minseongg** [comment]
@RosFuDah 

> cargo fmt --all shows nothing, and if i run cargo clippy, cargo clippy Finished dev [unoptimized + debuginfo] target(s) in 0.15s but if i run my self grader, it shows cargo asan failed. How could i fix this error?

Related issue: https://github.com/kaist-cp/cs220/issues/12

I recommend you to submit to gg if you pass the formatter and linter and tests on `cargo test` (even if it does not pass `cargo_asan` and `cargo_tsan`).

**Comment by jeehoonkang** [comment]
Closing, as the error message is posted as an image. Please re-create another issue with text `like this`

```rust
fn or_like_this() {}
```
