### ISSUE TITLE
Cannot access code-server in rehearsal SEB file

### ISSUE THREAD

**Issue by qkrdmsql** [kaist-cp/cs220#441]
I cannot access code-server though the rehearsal SEB file. It just shows a white screen. It worked fine when I tested for the midterm. Why am I having this issue?

**Comment by Jaewookim08** [comment]
The exam server is currently set to block connections from networks other than the exam room Wi-Fi.
If you didn’t experience connection issues during the midterm, you should be fine.
+I'll check if we can disable the connection whitelist until tomorrow.

**Comment by qkrdmsql** [comment]
I also tested using wifi E3_1501 and it didn't work..

**Comment by Jaewookim08** [comment]
I'm checking the server settings.. I'll let you know if I figure out what's wrong.

**Comment by Jaewookim08** [comment]
- The connections will be allowed when the exam starts, so don't worry. If you want to test code-server, please use the development server since it has almost the same configurations.
