### ISSUE TITLE
Unable to access to coder vscode 

### ISSUE THREAD

**Issue by Akais24** [kaist-cp/cs220#442]
### Googling Result

.

### ChatGPT Result

.

### Your question here

I tried to use Coder VSCode for the test exam environment.
However, I cannot interact with anything in the workspace or Docker page, and it freezes, making it inaccessible as shown in the screen below. How can I resolve this issue?

<img width="684" alt="image" src="https://github.com/user-attachments/assets/de20b78d-d6ce-4b85-9b6f-c99ae690803c" />

**Comment by Jaewookim08** [comment]
Hello, could you tell us exactly how you accessed the test environment? Did you use seb?

**Comment by Akais24** [comment]
No. I just try to access with Chrome.
I intend to test environment, but i could not access to page for original container for assignment too

**Comment by Jaewookim08** [comment]
Could you try making a new workspace as suggested in #440 ?

**Comment by Akais24** [comment]
Oh. Now it works. Thanks very much
