### ISSUE TITLE
Seb files for final

### ISSUE THREAD

**Issue by Jaewookim08** [kaist-cp/cs220#443]
Seb files for final will be uploaded here.
- **WARNING: once you launch SEB, you will not be able to exit it until the exam ends.**
- There is no SEB enter password.
- The problems are hidden until the exam starts.

Part 1:
[cs220_final_part1.zip](https://github.com/user-attachments/files/18174440/cs220_final_part1.zip)

Part 2:
[cs220_final_part2.zip](https://github.com/user-attachments/files/18174794/cs220_final_part2.zip)

**Comment by park-sunho** [comment]
We announce the exit passwords here:
* Part 1: hoare
* Part 2: byeworld
