### ISSUE TITLE
Announcement on final scores and claim session

### ISSUE THREAD

**Issue by park-sunho** [kaist-cp/cs220#444]
We will hold an in-person claim session on this Friday and next Monday. Grading will be done and be announced today.

* When: (1) **12/20 (Fri) 19:00 ~ 20:00**, (2) **12/23 (Mon) 16:00 ~ 17:00**
* Where: E3-1, **Room 2450**
  * Please be noted that the room number is different from the one we previously used for midterm claim session.

The claim session will be held twice on Friday and Monday, and you can freely choose between the two sessions. If you cannot attend both, then please feel free to send us an email.

| Statistics | Value |
|--- | --- |
| Full scores | 90 |
| Average | 46.34 |
| First Quartile (25%) | 34.5 |
| Second Quartile (Median) | 47 |
| Third Quartile (75%) | 56.75 |

![Final Scores](https://github.com/user-attachments/assets/f21b4169-33fc-43ef-88da-2d507ded0b58)

**Comment by park-sunho** [comment]
We just uploaded the grading result in gg. Please check the result.

**Comment by park-sunho** [comment]
We also uploaded the exam problems here: https://github.com/kaist-cp/cs220/issues/280

**Comment by Lee-Janggun** [comment]
Note: You should have gotten a copy of your responses via the email you signed in. Please check it if you want to look at your answers.

**Comment by Jaewookim08** [comment]
We just updated the scores for Problem 3 (no one's score was lowered).
