### ISSUE TITLE
Final Exam Score summation seems to be wrong

### ISSUE THREAD

**Issue by Akais24** [kaist-cp/cs220#446]
### Googling Result

.

### ChatGPT Result

.

### Your question here

As I checked my final exam score, the total score is different with summation of each problems. Is there any deduction on score?

**Comment by Lee-Janggun** [comment]
Oh sorry, we updated some points, but didn't update the total... give me a minute.

**Comment by Lee-Janggun** [comment]
Can you check again?

**Comment by Akais24** [comment]
It fixed! Thanks!
