### ISSUE TITLE
[Homework 4] cargo asan failed

### ISSUE THREAD

**Issue by choejms** [kaist-cp/cs220#45]
Hi, I passed all 3 tests but I am getting an error message that says following:

**running 3 tests
test assignments::assignment04_grade::test::test_context_calc_expression ... ok
test assignments::assignment04_grade::test::test_context_calc_command ... ok
test assignments::assignment04_grade::test::test_parse ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 20 filtered out; finished in 0.00s

Running with cargo_asan...
Build failed!
Test timed out: cargo_asan test  --lib assignment04_grade**

How can I interpret this message?
Is there any way I can check test cases for cargo_asan test?

**Comment by m-spitfire** [comment]
Hello! See my comment at  https://github.com/kaist-cp/cs220/issues/12#issuecomment-1235085251
