### ISSUE TITLE
[Homework 5] Verifying Binary Search (due: 2022-10-07 23:59:59)

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs220#48]
Verify binary search algorithm.

- Read the description [here](https://github.com/kaist-cp/cs220/blob/main/assets/why3/binary_search.mlw). You're going to fill out the `(* TODO *)`.

- You can run Why3 in your browser: https://why3.lri.fr/try/

- Submit your `binary_search.mlw` [here](https://gg.kaist.ac.kr/assignment/71/).

- **IMPORTANT**: only the last submission counts. Please make sure the last submission succeeds.

- **IMPORTANT**: don't fork this repository. It'll be public!

**Comment by minseongg** [comment]
**IMPORTANT**: We fixed the grader script to ignore diff caused by line ending styles. (CRLF vs. LF) (https://github.com/kaist-cp/cs220/issues/82)

If you worked on Windows OS and failed to submit due to "not legit submission" error, please submit again.

**Comment by jeehoonkang** [comment]
**IMPORTANT**

- you should implement your binary search with the time complexity `O(lg n)`, where `n` is the size of the array.
- Even if your solution is not `O(lg n)`, you may be able to successfully submit your solution to gg.
- But we will manually review your submissions if they indeed have the time complexity `O(lg n)`.

**Comment by vm3fk5dla2** [comment]
I have a question.
Why ensures  { 0 <= result <= length a }?
Can result equal to length a?..

**Comment by choejms** [comment]
@vm3fk5dla2 
If the searched element is greater than the last element of the list, then the position for insertion should be length a.
e. g. ) a = [1, 2, 3], v = 4. Then result = 3.

**Comment by kohs100** [comment]
Since postcondition forces the result to be the leftmost index of v (if there is multiple v in the list), can I find the result only with binary search? e.g. If the list is 112222244 and v=2, binary search will find index 4 and terminates, and index 3 can be counterexample since a[3]=2 and v=a[4]=2.

**Comment by minseongg** [comment]
The accepted rate for the homework 5 is as follows. (Except for the students who dropped the course)

- Total: 133
- Success: 98
- Success rate: 73.68%
