### ISSUE TITLE
[Homework 3] Error:some `extern` functions couldn't be found

### ISSUE THREAD

**Issue by AlijonovMukhammaddiyor** [kaist-cp/cs220#50]
I am getting the following error when I run ./scripts/grade-03.sh on the server.

<img width="2037" alt="Screen Shot 2022-09-18 at 8 17 56 PM" src="https://user-images.githubusercontent.com/74100661/190899466-730ff097-e239-4ae4-8e0f-b5dbaaf05045.png">

Can you help me fix this?

**Comment by minseongg** [comment]
Could you please do `cargo clean` and then try again?

**Comment by jeehoonkang** [comment]
Please paste your error message in text in a new issue.

**Comment by AlijonovMukhammaddiyor** [comment]
> Could you please do `cargo clean` and then try again?

Thank you it worked

**Comment by AlijonovMukhammaddiyor** [comment]
> Please paste your error message in text in a new issue.

Understood, Professor!
