### ISSUE TITLE
How to use HashMap and HashSet

### ISSUE THREAD

**Issue by albinjeon** [kaist-cp/cs220#51]
To insert some variable to HashSet or to access some value in HashMap, I use .insert() function to HashSet. But there is some error when I use insert to hashset >> unused result of type 'bool'. and also there are some type error for HashMap. I know that the return of insert function is bool because I saw many times rust doc. However, example code of them use just >> set.insert(val) without error. How can I put the value to the HashSet or HashMap? 
![캡처](https://user-images.githubusercontent.com/12196529/190911251-667e0619-99c4-4782-afe3-7c45553e3e87.PNG)

**Comment by m-spitfire** [comment]
Hello! The reason why compiler denies the unused results, is because at the top level file the lint [`unused_results`](https://github.com/kaist-cp/cs220/blob/main/src/lib.rs#L21) is denied. If you just want to ignore the results one trick is to do 
```rust
let _ = function_that_returns_bool();
```

**Comment by albinjeon** [comment]
thank you for your comment. But I have an additional question. How can I insert the element to HashMap with no Option<> type? In rust doc about the insert of HashMap, that return type of  insert is Option<V> but I want to insert the HashSet or other  types. Is it possible?

**Comment by m-spitfire** [comment]
I'm not sure if I get your question. As you said in the documentation the return type of `.insert()` is `Option<V>`, but the return type isn't really related to arguments' types. The function signature is given like this:
```rust
pub fn insert(&mut self, k: K, v: V) -> Option<V>
```
The arguments are `k` and `v`, whose types are `K` and `V`, which are [generics](https://doc.rust-lang.org/book/ch10-00-generics.html), which means the `HashMap` key and value could be any type.

**Comment by albinjeon** [comment]
thank you! I'll have to think about it a little more.
