### ISSUE TITLE
[Homework 5] Is Why3 Installation Necessary?

### ISSUE THREAD

**Issue by choejms** [kaist-cp/cs220#52]
To complete homework 5, is it not necessary to install Why3 on our computers?
The instruction says we can run Why3 in our browser, but I am wondering if installation of Why3 is necessary to complete the homework.

In particular, since there are no test cases, how can we know our program is verified?
The Why3 documentation says we should use "why3 prove myfile.mlw," but I do not think we can run this command on our browser.

Thank you.
Kind regards

**Comment by m-spitfire** [comment]
+1

When I run the given reference `binary_search` function from why3 gitlab it says there's no main function is defined. So I define main function inside of `BinarySearch` module:
```whyml
let main () =
      let b = Array.make 5 3 in
      binary_search b 3
```
But this still raises `Not_found` exception. I am suspecting there's something wrong with the array declaration, but this is only way I found to create an array from given documentation and examples.

**Comment by jeehoonkang** [comment]
I think the homework assignment is doable in the browser. I'll walk through a detailed procedure for solving examples in class.
