### ISSUE TITLE
[Homework 4]  How to use Parser (Syntax)

### ISSUE THREAD

**Issue by theonlyrealALEX** [kaist-cp/cs220#53]
I tried the following Code to try out the parsing, but even though SytnaxParses is defined it throws an error. I tried looking on the web for a solution but there are not many ressources:   
` let succesfull_parse = SyntaxParser::parse(Rule::command, line);`
(the compiler told me to write `use self::inner::SyntaxParser;`)
;
after that i get the following error for **parse:**

```
let succesfull_parse = SyntaxParser::**parse**(Rule::command, line);
no function or associated item named `parse` found for struct `SyntaxParser` in the current scope
items from traits can only be used if the trait is in scoperustc[E0599](https://doc.rust-lang.org/error-index.html#E0599)
parser.rs(17, 5): function or associated item `parse` not found for this
parser.rs(5, 1): the following trait is implemented but not in scope; perhaps add a `use` for it:: `use
```

for **Rule**

```
let succesfull_parse = SyntaxParser::parse(**Rule**::command, line);
{unknown}
failed to resolve: use of undeclared type `Rule`
use of undeclared type `Rule`rustc[E0433](https://doc.rust-lang.org/error-index.html#E0433)
```

**Comment by m-spitfire** [comment]
Hello. Please refer to Rust Book's [Chapter 7](https://doc.rust-lang.org/book/ch07-02-defining-modules-to-control-scope-and-privacy.html) about modules and privacy in a project. (Hint: `SyntaxParser` is in a module called `inner`)

**Comment by theonlyrealALEX** [comment]
@m-spitfire 
I got that part working, but i can't use the parse yet: 

no function or associated item named `parse` found for struct `SyntaxParser` in the current scope
items from traits can only be used if the trait is in scoperustc[E0599](https://doc.rust-lang.org/error-index.html#E0599)
parser.rs(15, 5): function or associated item `parse` not found for this
parser.rs(3, 1): the following trait is implemented but not in scope; perhaps add a `use` for it:: `use pest::Parser;

**Comment by zzz845zz** [comment]
@theonlyrealALEX Could you please try again after adding `use pest::Parser;` as the error message said?

**Comment by theonlyrealALEX** [comment]
//! Parser.

use self::inner::SyntaxParser;
use pest::Parser;

use super::syntax::*;
use anyhow::Result;

#[allow(missing_docs)]
#[allow(missing_debug_implementations)]
pub mod inner {
    use pest_derive::*;

    #[derive(Parser)]
    #[grammar = "assignments/assignment04/syntax.pest"]
    pub(crate) struct SyntaxParser;
}

/// Parses command.
///
/// ## Operator Associativty
///
/// For associativity of each operator, please follow [here](https://docs.rs/pest/latest/pest/prec_climber/struct.PrecClimber.html#examples).
///
/// e.g. `1+2+3` should be parsed into `(1+2)+3`, not `1+(2+3)` because the associativity of plus("add" in our hw) operator is `Left`.
pub fn parse_command(line: &str) -> Result<Command> {
    let succesfull_parse = SyntaxParser::pest(Rule::command, line);

    todo!("fill here")
}

that's the whole code (I am uploading because there is virtually no change in comparison to the orignal);

at **pest** i get the error message:

No function or associated item named `pest` found for struct `SyntaxParser` in the current scope
function or associated item not found in `SyntaxParser`rustc[E0599](https://doc.rust-lang.org/error-index.html#E0599)
parser.rs(15, 5): function or associated item `pest` not found for this

**Comment by zzz845zz** [comment]
> let succesfull_parse = SyntaxParser::pest(Rule::command, line);

You are misusing the `SyntaxParser` struct. There is no `SyntaxParser::pest()` function because the `Parser` trait support only `parse()` function. Please see this [document](https://docs.rs/pest/latest/pest/trait.Parser.html).

**Comment by m-spitfire** [comment]
> > let succesfull_parse = SyntaxParser::pest(Rule::command, line);
> 
> You are misusing the `SyntaxParser` struct. There is no `SyntaxParser::pest()` function because the `Parser` trait support only `parse()` function. Please see this [document](https://docs.rs/pest/latest/pest/trait.Parser.html).

Even if he tries to use `parse()` it will not still work. As I said in my first reply, you do not correctly "import" the required things from the `inner` module.

`#[derive(Parser)]` is a [macro](https://doc.rust-lang.org/book/ch19-06-macros.html), which as the [pest documentation](https://pest.rs/book/examples/csv.html#writing-the-parser), that implements `parse()` function for given struct, **and** the enum `Rule`(which you got the error for it too in the first place) for the grammar. So you need to use everything that has been implemented in the `inner` module. you need `use self::inner::*;` instead of only `SyntaxParser`
