### ISSUE TITLE
[Assignment 02] Inquiry about "Nullified"

### ISSUE THREAD

**Issue by yumincho** [kaist-cp/cs220#54]
```
Running with cargo_tsan --release...

running 9 tests
test assignments::assignment02_grade::test::test_capitalize ... ok
test assignments::assignment02_grade::test::test_chooses ... ok
test assignments::assignment02_grade::test::test_fahrenheit ... ok
test assignments::assignment02_grade::test::test_fibonacci ... ok
test assignments::assignment02_grade::test::test_gcd ... ok
test assignments::assignment02_grade::test::test_lyrics ... ok
test assignments::assignment02_grade::test::test_sum_array ... ok
test assignments::assignment02_grade::test::test_up3 ... ok
test assignments::assignment02_grade::test::test_zip ... ok

test result: ok. 9 passed; 0 failed; 0 ignored; 0 measured; 4 filtered out; finished in 0.00s
```

<img width="506" alt="image" src="https://user-images.githubusercontent.com/100757008/191171443-ab911f3f-299a-4b1a-a6fd-5eebf0e65732.png">
<img width="378" alt="image" src="https://user-images.githubusercontent.com/100757008/191171742-55442873-9e2a-44fc-9fc3-27a1f83e99f3.png">

I submitted my work for assignment 02 on 9/8, and i thought it passed all test cases. But as i checked it out today, it said it was "nullified", and i failed to submit it. Would you let me know what i have done wrong?

**Comment by minseongg** [comment]
We decided to accept pull requests until 9/8 for adding extra test cases, and we nullified all previous submissions on 9/8. 

So you needed to submit your solution again after 9/8... (We announced it at https://github.com/kaist-cp/cs220/issues/7#issuecomment-1235166742)

**Comment by yumincho** [comment]
I think I missed or misunderstood the notice.. Is there any way i can resubmit exactly the same code now and get some of the points? Or do i lose all the points? Thanks for your help.

**Comment by minseongg** [comment]
We decided to give full score for the nullified submissions that pass the updated test.

Could you please send email to minseong.jang@kaist.ac.kr with your (1) Student ID and (2) Submission ID?

**Comment by yumincho** [comment]
I just sent you an email. I'll check the further announcements really carefully. Thanks for your big help!

**Comment by yumincho** [comment]
There's one more question! Is there any way i can check my score or submission status of assignment 02? I just want to double check it .. :D

**Comment by minseongg** [comment]
We will send an email to you when the score is updated, please wait a little bit. Sorry for the inconvenience!

**Comment by yumincho** [comment]
Never mind and please take your time! Thanks for letting me know. I'll close this issue then.
