### ISSUE TITLE
[Assignment # 4]Parse example

### ISSUE THREAD

**Issue by doolymember** [kaist-cp/cs220#56]
I don't understand about parsing yet.

If adds and subtracts are in expression what operator do I have to choose first??

For example,

12 + 23 ^ 4 - 34 => 12 + ((23 ^ 4) - 34) 

34 + 67 - 71 + 5 - 9 => (34 + (67 - 71)) + (5 -9)

71 * 2 - 9 + 6 = > (71 * 2) - ( 9 + 6)

all of them are right parsing? 
 
I want to know about exact standard.

**Comment by Lee-Janggun** [comment]
The last one is clearly incorrect, as a simplification of the RHS leads to `71 * 2 - 15`, whereas the LHS leads to `71 * 2 - 3`.

**Comment by zzz845zz** [comment]
The order of operators with the same precedence is the same as the order of expression.

For example,

`1 + 2 - 3 => (1 + 2) - 3`
`1 - 2 + 3 => (1 - 2) + 3`

For your example,


`12 + 23 ^ 4 - 34 => (12 + (23 ^ 4)) - 34`
`34 + 67 - 71 + 5 - 9 => (((34 + 67) - 71) + 5) -9`
`71 * 2 - 9 + 6 = > ((71 * 2) - 9) + 6`
