### ISSUE TITLE
[Homework 4] How to unwrap Box<T>?

### ISSUE THREAD

**Issue by nargizas** [kaist-cp/cs220#57]
The documentation suggests using into_inner() function, however, it gives me an error:

```
error: crate-level attribute should be in the root module
  --> src\assignments\assignment04\context.rs:3:1
   |
3  | #![feature(box_into_inner)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: the lint level is defined here
  --> src\lib.rs:23:9
   |
23 | #![deny(warnings)]
   |         ^^^^^^^^
   = note: `#[deny(unused_attributes)]` implied by `#[deny(warnings)]`

error[E0658]: use of unstable library feature 'box_into_inner'
  --> src\assignments\assignment04\context.rs:38:68
   |
38 |                 super::syntax::BinOp::Add => self.calc_expression(&Box::into_inner(*lhs)),
   |                                                                    ^^^^^^^^^^^^^^^
   |
   = note: see issue #80437 <https://github.com/rust-lang/rust/issues/80437> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `cs220` due to 2 previous errors
```

Is there another way of getting the wrapped value?

**Comment by zzz845zz** [comment]
You can use [`as_ref()`](https://doc.rust-lang.org/std/boxed/struct.Box.html#method.as_ref) to get the `&T` from the `Box<T>`.

**Comment by m-spitfire** [comment]
Hello. I think rust can auto-infer the argument type. So I think the `self.calc_expression(lhs)` should also just work. See
> For instance, if the receiver has type Box<[i32;2]>, then the candidate types will be Box<[i32;2]>, &Box<[i32;2]>, &mut Box<[i32;2]>, [i32; 2] (by dereferencing), &[i32; 2], &mut [i32; 2], [i32] (by unsized coercion), &[i32], and finally &mut [i32].
* https://stackoverflow.com/questions/28519997/what-are-rusts-exact-auto-dereferencing-rules
* https://doc.rust-lang.org/reference/expressions/method-call-expr.html

**Comment by nargizas** [comment]
Thank you!
