### ISSUE TITLE
[Homework 4] cargo clippy gives warning but --fix won't fix the code

### ISSUE THREAD

**Issue by rowletter** [kaist-cp/cs220#58]
Hello, 

What I want to do is this:
1. Assign variable x, y with function returns the result as Result. 
2. If both x and y are Ok, then unwrap, add, wrap with Ok, and return. If either x or y is Err, then return Err. 
So I tried this code:

let x = function(/* some inputs */);
let y = function(/* another inputs */);
if x.is_err() {
        return x;
} else if y.is_err() {
        return y;
}
Ok(x.unwrap() + y.unwrap())

I thought this code was fine, but clippy gave me warning. 
It said that I should try fixing the second if statement(following after else) to this:
y.as_ref()?
I didn't think that it would work as I intended, but anyway I tried cargo clippy --fix. 
And what happened was: clippy fixed, found out that it needs a block after else, and returned to the original code. 
So I made a change what clippy intended(putting the statement into the block), and the compiler gave quite an error. 
I am struggling with this since I can't run the code if clippy gives a warning. 
So I want to know why clippy give warning for this code, or what is the problem of this code.

**Comment by Lee-Janggun** [comment]
Can you give the type signatures for the functions, and also the precise statement of the warning by clippy? 

The following similar function compiles fine with clippy.

[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=33a0f592cc9318c819628e560467750d).

```rust
fn ret_result(b: bool) -> Result<bool, bool> {
    if b {
        Ok(true)
    } else {
        Err(false)
    }
}

fn ret_result_2() -> Result<bool, bool> {
    let x = ret_result(true);
    let y = ret_result(false);
    if x.is_err() {
        return x;
    } else if y.is_err() {
        return y;
    }
    Ok(x.unwrap() || y.unwrap())
}

fn main() {
    let _ = ret_result_2();
}
```

**Comment by rowletter** [comment]
My actual code is this; I wrote like that because I was not sure that is okay to put my code here. 
I called the function recursively. 
```
    /// Calculates the given expression.
    pub fn calc_expression(&self, expression: &Expression) -> Result<f64> {
        if let Expression::BinOp { op: &BinOp , lhs: &Box<Expression> , rhs: &Box<Expression> } = expression {
            let lval_raw: Result<f64, Error> = self.calc_expression(lhs.as_ref());
            let rval_raw: Result<f64, Error> = self.calc_expression(rhs.as_ref());

            // return if either lval_raw or rval_raw is error
            if lval_raw.is_err() {
                return lval_raw;
            } else if rval_raw.is_err() {
                return rval_raw;
            }

            let lval: f64 = lval_raw.unwrap();
            let rval: f64 = rval_raw.unwrap();
            return Ok(match *op {
                super::syntax::BinOp::Add => lval + rval,
                super::syntax::BinOp::Subtract => lval - rval,
                super::syntax::BinOp::Multiply => lval * rval,
                super::syntax::BinOp::Divide => lval / rval,
                super::syntax::BinOp::Power => lval.powf(rval),
            });
        } else if let Expression::Num { 0: num: &f64 } = expression {
            return Ok(*num);
        } else if let Expression::Variable { 0: var: &String } = expression {
            use anyhow::Context;
            let b: Option<&f64> = self.variables.get(var);
            let a: Result<f64, Error> = b.copied().context("no var");
            return match a {
                Result::Ok(x: f64) => Ok(x),
                Result::Err(e: Error) => Err(e),
            };
        }
        println!("{:#?}", expression);
        panic!("Something went wrong");
    }
```
And what clippy says looks like this:
```
rowletter@rowletter-VirtualBox:~/cs220/cs220$ cargo clippy
    Blocking waiting for file lock on build directory
    Checking cs220 v0.1.0 (/home/rowletter/cs220/cs220)
error: this block may be rewritten with the `?` operator
  --> src/assignments/assignment04/context.rs:36:20
   |
36 |               } else if rval_raw.is_err() {
   |  ____________________^
37 | |                 return rval_raw;
38 | |             }
   | |_____________^ help: replace it with: `rval_raw.as_ref()?;`
   |
note: the lint level is defined here
  --> src/lib.rs:23:9
   |
23 | #![deny(warnings)]
   |         ^^^^^^^^
   = note: `#[deny(clippy::question_mark)]` implied by `#[deny(warnings)]`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#question_mark

error: could not compile `cs220` due to previous error
```

**Comment by m-spitfire** [comment]
Hello. I don't think sharing the whole function in the public issue is okay. You should have shared only relevant parts. (even if you edit the comment now the past revision will still be there)

Coming to your problem: 

Don't mind the `.as_ref()` part. The actual problem is that what you're trying to do herecan be achieved with "question mark operator"(see the first line of error). Please search for it in the `Result` documentation.

**Comment by rowletter** [comment]
Ah thank you. The question mark operator is the key, and your comment really saved me. 
Since the problem is the solved, I would close the thread.
