### ISSUE TITLE
[Homework 1] Preparing Rust Development Environment (due: 2022-09-09 23:59:59)

### ISSUE THREAD

**Issue by zzz845zz** [kaist-cp/cs220#6]
Prepare Rust development environment.

- Read the description [here](https://github.com/kaist-cp/cs220/blob/main/src/assignments/assignment01.rs). You're going to fill out the `todo!()`s.

- You can grade your solution yourself by running `./script/grade-01.sh`. If the server's evaluation results differ from your own evaluation results, please let us know.

- Submit your code [here](https://gg.kaist.ac.kr/assignment/60/).

- **IMPORTANT**: only the last submission counts. Please make sure the last submission succeeds.

- **IMPORTANT**: don't fork this repository. It'll be public!

**Comment by AlijonovMukhammaddiyor** [comment]
> * **IMPORTANT**: only the last submission counts. Please make sure the last submission succeeds.
> *

Can we use built-in functions or should we implement them from scratch by ourselves?

**Comment by minseongg** [comment]
@AlijonovMukhammaddiyor You can use built-in functions.

**Comment by minseongg** [comment]
Accepted Rate (except for the students who dropped it): 132/133
