### ISSUE TITLE
About Assignment Score

### ISSUE THREAD

**Issue by dgcha1028** [kaist-cp/cs220#62]
Hello, Professor. I have a question about assignment scoring.
As I know, If I pass all test cases, then I can get full score for this assignment. But If some test cases are failed, then can I get partial score of this assignment?
In my case, I finished for six functions and when I run this code, 6/7 is passed. But when I submit this file to gg server, ‘No’ is shown at ‘SUBMITTED?’. So can I get partial
score or cannot get any score? Thank you :)

**Comment by minseongg** [comment]
There will be no partial score.
