### ISSUE TITLE
[Homework 6] Mastering advanced types (1/2) (due: 2022-10-14 23:59:59)

### ISSUE THREAD

**Issue by minseongg** [kaist-cp/cs220#63]
Understanding generics, traits, and lifetimes.

- Read the description [here](https://github.com/kaist-cp/cs220/blob/main/src/assignments/assignment06.rs). You're going to fill out the `todo!()`s.

- You can grade your solution yourself by running `./scripts/grade-06.sh`.

- Submit your code [here](https://gg.kaist.ac.kr/assignment/72/).

- We will accept pull requests until 10/7 for adding extra test cases. Feel free to make a PR if you think we need more test cases.

- **IMPORTANT**: we will nullify all previous submissions on 10/7. Please keep this in mind and **submit your solution again after 10/7**.

- **IMPORTANT**: only the last submission counts. Please make sure the last submission succeeds.

- **IMPORTANT**: don't fork this repository. It'll be public!

**Comment by komfkore** [comment]
nit) Maybe add **assignment** label?

**Comment by minseongg** [comment]
@komfkore Thanks!

**Comment by minseongg** [comment]
**IMPORTANT**: Please do not implement your solution to pass only the inputs in the test cases.

For example: `fahrenheit_to_celsius` function in assignment 2 ([Problem](https://github.com/kaist-cp/cs220/blob/main/src/assignments/assignment02.rs#L14-L17), [Test cases](https://github.com/kaist-cp/cs220/blob/main/src/assignments/assignment02_grade.rs#L6-L9))

```rust
pub fn fahrenheit_to_celsius(degree: f64) -> f64 {
    if degree == 32.0 {
        0.0
    } else {
        100.0
    }
}
```

**Comment by minseongg** [comment]
The accepted rate for the homework 6 is as follows. (Except for the students who dropped the course)

- Total: 133
- Success: 122
- Success rate: 91.73%
