### ISSUE TITLE
[Homework 3] Error when testing fn organize

### ISSUE THREAD

**Issue by riskyben** [kaist-cp/cs220#64]
How do I solve this error?

```
running 1 test
thread 'assignments::assignment03_grade::test::test_organize' panicked at 'not yet implemented', src/assignments/assignment03.rs:196:5
stack backtrace:
```

I tried just deleting my code and returning a constant to see if I can get rid of this error and receive a different one but it still returns the same error

**Comment by Lee-Janggun** [comment]
It's complaining about a `todo!()` is `organize()`. If you did delete it, try running `cargo clean` first.

**Comment by riskyben** [comment]
It worked, thank you!

I have a separate question about the testcases for fn organize, why is P1 not in D2? Is it because P1 was immediately MOVED from D1 to D2 and not ADDED to any department first?

**Comment by minseongg** [comment]
> I have a separate question about the testcases for fn organize, why is P1 not in D2? Is it because P1 was immediately MOVED from D1 to D2 and not ADDED to any department first?

Yes. It is ignored.
