### ISSUE TITLE
Minor expression complains from compiler

### ISSUE THREAD

**Issue by songminwoo1** [kaist-cp/cs220#66]
My codes passed all tests with 'cargo test --lib assignment03_grade', and had no cargo clippy issue. But When I submitted, the server had compiler error. And it was some really minor complains about 

match statement with cases ending with ','

`
Some(A) => {
match my_func() { 
None => String::new(),
`
To
`
Some(A) => match my_func() {
None => String::new(),`
(case expression inside curly brackets, which could be written outside brackets. I had brackets on both ends.)

Also

```diff
 /// really?
-/// 
+///
 /// this is a document
```

 This multi line comment with more than one blank line

 and other similar complains.
 
 I won't ask for full credit. But is there any possibility of partial credit..?

**Comment by songminwoo1** [comment]
Also it even complained about comment location

//This is OK
pub fn piglatin(input: String) -> String {
    //a
    let mut chars = input.chars();

//This is not OK
pub fn piglatin(input: String) -> String {//a
    let mut chars = input.chars();

**Comment by zzz845zz** [comment]
Isn't it failed on `./scripts/grade-03.sh`? There is no partial score if you failed to pass the grader script..

**Comment by zzz845zz** [comment]
@songminwoo1 As https://github.com/kaist-cp/cs220/issues/76 said, We decided to give a chance for students who couldn't get scores for small reasons like you. Please format your solution and submit it again!

**Comment by songminwoo1** [comment]
thank you!
