### ISSUE TITLE
question regarding today's lecture 

### ISSUE THREAD

**Issue by quanxi1** [kaist-cp/cs220#68]
For verifying a program whose pre-condition P, post-condition Q and an invariant V,
does a checker(like why3, i don't know what it is called) check both of below:
1. If P holds and the entire program preserves V, then Q holds. 
2. V is indeed preserved during the entire program.

?

And are those the everything needed to be proved to verify the 'functionality' of a program?

**Comment by jeehoonkang** [comment]
Maybe would you please ask questions in a more concrete context? A concrete program, pre/post-conditions, and verification would help.

**Comment by quanxi1** [comment]
let fact_loop (n: int) : int
    requires { 0 < n }
    ensures  { result = fact n }
    = let ref m = 0 in
    let ref r = 1 in
    while m < n do
      invariant { 0 <= m <= n /\ r = fact m }
      variant { n - m }
      m <- m + 1;
      r <- r * m
    done;
    r

This is from ex2_fact.mlw. As we've learned today ,
`    requires { 0 < n }`
`    ensures  { result = fact n }`
They're pre-condition and post-condition respectively and

` invariant { 0 <= m <= n /\ r = fact m }`
this is the invariant that should be preserved while looping.

I was just curious that when why3 tells that this program is correct, 

1. if { 0 < n } and the invariant { 0 <= m <= n /\ r = fact m } is true for every looping,
then { result = fact n }.
2. The invariant is actually true for every looping. 

both above are proved to be true by why3.

My question was just to check if my understanding is correct for today's lecture.

**Comment by jeehoonkang** [comment]
The proof would consist of:
- That the function's pre-condition implies the invariant (for the first iteration);
- That the invariant /\ loop condition implies the invariant (after each iteration); and
- That the invariant /\ the negation of loop condition implies the function's post-condition.
