### ISSUE TITLE
Why3: Difference between `use` and `use import`

### ISSUE THREAD

**Issue by m-spitfire** [kaist-cp/cs220#70]
Hello. You have imported the required libraries for the program with `use <library>` in all the examples you provided. But in the homework 5 file(`binary_search.mlw`) you have imported the libraries with `use import <library>`. What's the difference between these two?

I am asking this question because I am getting a strange error when I declare a mutable integer with `let ref l = 0 in`, it says
```
This expression has type () but is expected to have type int
```
so I thought maybe this was related to how the `ref.Ref` was imported.

**Comment by jeehoonkang** [comment]
Thanks! I just removed `import` from the skeleton code.

**Comment by m-spitfire** [comment]
Just writing here as a reference: the error was due that I deleted the `0` at the end of the function.
