### ISSUE TITLE
[Homework 5] Time Complexity

### ISSUE THREAD

**Issue by idealyhn** [kaist-cp/cs220#71]
Hello.

Will the score varies depending on the time complexity in hw5?
I wrote two kinds of code. One is a conventional O(logn) binary search algorithm and the other is brute force O(n) algorithm, which is actually not a binary search. But it seems that all the codes pass the gg's test.

**Comment by jeehoonkang** [comment]
- Your binary search should have the time complexity `O(lg n)`, where `n` is the size of the array.
- We cannot check it automatically, but the TAs will review all submissions and determine if your implementation is indeed `O(lg n)`.

**Comment by jeehoonkang** [comment]
https://github.com/kaist-cp/cs220/issues/48#issuecomment-1263069704
