### ISSUE TITLE
Do we have no class on 10/4?

### ISSUE THREAD

**Issue by tlsdud020918** [kaist-cp/cs220#72]
The school has announced that all Tuesday courses on the 10/4 will be canceled and replaced with Monday's classes. 
I also have a 1:00PM class every Monday, so I have to go to the other class at 1:00PM on the 10/4. 
Is it correct that CS220 class will be canceled on 10/4?

**Comment by jeehoonkang** [comment]
No CS220 sessions on Oct. 4th.
