### ISSUE TITLE
[Homework 5] not legit submission on gg.kaist.ac.kr

### ISSUE THREAD

**Issue by junsooo** [kaist-cp/cs220#73]
Hello, Now i'm doing HW5.

What I did:
 - Made a file `binary_search.mlw`.
 - Filled TODO on "MY CODE" part.
```
(* Binary search

   A classical example. Searches a sorted array for a given value v.
   Consult <https://gitlab.inria.fr/why3/why3/-/blob/master/examples/binary_search.mlw>.
 *)

module BinarySearch

  use int.Int
  use int.ComputerDivision
  use ref.Ref
  use array.Array

  (* the code and its specification *)
  (MY CODE)
  0;

end
```
 - Verified my code on https://why3.lri.fr/try/. I press alt-R to verify my code, and i got some task list.(I didn't attach it cause it can be leak of some hw info)
 - I submitted my homework to gg. The error message is:
```
o you want opam to modify ~/.profile? [N/y/f]
(default is 'no', use 'f' to choose a different file) 
A hook can be added to opam's init scripts to ensure that the shell remains in sync with the opam environment when they are loaded. Set that up? [y/N] n
[NOTE] Package alt-ergo is already installed (current version is 2.4.2).
[NOTE] Package why3 is already installed (current version is 1.5.0).
Prover Alt-Ergo version 2.4.2 is not recognized.
  Known versions for this prover: 2.4.0, 2.4.1.
1 prover(s) added (including 1 prover(s) with an unrecognized version)
Save config to /home/runner/.why3.conf
Cloning into 'cs220'...
not legit submission
```
Now i got "not legit submission" but i don't know why. Am i doing something wrong?

**Comment by choejms** [comment]
I am having a same issue.
Previously I had a successful submission with "Yes" on "Success?" tab. 
I submitted the same file again, and I am getting "not legit submission."

**Comment by choejms** [comment]
Hi I just realized the reason.
https://github.com/kaist-cp/cs220/blob/main/assets/why3/binary_search.mlw
https://github.com/kaist-cp/cs220/issues/69

Here you can see that the code has been slightly modified with extra type annotation (It shouldn't affect correctness of your code though).

If you just copy and paste the updated skeleton code to your code, the submission should work.

**Comment by junsooo** [comment]
@choejms Thank you for your reply! It worked.
@KAIST16-Ryu  I think If you copy-paste the last commit(3a463b5) of https://github.com/kaist-cp/cs220/blob/main/assets/why3/binary_search.mlw , It will work.
