### ISSUE TITLE
[Homework 5] How to resolve expression is type() but int expected error

### ISSUE THREAD

**Issue by theonlyrealALEX** [kaist-cp/cs220#75]
I was not able to find anything on the web so I am asking here:
I get the following Error:
"This expression has type(), but is expected to have type int"
at the "let ref l = 0 in " line
Code(does not contain any solutions, just some trying out):
module BinarySearch

  use int.Int
  use int.ComputerDivision
  use ref.Ref
  use array.Array

  let binary_search (a : array int) (v : int) : int
    requires { forall i1 i2 : int. 0 <= i1 < i2 < length a -> a[i1] <= a[i2] }
    ensures  { 0 <= result <= length a }
    ensures  { forall i: int. 0 <= i < result -> a[i] < v }
    ensures  { forall i: int. result <= i < length a -> v <= a[i] }
  =
    (* IMPORTANT: DON'T MODIFY THE ABOVE LINES *)

    let ref l = 0 in
    let ref u = length a - 1  in
    while l<=u do

    done;

 (* TODO *)
end

PS: i dont know why formatting is so horrible, can't fix it

**Comment by m-spitfire** [comment]
Hello. I had the same problem. Add 0 at the end of the function: https://github.com/kaist-cp/cs220/issues/70#issuecomment-1261675412

**Comment by zzz845zz** [comment]
@theonlyrealALEX 

> PS: i dont know why formatting is so horrible, can't fix it

Please format your error message using Fenced Code Block in [here](https://www.markdownguide.org/cheat-sheet/#extended-syntax)

For example, If you typed the text like this:

\```
Your code
\```

The rendered output looks like this:

```
Your code
```

**Comment by theonlyrealALEX** [comment]
adding 0 worked perfect
