### ISSUE TITLE
[Homework 5] Prover result is: Timeout (5.00s) error

### ISSUE THREAD

**Issue by junsooo** [kaist-cp/cs220#77]
Hello, 
If we submit the skeleton code(https://github.com/kaist-cp/cs220/blob/main/assets/why3/binary_search.mlw) in gg, 
I got error from gg.
```
Do you want opam to modify ~/.profile? [N/y/f]
(default is 'no', use 'f' to choose a different file) 
A hook can be added to opam's init scripts to ensure that the shell remains in sync with the opam environment when they are loaded. Set that up? [y/N] n
[NOTE] Package alt-ergo is already installed (current version is 2.4.2).
[NOTE] Package why3 is already installed (current version is 1.5.0).
Prover Alt-Ergo version 2.4.2 is not recognized.
  Known versions for this prover: 2.4.0, 2.4.1.
1 prover(s) added (including 1 prover(s) with an unrecognized version)
Save config to /home/runner/.why3.conf
Cloning into 'cs220'...
File submission.mlw:
Goal binary_search'vc.
Prover result is: Timeout (5.00s).
```
So it says Prover result is timeout, but the skeleton code immediately returns 0, so i don't know why it results in timeout.
Also i finished writing my code and submitted to gg and got same error. Could you give me the possible reason for timeout (5.00s)? 

And Is there any method to use gg's prover in my local computer? There is no grade-05.sh, so I think it is not possible.
Thank you very much .

**Comment by m-spitfire** [comment]
Hello. The gg's prover is just running `why3 prove -P Alt-Ergo binary_search.mlw`. I use the command in my machine and got the same error `Timeout(5.00s)` when I just run on the skeleton code. I think it's because the prover tries to prove the postcondition, which is not implemented. When I run it against valid binary search code(provided in gitlab), it gives a Valid result as below: 
```
➜  why3 git:(main) ✗ why3 prove -P Alt-Ergo binary_search2.mlw
File binary_search2.mlw:
Goal binary_search'vc.
Prover result is: Valid (0.05s, 749 steps).
```

**Comment by choejms** [comment]
Timeout just means that the code has failed to prove the postcondition.

**Comment by junsooo** [comment]
Thank you. problem solved
