### ISSUE TITLE
Homework 2: gg returns code 1 for (maybe) valid code

### ISSUE THREAD

**Issue by junsooo** [kaist-cp/cs220#8]
Hello, Now i'm doing HW2.

On gg.kaist.ac.kr, I submitted my assignment02.rs and the log is:
<details>
===== SETUP =====

===== CHECK =====
[2022-08-31 16:20:21,831: WARNING/ForkPoolWorker-32] Demoting to runner...
info: downloading installer
info: profile set to 'default'
info: default host triple is x86_64-unknown-linux-gnu
warning: Updating existing toolchain, profile choice will be ignored
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.63.0 (4b91a6ea7 2022-08-08)

Rust is installed now. Great!

To get started you may need to restart your current shell.
This would reload your PATH environment variable to include
Cargo's bin directory ($HOME/.cargo/bin).

To configure your current shell, run:
source "$HOME/.cargo/env"
Cloning into 'cs220'...
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.63.0 (4b91a6ea7 2022-08-08)

info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'

  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.65.0-nightly (02654a084 2022-08-30)

info: checking for self-updates
    Checking cs220 v0.1.0 (/app/files/checks/0ddecad5-9047-4bf6-9175-2187a80681f1/cs220)
    Finished dev [unoptimized + debuginfo] target(s) in 0.37s
Running with cargo...

running 8 tests
test assignments::assignment02_grade::test::test_farenheit ... ok
test assignments::assignment02_grade::test::test_chooses ... ok
test assignments::assignment02_grade::test::test_fibonacci ... ok
test assignments::assignment02_grade::test::test_lyrics ... ok
test assignments::assignment02_grade::test::test_capitalize ... ok
test assignments::assignment02_grade::test::test_sum_array ... ok
test assignments::assignment02_grade::test::test_up3 ... ok
test assignments::assignment02_grade::test::test_zip ... ok

test result: ok. 8 passed; 0 failed; 0 ignored; 0 measured; 4 filtered out; finished in 0.00s

Running with cargo --release...

running 8 tests
test assignments::assignment02_grade::test::test_chooses ... ok
test assignments::assignment02_grade::test::test_farenheit ... ok
test assignments::assignment02_grade::test::test_capitalize ... ok
test assignments::assignment02_grade::test::test_fibonacci ... ok
test assignments::assignment02_grade::test::test_lyrics ... ok
test assignments::assignment02_grade::test::test_sum_array ... ok
test assignments::assignment02_grade::test::test_up3 ... ok
test assignments::assignment02_grade::test::test_zip ... ok

test result: ok. 8 passed; 0 failed; 0 ignored; 0 measured; 4 filtered out; finished in 0.00s

Running with cargo_asan...

running 8 tests
test assignments::assignment02_grade::test::test_farenheit ... ok
test assignments::assignment02_grade::test::test_fibonacci ... ok
test assignments::assignment02_grade::test::test_up3 ... ok
test assignments::assignment02_grade::test::test_sum_array ... ok
test assignments::assignment02_grade::test::test_capitalize ... ok
test assignments::assignment02_grade::test::test_lyrics ... ok
test assignments::assignment02_grade::test::test_chooses ... ok
test assignments::assignment02_grade::test::test_zip ... ok

test result: ok. 8 passed; 0 failed; 0 ignored; 0 measured; 4 filtered out; finished in 0.00s

Running with cargo_asan --release...

running 8 tests
test assignments::assignment02_grade::test::test_farenheit ... ok
test assignments::assignment02_grade::test::test_capitalize ... ok
test assignments::assignment02_grade::test::test_chooses ... ok
test assignments::assignment02_grade::test::test_fibonacci ... ok
test assignments::assignment02_grade::test::test_sum_array ... ok
test assignments::assignment02_grade::test::test_lyrics ... ok
test assignments::assignment02_grade::test::test_up3 ... ok
test assignments::assignment02_grade::test::test_zip ... ok

test result: ok. 8 passed; 0 failed; 0 ignored; 0 measured; 4 filtered out; finished in 0.00s

Running with cargo_tsan...

running 8 tests
test assignments::assignment02_grade::test::test_capitalize ... ok
test assignments::assignment02_grade::test::test_chooses ... ok
test assignments::assignment02_grade::test::test_farenheit ... ok
test assignments::assignment02_grade::test::test_fibonacci ... ok
test assignments::assignment02_grade::test::test_lyrics ... ok
test assignments::assignment02_grade::test::test_sum_array ... ok
test assignments::assignment02_grade::test::test_up3 ... ok
test assignments::assignment02_grade::test::test_zip ... ok

test result: ok. 8 passed; 0 failed; 0 ignored; 0 measured; 4 filtered out; finished in 0.00s

Running with cargo_tsan --release...

running 8 tests
test assignments::assignment02_grade::test::test_capitalize ... ok
test assignments::assignment02_grade::test::test_chooses ... ok
test assignments::assignment02_grade::test::test_farenheit ... ok
test assignments::assignment02_grade::test::test_fibonacci ... ok
test assignments::assignment02_grade::test::test_lyrics ... ok
test assignments::assignment02_grade::test::test_sum_array ... ok
test assignments::assignment02_grade::test::test_up3 ... ok
test assignments::assignment02_grade::test::test_zip ... ok

test result: ok. 8 passed; 0 failed; 0 ignored; 0 measured; 4 filtered out; finished in 0.00s
</details>

So I think I finished homework cause there are no fail cases. But gg's return code is 1,  so is there anything I haven't considered for homework? Thank you.

**Comment by m-spitfire** [comment]
Same issue here. Log says everything passed, but the return code is 1. It works fine on my machine too(with return code 0)
```bash
$ cargo test --lib assignment02_grade
    Finished test [unoptimized + debuginfo] target(s) in 0.15s
     Running unittests src/lib.rs (target/debug/deps/cs220-f3b72d2d58f85cad)

running 8 tests
test assignments::assignment02_grade::test::test_capitalize ... ok
test assignments::assignment02_grade::test::test_chooses ... ok
test assignments::assignment02_grade::test::test_farenheit ... ok
test assignments::assignment02_grade::test::test_fibonacci ... ok
test assignments::assignment02_grade::test::test_sum_array ... ok
test assignments::assignment02_grade::test::test_lyrics ... ok
test assignments::assignment02_grade::test::test_up3 ... ok
test assignments::assignment02_grade::test::test_zip ... ok

test result: ok. 8 passed; 0 failed; 0 ignored; 0 measured; 4 filtered out; finished in 0.00s

$ echo $?
0
```

**Comment by minseongg** [comment]
Thanks for reporting! We fixed the checker script in gg. Could you please submit it again?

**Comment by junsooo** [comment]
It works well! Thank you.
