### ISSUE TITLE
What if the cargo clean doesn't work?

### ISSUE THREAD

**Issue by Kimsungwook123** [kaist-cp/cs220#80]
I found out that it didn't work normally while testing. So I ran a cargo clean. However, it came out as below. So I looked up the related contents on git. But, I failed to remove nfs000000000602dadc00060c3c and other files. And yet the cargo clean still doesn't work. What should I do?

$ cargo clean
error: failed to remove build artifact

Caused by:
  failed to remove file `/home/sXXXXXXXX/cs220/target/debug/deps/.nfs000000000602dadc00060c3c`

Caused by:
  Device or resource busy (os error 16)

(I saw the this article.
https://github.com/rust-lang/vscode-rust/issues/630
https://github.com/rust-lang/cargo/issues/6943)

**Comment by minseongg** [comment]
Does the same error occur when you do `cargo clean` again?

If so, please try to move your `~/cs220/target` to another location (e.g., `mkdir ~/Trash; mv ~/cs220/target ~/Trash`) and then try again.

**Comment by Kimsungwook123** [comment]
thank you for answer!
