### ISSUE TITLE
[Assignment 4] What result is expected for Expression::Variable in calc_expression?

### ISSUE THREAD

**Issue by blziiiin** [kaist-cp/cs220#81]
I read all given .rs files but I cannot find what exactly function wants me to return.
In function "calc_expression()", what should I return if expression is variable ?
How can I get this answer? Is there any more reading stuff in notice or source?

**Comment by minseongg** [comment]
If the expression is variable, then you should return the value of the variable stored in `variables` field in the context.

If there is no such variable with the given name, then you should return an error.

(https://github.com/kaist-cp/cs220/blob/main/src/assignments/assignment04/context.rs#L13)
