### ISSUE TITLE
[Homework 5] About the postcondition

### ISSUE THREAD

**Issue by yj-han** [kaist-cp/cs220#83]
Hi, I have a question about one of the postconditions provided.

On the [line 17](https://github.com/kaist-cp/cs220/blob/3a463b55b16318cc4404d5ee5d954f067b969d6c/assets/why3/binary_search.mlw#L17), there is an `ensures` clause that for all indices smaller than `result`, their array elements should be smaller than `v`. However, if all of the elements in an array are `v`, then shouldn't the postcondition be `ensures { forall i: int. 0 <= i < result -> a[i] <= v }`? Otherwise, should `binary_search` return the smallest `result` available?

**Comment by choejms** [comment]
Yes, it should return the smallest index.

**Comment by yj-han** [comment]
@choejms @minseongg Thank you :)
