### ISSUE TITLE
HW4) Do I need to setup the pest?

### ISSUE THREAD

**Issue by albinjeon** [kaist-cp/cs220#84]
In a doc. They cargo csv-tool and edit the dependencies, and bring pest and pest_derive into scope in src/main.rs:. but I need pest in assignment files. how to set up the pest?

**Comment by minseongg** [comment]
You can do `cargo build` to set up pest.

**Comment by albinjeon** [comment]
In the assignment4 folder?

**Comment by minseongg** [comment]
It doesn't matter if your current directory is subdirectory of `cs220` directory.

**Comment by albinjeon** [comment]
In manual, If I add the pest to dependencies in Caro.toml, I should bring pest and pest_derive into main.rs. but I want to use this in syntex.rs. How can I use this? Just use pest::Parser in other files?

**Comment by minseongg** [comment]
Yes. You can use `pest::Parser` in other files.
