### ISSUE TITLE
[Homework 4] PrecClimber error when submitting  

### ISSUE THREAD

**Issue by nargizas** [kaist-cp/cs220#85]
When I submitted my zip file again after the nullification on 09/30, the website gave me the following error:

```
error: use of deprecated module `pest::prec_climber`: Use `pest::pratt_parser` instead (it is an equivalent which also supports unary prefix/suffix operators).
       While prec_climber is going to be kept in 2.x minor and patch releases, it may be removed in a future major release.
  --> src/assignments/assignment04/parser.rs:13:30
   |
13 | use pest::{iterators::Pairs, prec_climber::*};
   |                              ^^^^^^^^^^^^
   |
note: the lint level is defined here
  --> src/lib.rs:23:9
   |
23 | #![deny(warnings)]
   |         ^^^^^^^^
   = note: `#[deny(deprecated)]` implied by `#[deny(warnings)]`
```
However, everything is working fine on my local machine and the zip was accepted before.

**Comment by choejms** [comment]
Was there nullification?
I submitted my file on Sep 17th, but I don't see any nullification on gg.kaist.ac.kr.

**Comment by nargizas** [comment]
The [notice](https://github.com/kaist-cp/cs220/issues/41) says there would be one on 9/30, but I don't know if there was an actual nullification

**Comment by choejms** [comment]
Alright. This is another question for TAs, Are we supposed to resubmit even when there is no nullification on gg?

**Comment by minseongg** [comment]
We fixed the problem. Could you please try again?

Actually, we did not nullify previous submissions because there was no extra test cases. You do not have to resubmit :)

**Comment by nargizas** [comment]
Oh, I see! 
It works, thanks!
