### ISSUE TITLE
[Assignment 4] How to use SyntaxParser?

### ISSUE THREAD

**Issue by blziiiin** [kaist-cp/cs220#87]
I read https://pest.rs/book/examples/ini.html and follow parsing just like below
<pre>
<code>
...
use pest::Parser;

#[derive(Parser)]
#[grammar = "ini.pest"]
pub struct INIParser;
...
fn main() {
    let unparsed_file = fs::read_to_string("config.ini").expect("cannot read file");

    let file = INIParser::parse(Rule::file, &unparsed_file)
...
</code>
</pre>

But in my code, it makes error. Below is my implementation of using SyntaxParser and Error Message.
<pre>
<code>
pub fn parse_command(line: &str) -> Result<Command> {
    let tokens = inner::SyntaxParser::parse(inner::Rule, line);
}
</code>
</pre>

>"message": "no function or associated item named `parse` found for struct `SyntaxParser` in the current scope\nitems from traits can only be used if the trait is in scope",

I read docs again and again, googled lot to find how to handle derived Parser structure, but it is hard to find answer...Should I need to implement parse in struct SyntaxParser?

**Comment by ironore15** [comment]
You should include `use` to get namespace of `Parser::parse`.

For example,
```rust
pub fn parse_command(line: &str) -> Result {
    use pest::Parser;
    let tokens = inner::SyntaxParser::parse(inner::Rule, line);
}
```
