### ISSUE TITLE
[Assignment 4] Should we handle overflow when calculating?

### ISSUE THREAD

**Issue by blziiiin** [kaist-cp/cs220#89]
I pass test cases, but I am not sure that my program will also pass hidden cases.. I think invalid input when parsing, invalid expression and zero division is enough to pass the test so I used pure operator(+, -, *,  /) to calculate. Should I use other operating function to handle more errors like overflow?

**Comment by minseongg** [comment]
You can assume that there will be no overflow. Also, there is no hidden test case.
