### ISSUE TITLE
Homework2: No test code for gcd function.

### ISSUE THREAD

**Issue by idealyhn** [kaist-cp/cs220#9]
Hello. Now I am working on hw2 and found that there is no test code for `gcd(lhs, rhs)` function. 
So I tested the function with my own testcode. 
Is that intended?

**Comment by minseongg** [comment]
Nice catch! We added tests for `gcd` function. (https://github.com/kaist-cp/cs220/commit/45225857e964e7ada1ce37110db28ff09d0c7a19)
