### ISSUE TITLE
HW#4 ) Compile error while running test 

### ISSUE THREAD

**Issue by quanxi1** [kaist-cp/cs220#90]
Hi, I'm doing HW4 and I've just implemented parse_command in parser.rs. I wanted to run test in assignment04_grade.rs but when I click 'Run test' button I keep seeing the error message below and can't find out why it fails to compile. (I skipped some part due to maximum characters limitation.)

I've checked that it works as I intended in calc.rs using 'cargo run'. Could you please let me know the problem? 

---------------------------------------------------------------------------------------------------------------------------------

 *  작업 실행 중: cargo test --package cs220 --lib -- assignments::assignment04_grade::test --nocapture 

   Compiling cs220 v0.1.0 (/home/s20170785/cs220)
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/tmp/rustcZ4xZSX/symbols.o" "/home/s20170785/cs220/target/debug/deps/cs220-dd39386f8b9baa4f.112lr4tuh5k8ngcw.rcgu.o" "/home/s20170785/cs220/target/debug/deps/cs220-dd39386f8b9baa4f.11akgirhhxfoyqrt.rcgu.o" "/home/s20170785/cs220/target/debug/deps/cs220-dd39386f8b9baa4f.11n4ata5yfr6s9rs.rcgu.o" "/home/s20170785/cs220/target/debug/deps/cs220-dd39386f8b9baa4f.12ona8cfls7urtzx.rcgu.o" "/home/s20170785/cs220/target/debug/deps/cs220-dd39386f8b9baa4f.15y5ibv5joz5dpda.rcgu.o" "/home/s20170785/cs220/target/debug/deps/cs220-dd39386f8b9baa4f.16wol9rb1y8s4jc7.rcgu.o" "/home/s20170785/cs220/target/debug/deps/cs220-dd39386f8b9baa4f.19q9fq8lji3zrih8.rcgu.o" "/home/s20170785/cs220/target/debug/deps/cs220-dd39386f8b9baa4f.1av4ft8fhxg913hd.rcgu.o" "/home/s20170785/cs220/target/debug/deps/cs220-dd39386f8b9baa4f.1byzq1zwaz3gyrrr.rcgu.o" "/home/s20170785/cs220/target/debug/deps/cs220-dd39386f8b9baa4f.1cpnb12cubruqhb8.rcgu.o" "/home/s20170785/cs220/target/debug/deps/cs220-dd39386f8b9baa4f.1e743lt1hazkqzxi.rcgu.o" "/home/s20170785/cs220/target/debug/deps/cs220-dd39386f8b9baa4f.1fw02c3u9v9u4yo5.rcgu.o" "/home/s20170785/cs220/target/debug/deps/cs220-dd39386f8b9baa4f.1gxffm924mapk9i4.rcgu.o" "/home/s20170785/cs220/target/debug/deps/cs220-dd39386f8b9baa4f.1h4kf4wbzjqxsumy.rcgu.o" "/home/s20170785/cs220/target/debug/deps/cs220-dd39386f8b9baa4f.1hz89e5sfc4u5muu.rcgu.o" "/home/s20170785/cs220/target/debug/deps/cs220-dd39386f8b9baa4f.1j082qggni1nteoc.rcgu.o" "/home/s20170785/cs220/target/debug/deps/cs220-dd39386f8b9baa4f.1jxf9d24pox5qbmq.rcgu.o" "/home/s20170785/cs220/target/debug/deps/cs220-dd39386f8b9baa4f.1m2on0fcyr288u12.rcgu.o" "/home/s20170785/cs220/target/debug/deps/cs220-dd39386f8b9baa4f.1ncg75i7kkyc3ucf.rcgu.o" "/home/s20170785/cs220/target/debug/deps/cs220-dd39386f8b9baa4f.1njju892pg7okuxj.rcgu.o" "/home/s20170785/cs220/target/debug/deps/cs220-dd39386f8b9baa4f.1nrkjcuh1whhhzhj.rcgu.o" "/home/s20170785/cs220/target/debug/deps/cs220-dd39386f8b9baa4f.1oh074h74zmmenap.rcgu.o" "/home/s20170785/cs220/target/debug/deps/cs220-dd39386f8b9baa4f.1p84fnfnaplf74si.rcgu.o" "/home/s20170785/cs220/target/debug/deps/cs220-dd39386f8b9baa4f.1pt0lbge6o8qdzm4.rcgu.o" "/home/s20170785/cs220/target/debug/deps/cs220-dd39386f8b9baa4f.1pveb0d4swbw0nc1.rcgu.o" "/home/s20170785/cs220/target/debug/deps/cs220-dd39386f8b9baa4f.1qlix8t0eo22tny.rcgu.o" "/home/s20170785/cs220/target/debug/deps/cs220-dd39386f8b9baa4f.1uzisqt34ldf5u77.rcgu.o" "/home/s20170785/cs220/target/debug/deps/cs220-dd39386f8b9baa4f.1vjem6dy6xiixr6.rcgu.o" "/home/s20170785/cs220/target/debug/deps/cs220-dd39386f8b9baa4f.1w10ye9h10eplhkr.rcgu.o" "/home/s20170785/cs220/target/debug/deps/cs220-dd39386f8b9baa4f.1wghh6ee3xr6lr4z.rcgu.o" "/home/s20170785/cs220/target/debug/deps/cs220-dd39386f8b9baa4f.1x6wifo2uffirckn.rcgu.o" "/home/s20170785/cs220/target/debug/deps/cs220-

(ommitted)

0/src/assignments/assignment04_grade.rs:234: undefined reference to `<T as core::convert::Into<U>>::into'
          /usr/bin/ld: /home/s20170785/cs220/src/assignments/assignment04_grade.rs:229: undefined reference to `cs220::assignments::assignment04::context::Context::calc_command'
          /usr/bin/ld: /home/s20170785/cs220/src/assignments/assignment04_grade.rs:247: undefined reference to `<T as core::convert::Into<U>>::into'
          /usr/bin/ld: /home/s20170785/cs220/src/assignments/assignment04_grade.rs:248: undefined reference to `<T as core::convert::Into<U>>::into'
          /usr/bin/ld: /home/s20170785/cs220/src/assignments/assignment04_grade.rs:243: undefined reference to `cs220::assignments::assignment04::context::Context::calc_command'
          /usr/bin/ld: /home/s20170785/cs220/src/assignments/assignment04_grade.rs:261: undefined reference to `<T as core::convert::Into<U>>::into'
          /usr/bin/ld: /home/s20170785/cs220/src/assignments/assignment04_grade.rs:262: undefined reference to `<T as core::convert::Into<U>>::into'
          /usr/bin/ld: /home/s20170785/cs220/src/assignments/assignment04_grade.rs:257: undefined reference to `cs220::assignments::assignment04::context::Context::calc_command'
          /usr/bin/ld: /home/s20170785/cs220/src/assignments/assignment04_grade.rs:275: undefined reference to `<T as core::convert::Into<U>>::into'
          /usr/bin/ld: /home/s20170785/cs220/src/assignments/assignment04_grade.rs:276: undefined reference to `<T as core::convert::Into<U>>::into'
          /usr/bin/ld: /home/s20170785/cs220/src/assignments/assignment04_grade.rs:270: undefined reference to `cs220::assignments::assignment04::context::Context::calc_command'
          /usr/bin/ld: /home/s20170785/cs220/src/assignments/assignment04_grade.rs:287: undefined reference to `<T as core::convert::Into<U>>::into'
          /usr/bin/ld: /home/s20170785/cs220/src/assignments/assignment04_grade.rs:292: undefined reference to `<T as core::convert::Into<U>>::into'
          /usr/bin/ld: /home/s20170785/cs220/src/assignments/assignment04_grade.rs:293: undefined reference to `<T as core::convert::Into<U>>::into'
          /usr/bin/ld: /home/s20170785/cs220/src/assignments/assignment04_grade.rs:290: undefined reference to `<T as core::convert::Into<U>>::into'
          /usr/bin/ld: /home/s20170785/cs220/src/assignments/assignment04_grade.rs:296: undefined reference to `<T as core::convert::Into<U>>::into'
          /usr/bin/ld: /home/s20170785/cs220/target/debug/deps/cs220-dd39386f8b9baa4f.jk12i1gqhq6xeg8.rcgu.o:/home/s20170785/cs220/src/assignments/assignment04_grade.rs:288: more undefined references to `<T as core::convert::Into<U>>::into' follow
          /usr/bin/ld: /home/s20170785/cs220/target/debug/deps/cs220-dd39386f8b9baa4f.jk12i1gqhq6xeg8.rcgu.o: in function `cs220::assignments::assignment04_grade::test::test_context_calc_command':
          /home/s20170785/cs220/src/assignments/assignment04_grade.rs:282: undefined reference to `cs220::assignments::assignment04::context::Context::calc_command'
          /usr/bin/ld: /home/s20170785/cs220/src/assignments/assignment04_grade.rs:309: undefined reference to `<T as core::convert::Into<U>>::into'
          /usr/bin/ld: /home/s20170785/cs220/src/assignments/assignment04_grade.rs:310: undefined reference to `<T as core::convert::Into<U>>::into'
          /usr/bin/ld: /home/s20170785/cs220/src/assignments/assignment04_grade.rs:304: undefined reference to `cs220::assignments::assignment04::context::Context::calc_command'
          /usr/bin/ld: /home/s20170785/cs220/target/debug/deps/cs220-dd39386f8b9baa4f.s4g94yf0vpowv9q.rcgu.o: in function `<pest::iterators::pair::Pair<R> as core::fmt::Display>::fmt::{{closure}}':
          /home/s20170785/.cargo/registry/src/github.com-1ecc6299db9ec823/pest-2.3.1/src/iterators/pair.rs:297: undefined reference to `alloc::fmt::format'
          /usr/bin/ld: /home/s20170785/cs220/target/debug/deps/cs220-dd39386f8b9baa4f: hidden symbol `_ZN4core3ptr7mut_ptr31_$LT$impl$u20$$BP$mut$u20$T$GT$3sub17h6312ed146b830267E' isn't defined
          /usr/bin/ld: final link failed: bad value
          collect2: error: ld returned 1 exit status
          
  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `cs220` due to previous error

 *  터미널 프로세스 "cargo 'test', '--package', 'cs220', '--lib', '--', 'assignments::assignment04_grade::test', '--nocapture'"이(가) 종료되었습니다(종료 코드: 101). 
 *  터미널이 작업에서 다시 사용됩니다. 닫으려면 아무 키나 누르세요.

**Comment by minseongg** [comment]
Could you please do `cargo clean` and then try again?

**Comment by m-spitfire** [comment]
Hello @minseongg . This is one of the most asked questions, maybe you could , mention`cargo clean` in the homework description for the next homeworks?

**Comment by quanxi1** [comment]
@minseongg ah I missed there's some others with same problem, sorry for duplicate question. I'll try it soon

**Comment by minseongg** [comment]
@m-spitfire Thanks for suggestion! we will mention it for the next homeworks.
