### ISSUE TITLE
[Homework 5] The reason for existing multiple postconditions

### ISSUE THREAD

**Issue by dripcharacter** [kaist-cp/cs220#95]
![image](https://user-images.githubusercontent.com/53895663/193795682-a5545b62-3123-44d3-8433-6a54fc495634.png)
Now I am doing Homework 5 and I got multiple postconditions which are more than 3.
Since I only returned in last line, I expected that there will be only three postconditions. 
All postconditions are related with the last line but I don't know why there are 6 postconditions.

**Comment by choejms** [comment]
Can you try deleting parts of your code and see which lines are responsible for the postconditions?
