### ISSUE TITLE
[Homework 4] How to convert None to Err (Option to Result)

### ISSUE THREAD

**Issue by znunc** [kaist-cp/cs220#98]
Is there a way to convert None to Err without explicitly choose the error type?
I tried to use .ok_or() method but it didn't work well.
Is there a way to safely return Result type error without panicking?

**Comment by jeehoonkang** [comment]
the following methods should work:
- https://doc.rust-lang.org/std/option/enum.Option.html#method.ok_or
- https://doc.rust-lang.org/std/option/enum.Option.html#method.ok_or_else

**Comment by ironore15** [comment]
FYI, You can use `anyhow!()` macro to produce `anyhow::Error`. Check out crate [anyhow](https://docs.rs/anyhow/1.0.65/anyhow/).
